# Topic: https://www.youtube.com/@herenciadetimbiqui/releases
-
  file: "a-tomaco-lo-quemaron.mp3"
  title: "A Tomaco Lo Quemaron"
  artist: "Herencia De Timbiqui"
  album: "Herencia Pacifica"
  year: 2021
  url: "https://www.youtube.com/watch?v=B8HQQItvTWM"

-
  file: "el-caldo-de-piangua.mp3"
  title: "El Caldo De Piangua"
  artist: "Herencia De Timbiqui"
  album: "Herencia Pacifica"
  year: 2021
  url: "https://www.youtube.com/watch?v=H-0oLJr4jlc"

-
  file: "la-banda.mp3"
  title: "La Banda"
  artist: "Herencia De Timbiqui"
  album: "Herencia Pacifica"
  year: 2021
  url: "https://www.youtube.com/watch?v=PUDVRnKlJT8"

-
  file: "la-banda.mp3"
  title: "La Banda"
  artist: "Herencia De Timbiqui"
  album: "Herencia Pacifica"
  year: 2021
  url: "https://www.youtube.com/watch?v=gFZK6x2GVgc"

-
  file: "río-timbiquí.mp3"
  title: "Río Timbiquí"
  artist: "Herencia De Timbiqui"
  album: "Herencia Pacifica"
  year: 2021
  url: "https://www.youtube.com/watch?v=__pMrOwsw9A"

-
  file: "buenaventura.mp3"
  title: "Buenaventura"
  artist: "Herencia De Timbiqui"
  album: "Herencia Pacifica"
  year: 2021
  url: "https://www.youtube.com/watch?v=trU_TB18IRY"

-
  file: "memoria-de-justino.mp3"
  title: "Memoria De Justino"
  artist: "Herencia De Timbiqui"
  album: "Herencia Pacifica"
  year: 2021
  url: "https://www.youtube.com/watch?v=gFZK6x2GVgc"

-
  file: "y-qué.mp3"
  title: "Y Qué!"
  artist: "Herencia De Timbiqui"
  album: "Tambo"
  year: 2015
  url: "https://www.youtube.com/watch?v=aoCcYPFQgOw"

-
  file: "pacifico.mp3"
  title: "Pacifico"
  artist: "Herencia De Timbiqui"
  album: "Tambo"
  year: 2015
  url: "https://www.youtube.com/watch?v=pO0YmuK7y1E"

-
  file: "tambó.mp3"
  title: "Tambó"
  artist: "Herencia De Timbiqui"
  album: "Tambo"
  year: 2015
  url: "https://www.youtube.com/watch?v=JRgwSYbdc0M"

-
  file: "te-invito.mp3"
  title: "Te Invito"
  artist: "Herencia De Timbiqui"
  album: "Tambo"
  year: 2015
  url: "https://www.youtube.com/watch?v=ICIDjTaE79E"

-
  file: "serenata-a-mamá.mp3"
  title: "Serenata A Mamá"
  artist: "Herencia De Timbiqui"
  album: "Tambo"
  year: 2015
  url: "https://www.youtube.com/watch?v=aieCgBwIm9g"

-
  file: "rumba.mp3"
  title: "Rumba"
  artist: "Herencia De Timbiqui"
  album: "Tambo"
  year: 2015
  url: "https://www.youtube.com/watch?v=YYafIH7HIg0"

-
  file: "amanecé.mp3"
  title: "Amanecé"
  artist: "Herencia De Timbiqui"
  album: "This Is Gozar"
  year: 2014
  url: "https://www.youtube.com/watch?v=AErXyO7V5qY"

-
  file: "sabrás.mp3"
  title: "Sabrás"
  artist: "Herencia De Timbiqui"
  album: "This Is Gozar"
  year: 2014
  url: "https://www.youtube.com/watch?v=fB8BdNdqtr0"

