# List: https://www.youtube.com/playlist?list=OLAK5uy_n2nFJP95k5thFZVSVJ1uUlnguHHVu_XbQ

-
  file: "ven-ven.mp3"
  title: "Ven Ven"
  artist: "Pacho Galán"
  album: "Homenaje a Los Grandes Compositores de la Musica Tropical Colombiana Volume 5"
  year: 2011
  url: "https://www.youtube.com/watch?v=Ta1LnIrLExk"

-
  file: "boquita-salá.mp3"
  title: "Boquita Salá"
  artist: "Pacho Galán"
  album: "Homenaje a Los Grandes Compositores de la Musica Tropical Colombiana Volume 5"
  year: 2011
  url: "https://www.youtube.com/watch?v=go9Q1FFgwcg"

-
  file: "ay-cosita-linda.mp3"
  title: "Ay Cosita Linda"
  artist: "Pacho Galán"
  album: "Homenaje a Los Grandes Compositores de la Musica Tropical Colombiana Volume 5"
  year: 2011
  url: "https://www.youtube.com/watch?v=N9FAFjvvp88"

-
  file: "quiero-amanecer.mp3"
  title: "Quiero Amanecer"
  artist: "Pacho Galán"
  album: "Homenaje a Los Grandes Compositores de la Musica Tropical Colombiana Volume 5"
  year: 2011
  url: "https://www.youtube.com/watch?v=Pps401dMJfU"

-
  file: "el-merecumbé.mp3"
  title: "El Merecumbé"
  artist: "Pacho Galán"
  album: "Homenaje a Los Grandes Compositores de la Musica Tropical Colombiana Volume 5"
  year: 2011
  url: "https://www.youtube.com/watch?v=yMmYsw8sU54"

-
  file: "la-casa-de-fernando.mp3"
  title: "La Casa De Fernando"
  artist: "Pacho Galán"
  album: "Homenaje a Los Grandes Compositores de la Musica Tropical Colombiana Volume 5"
  year: 2011
  url: "https://www.youtube.com/watch?v=UxL-DvRNvD0"

-
  file: "la-butifarra-de-pacho.mp3"
  title: "La Butifarra De Pacho"
  artist: "Pacho Galán"
  album: "Homenaje a Los Grandes Compositores de la Musica Tropical Colombiana Volume 5"
  year: 2011
  url: "https://www.youtube.com/watch?v=ZmjZHwRmGy8"

-
  file: "ligia.mp3"
  title: "Ligia"
  artist: "Pacho Galán"
  album: "Homenaje a Los Grandes Compositores de la Musica Tropical Colombiana Volume 5"
  year: 2011
  url: "https://www.youtube.com/watch?v=MmDiElSeeaE"

-
  file: "algo-se-me-va.mp3"
  title: "Algo Se Me Va"
  artist: "Pacho Galán"
  album: "Homenaje a Los Grandes Compositores de la Musica Tropical Colombiana Volume 5"
  year: 2011
  url: "https://www.youtube.com/watch?v=I7MhsGAa0Wc"

-
  file: "las-cosas-de-la-vida.mp3"
  title: "Las Cosas De La Vida"
  artist: "Pacho Galán"
  album: "Homenaje a Los Grandes Compositores de la Musica Tropical Colombiana Volume 5"
  year: 2011
  url: "https://www.youtube.com/watch?v=2P2tHdPPpoY"

-
  file: "ave-pa-ve.mp3"
  title: "Ave Pa' Ve"
  artist: "Pacho Galán"
  album: "Homenaje a Los Grandes Compositores de la Musica Tropical Colombiana Volume 5"
  year: 2011
  url: "https://www.youtube.com/watch?v=fxO2zYxhyxE"

-
  file: "guepa-je.mp3"
  title: "Guepa' Je"
  artist: "Pacho Galán"
  album: "Homenaje a Los Grandes Compositores de la Musica Tropical Colombiana Volume 5"
  year: 2011
  url: "https://www.youtube.com/watch?v=nENABUHlf0E"

-
  file: "deciembre-azul.mp3"
  title: "Deciembre Azul"
  artist: "Pacho Galán"
  album: "Homenaje a Los Grandes Compositores de la Musica Tropical Colombiana Volume 5"
  year: 2011
  url: "https://www.youtube.com/watch?v=epX7P4NhkLg"

