# Topic: https://www.youtube.com/channel/UCjUpTJ06apcNOjQDaDAVVfw (El Mola)
# Topic: https://www.youtube.com/channel/UCPhmkScCZtTEMXObWUg9CkA (M.O.L.A)
-
  file: "intro.mp3"
  title: "Intro"
  artist: "El Mola"
  album: "Molano"
  year: 2011
  genre: "Timbaton"
  url: "https://www.youtube.com/watch?v=nIxlrRoMlHs"

-
  file: "calle.mp3"
  title: "Calle"
  artist: "El Mola"
  album: "Molano"
  year: 2011
  genre: "Timbaton"
  url: "https://www.youtube.com/watch?v=9f2UYFp-t98"

-
  file: "no-se-coje-con-la-mano.mp3"
  title: "No Se Coje Con La Mano"
  artist: "El Mola"
  album: "Molano"
  year: 2011
  genre: "Timbaton"
  url: "https://www.youtube.com/watch?v=RbLf7i7mHz8"

-
  file: "dejenme-vivir.mp3"
  title: "Dejenme Vivir"
  artist: "El Mola"
  album: "Molano"
  year: 2011
  genre: "Timbaton"
  url: "https://www.youtube.com/watch?v=fZur7jQh8PQ"

-
  file: "eres-una-loka.mp3"
  title: "Eres Una Loka"
  artist: "El Mola"
  album: "Molano"
  year: 2011
  genre: "Timbaton"
  url: "https://www.youtube.com/watch?v=_l32TLmGYPE"

-
  file: "no-llames-mas.mp3"
  title: "No Llames Mas"
  artist: "El Mola"
  album: "Molano"
  year: 2011
  genre: "Timbaton"
  url: "https://www.youtube.com/watch?v=7WhKIKF4e5g"

-
  file: "dejala-que-baile.mp3"
  title: "Dejala Que Baile"
  artist: "El Mola"
  album: "Molano"
  year: 2011
  genre: "Timbaton"
  url: "https://www.youtube.com/watch?v=by3HIP2fE_w"

-
  file: "la-visa.mp3"
  title: "La Visa"
  artist: "El Mola"
  album: "Molano"
  year: 2011
  genre: "Timbaton"
  url: "https://www.youtube.com/watch?v=zzqW7lfqhh0"

-
  file: "lo-que-yo-te-traigo.mp3"
  title: "Lo Que Yo Te Traigo"
  artist: "El Mola"
  album: "Molano"
  year: 2011
  genre: "Timbaton"
  url: "https://www.youtube.com/watch?v=r1sTX5iOEGY"

-
  file: "armando-pena-muerte.mp3"
  title: "Armando Pena Muerte"
  artist: "El Mola"
  album: "Molano"
  year: 2011
  genre: "Timbaton"
  url: "https://www.youtube.com/watch?v=Rd1HuCRyT5Y"

-
  file: "no-se-lo-que-tu-tienes.mp3"
  title: "No Se Lo Que Tu Tienes"
  artist: "El Mola"
  album: "Molano"
  year: 2011
  genre: "Timbaton"
  url: "https://www.youtube.com/watch?v=Li5CTekEdUU"

-
  file: "una-cualquiera.mp3"
  title: "Una Cualquiera"
  artist: "El Mola"
  album: "Molano"
  year: 2011
  genre: "Timbaton"
  url: "https://www.youtube.com/watch?v=lbs6EGAsczc"

