-
  file: "la-verdad.mp3"
  title: "La Verdad"
  artist: "El Niño y La Verdad"
  album: "Llegó La Verdad"
  year: 2014
  genre: "Timba"
  url: "https://www.youtube.com/watch?v=vX1vwcLU2q8"

-
  file: "ese-soy-yo.mp3"
  title: "Ese Soy Yo"
  artist: "El Niño y La Verdad"
  album: "Llegó La Verdad"
  year: 2014
  genre: "Timba"
  url: "https://www.youtube.com/watch?v=ftQxs0dIYAo"

-
  file: "loco-pero-te-amo.mp3"
  title: "Loco Pero Te Amo"
  artist: "El Niño y La Verdad"
  album: "Llegó La Verdad"
  year: 2014
  genre: "Timba"
  url: "https://www.youtube.com/watch?v=IvJ-dp9Jl2w"

-
  file: "la-mata.mp3"
  title: "La Mata"
  artist: "El Niño y La Verdad"
  album: "Llegó La Verdad"
  year: 2014
  genre: "Timba"
  url: "https://www.youtube.com/watch?v=m8tlfP9c1E0"

-
  file: "yo-si-camino-la-habana.mp3"
  title: "Yo Si Camino La Habana"
  artist: "El Niño y La Verdad"
  album: "Llegó La Verdad"
  year: 2014
  genre: "Timba"
  url: "https://www.youtube.com/watch?v=5zGzyRxTN9A"

-
  file: "llévame-papá.mp3"
  title: "Llévame Papá"
  artist: "El Niño y La Verdad"
  album: "Más Duro"
  year: 2016
  genre: "Timba"
  url: "https://www.youtube.com/watch?v=Hkzm-pHhoB0"

-
  file: "pa-ti-y-pa-mi.mp3"
  title: "Pa Ti Y Pa Mi"
  artist: "El Niño y La Verdad"
  album: "Más Duro"
  year: 2016
  genre: "Timba"
  url: "https://www.youtube.com/watch?v=jD4nIMGcFlc"

-
  file: "el-perro-y-el-sofá.mp3"
  title: "El Perro y El Sofá"
  artist: "El Niño y La Verdad"
  album: "Más Duro"
  year: 2016
  genre: "Timba"
  url: "https://www.youtube.com/watch?v=yqCztyAR5BM"

-
  file: "con-elegua-y-con-orula.mp3"
  title: "Con Elegua Y Con Orula"
  artist: "El Niño y La Verdad"
  album: "Más Duro"
  year: 2016
  genre: "Timba"
  url: "https://www.youtube.com/watch?v=MerW113Jeks"

-
  file: "el-secreto.mp3"
  title: "El Secreto"
  artist: "El Niño y La Verdad"
  album: "Más Duro"
  year: 2016
  genre: "Timba"
  url: "https://www.youtube.com/watch?v=e1zKCnkIdWA"

-
  file: "las-manzanas.mp3"
  title: "Las Manzanas"
  artist: "El Niño y La Verdad"
  album: "De Vuelta Al Barrio"
  year: 2018
  genre: "Timba"
  url: "https://www.youtube.com/watch?v=O9Seqz4JFAw"

-
  file: "la-cosa-mala.mp3"
  title: "La Cosa Mala"
  artist: "El Niño y La Verdad"
  album: "De Vuelta Al Barrio"
  year: 2018
  genre: "Timba"
  url: "https://www.youtube.com/watch?v=et8gHrBf_6s"

-
  file: "el-nombrecito.mp3"
  title: "El Nombrecito"
  artist: "El Niño y La Verdad"
  album: "De Vuelta Al Barrio"
  year: 2018
  genre: "Timba"
  url: "https://www.youtube.com/watch?v=67GY0oJ3u6k"

-
  file: "el-padrino.mp3"
  title: "El Padrino"
  artist: "El Niño y La Verdad"
  album: "El Hijo Del Viento"
  year: 2022
  genre: "Timba"
  url: "https://www.youtube.com/watch?v=wzx59U6h4CY"

