# Topic: https://www.youtube.com/@LosVanVan/releases

-
  file: "al-paso.mp3"
  title: "Al Paso"
  artist: "Los Van Van"
  album: "Legado"
  year: 2018
  genre: "Timba"
  url: "https://www.youtube.com/watch?v=sEYEnZx4R1g"

-
  file: "aquí-el-que-baila-gana.mp3"
  title: "Aquí el Que Baila Gana"
  artist: "Los Van Van"
  album: "Colección Juan Formell y Los Van Van, Vol. XV"
  year: 1995
  genre: "Timba"
  url: "https://www.youtube.com/watch?v=ZA1wE3-IbsE"

-
  file: "el-negro-esta-cocinando.mp3"
  title: "El Negro Esta Cocinando"
  artist: "Los Van Van"
  album: "Llego... Van Van"
  year: 2003
  genre: "Timba"
  url: "https://www.youtube.com/watch?v=A1EDfmBnuag"

-
  file: "esto-te-pone-la-cabeza-mala.mp3"
  title: "Esto Te Pone La Cabeza Mala"
  artist: "Los Van Van"
  album: "Esto Te Pone La Cabeza Mala"
  year: 1997
  genre: "Timba"
  url: "https://www.youtube.com/watch?v=48VjCS6i4Sc"

-
  file: "la-maquinaria.mp3"
  title: "La Maquinaria"
  artist: "Los Van Van"
  album: "La Maquinaria"
  year: 2011
  genre: "Timba"
  url: "https://www.youtube.com/watch?v=n57YHo1527c"

-
  file: "me-mantengo.mp3"
  title: "Me Mantengo"
  artist: "Los Van Van"
  album: "The Real Cuban Music: Timba"
  year: 2008
  genre: "Timba"
  url: "https://www.youtube.com/watch?v=N1eaRZqO6u4"

