-
  file: "el-chevrolito.mp3"
  title: "El Chevrolito"
  artist: "Carlos Vives"
  album: "Escalona Volumen 2"
  year: 1992
  genre: "Vallenato"

-
  file: "el-general-dangond.mp3"
  title: "El General Dangond"
  artist: "Carlos Vives"
  album: "Escalona Volumen 2"
  year: 1992
  genre: "Vallenato"

-
  file: "el-hambre-del-liceo.mp3"
  title: "El Hambre Del Liceo"
  artist: "Carlos Vives"
  album: "Escalona Volumen 2"
  year: 1992
  genre: "Vallenato"

-
  file: "el-pirata-de-loperena.mp3"
  title: "El Pirata De Loperena"
  artist: "Carlos Vives"
  album: "Escalona Volumen 2"
  year: 1992
  genre: "Vallenato"

-
  file: "el-playonero.mp3"
  title: "El Playonero"
  artist: "Carlos Vives"
  album: "Escalona Volumen 2"
  year: 1992
  genre: "Vallenato"

-
  file: "la-brasilera.mp3"
  title: "La Brasilera"
  artist: "Carlos Vives"
  album: "Escalona Volumen 2"
  year: 1992
  genre: "Vallenato"

-
  file: "la-casa-en-el-aire.mp3"
  title: "La Casa En El Aire"
  artist: "Carlos Vives"
  album: "Escalona Volumen 2"
  year: 1992
  genre: "Vallenato"

-
  file: "la-despedida.mp3"
  title: "La Despedida"
  artist: "Carlos Vives"
  album: "Escalona Volumen 2"
  year: 1992
  genre: "Vallenato"

-
  file: "la-historia.mp3"
  title: "La Historia"
  artist: "Carlos Vives"
  album: "Escalona Volumen 2"
  year: 1992
  genre: "Vallenato"

-
  file: "la-maye.mp3"
  title: "La Maye"
  artist: "Carlos Vives"
  album: "Escalona Volumen 2"
  year: 1992
  genre: "Vallenato"

-
  file: "la-vieja-sara.mp3"
  title: "La Vieja Sara"
  artist: "Carlos Vives"
  album: "Escalona Volumen 2"
  year: 1992
  genre: "Vallenato"

-
  file: "mala-suerte.mp3"
  title: "Mala Suerte"
  artist: "Carlos Vives"
  album: "Escalona Volumen 2"
  year: 1992
  genre: "Vallenato"

-
  file: "paraguachon.mp3"
  title: "Paraguachon"
  artist: "Carlos Vives"
  album: "Escalona Volumen 2"
  year: 1992
  genre: "Vallenato"
