-
  file: "no-vale-la-pena.mp3"
  title: "No Vale La Pena"
  artist: "Isaac Delgado"
  album: "Asi Soy"
  year: 2008
  genre: "Timba"
  url: "https://www.youtube.com/watch?v=jivqFHHKe3U"

-
  file: "los-barrios-de-la-habana.mp3"
  title: "Los Barrios de la Habana"
  artist: "NG La Banda"
  album: "Vamos Caminando"
  year: 2019
  genre: "Timba"
  url: "https://www.youtube.com/watch?v=xAQf1NzjeAA"
