-
  file: "bi-lambam.mp3"
  title: "Bi Lambam"
  artist: "Toumani Diabate with Ballake Sissoko"
  album: "New Ancient Strings"
  year: 1999
  genre: "Kora"

-
  file: "salaman.mp3"
  title: "Salaman"
  artist: "Toumani Diabate with Ballake Sissoko"
  album: "New Ancient Strings"
  year: 1999
  genre: "Kora"

-
  file: "kita-kaira.mp3"
  title: "Kita Kaira"
  artist: "Toumani Diabate with Ballake Sissoko"
  album: "New Ancient Strings"
  year: 1999
  genre: "Kora"

-
  file: "bafoulabe.mp3"
  title: "Bafoulabe"
  artist: "Toumani Diabate with Ballake Sissoko"
  album: "New Ancient Strings"
  year: 1999
  genre: "Kora"

-
  file: "cheiknah-demba.mp3"
  title: "Cheiknah Demba"
  artist: "Toumani Diabate with Ballake Sissoko"
  album: "New Ancient Strings"
  year: 1999
  genre: "Kora"

-
  file: "kora-bali.mp3"
  title: "Kora Bali"
  artist: "Toumani Diabate with Ballake Sissoko"
  album: "New Ancient Strings"
  year: 1999
  genre: "Kora"

-
  file: "kadiatou.mp3"
  title: "Kadiatou"
  artist: "Toumani Diabate with Ballake Sissoko"
  album: "New Ancient Strings"
  year: 1999
  genre: "Kora"

-
  file: "yamfa.mp3"
  title: "Yamfa"
  artist: "Toumani Diabate with Ballake Sissoko"
  album: "New Ancient Strings"
  year: 1999
  genre: "Kora"
