-
  file: "cancion-bonita.mp3"
  title: "Cancion Bonita"
  artist: "El Micha"
  album: "Cancion Bonita"
  year: 2017
  featured_artist: "Diana Fuentes"
  genre: "Timbaton"
  url: "https://www.youtube.com/watch?v=MWTESUHBqY0"

-
  file: "donde-estan.mp3"
  title: "Donde Estan"
  artist: "Este Habana"
  album: "Como Venga"
  year: 2011
  genre: "Timbaton"
  url: "https://www.youtube.com/watch?v=0fLOlWaUfnE"

-
  file: "eso-es-bola.mp3"
  title: "Eso Es Bola"
  artist: "Los Desiguales"
  album: "Eso Es Bola"
  year: 2016
  genre: "Timbaton"
  url: "https://www.youtube.com/watch?v=vzpnAB_OhdE"

-
  file: "lo-que-tengo-yo.mp3"
  title: "Lo Que Tengo Yo"
  artist: "Los 4"
  album: "Asi Somos"
  year: 2018
  genre: "Timbaton"
  url: "https://www.youtube.com/watch?v=iAN26j4kP_U"

-
  file: "si-se-va-a-formar-que-se-forme.mp3"
  title: "Si Se Va a Formar Que Se Forme"
  artist: "Los 4"
  album: "Escucha Lo Que Traje"
  year: 2010
  genre: "Timbaton"
  url: "https://www.youtube.com/watch?v=Ai9ef6xr0gk"

