-
  file: "guanabacoa.mp3"
  title: "Guanabacoa"
  artist: "Ivan El Hijo de Teresa y La Llegada"
  album: "Santa Palabra"
  year: 2020
  genre: "Timba"
  url: "https://www.youtube.com/watch?v=pkKBiKC_if0"

-
  file: "sin-son-no-hay-salsa.mp3"
  title: "Sin Son No Hay Salsa"
  artist: "Ivan El Hijo de Teresa y La Llegada"
  album: "Santa Palabra"
  year: 2020
  genre: "Timba"
  url: "https://www.youtube.com/watch?v=Af7nK3YbSMY"

-
  file: "cuando-toca-toca.mp3"
  title: "Cuando Toca, Toca"
  artist: "Ivan El Hijo de Teresa y La Llegada"
  album: "Santa Palabra"
  year: 2020
  genre: "Timba"
  url: "https://www.youtube.com/watch?v=P_mKcLyOdMc"

-
  file: "a-la-medida-justa.mp3"
  title: "A La Medida Justa"
  artist: "Ivan El Hijo de Teresa y La Llegada"
  album: "Santa Palabra"
  year: 2020
  genre: "Timba"
  url: "https://www.youtube.com/watch?v=kMCJiH5_eEc"

