-
  file: "trench-town-rock.mp3"
  title: "Trenchtown Rock"
  artist: "Bob Marley and the Wailers"
  album: "Trenchtown Rock"
  year: 1971
  genres: "Reggae"
  link: "https://www.youtube.com/watch?v=KSxDCpVSm5s"

-
  file: "roots-rock-reggae.mp3"
  title: "Roots, Rock, Reggae"
  artist: "Bob Marley and the Wailers"
  album: "Rastaman Vibration"
  year: 1976
  genres: "Reggae"
  link: "https://www.youtube.com/watch?v=OQYmGg3mKHg"
  
-
  file: "lively-up-yourself.mp3"
  title: "Lively Up Yourself"
  artist: "Bob Marley and the Wailers"
  album: "Lively Up Yourself"
  year: 1971
  genres: "Reggae"
  link: "https://www.youtube.com/watch?v=4OhGncMeeA8"

-
  file: "positive-vibration.mp3"
  title: "Positive Vibration"
  artist: "Bob Marley and the Wailers"
  album: "Rastaman Vibration"
  year: 1976
  genres: "Reggae"
  link: "https://www.youtube.com/watch?v=b0DU5uhoq-4"

-
  file: "easy-skanking.mp3"
  title: "Easy Skanking"
  artist: "Bob Marley and the Wailers"
  album: "Kaya"
  year: 1978
  genres: "Reggae"
  link: "https://www.youtube.com/watch?v=wlqB13iJu2o"

-
  file: "kaya.mp3"
  title: "Kaya"
  artist: "Bob Marley and the Wailers"
  album: "Kaya"
  year: 1978
  genres: "Reggae"
  link: "https://www.youtube.com/watch?v=q8bFkr22-j4"

-
  file: "mellow-mood.mp3"
  title: "Mellow Mood"
  artist: "Bob Marley and the Wailers"
  album: "Mellow Mood"
  year: 1967
  genres: "Reggae"
  link: "https://www.youtube.com/watch?v=MBv64Azlt0A"

-
  file: "natty-dread.mp3"
  title: "Natty Dread"
  artist: "Bob Marley and the Wailers"
  album: "Natty Dread"
  year: 1974
  genres: "Reggae"
  link: "https://www.youtube.com/watch?v=rhgxFqKyz98"

-
  file: "sun-is-shining.mp3"
  title: "Sun is Shining"
  artist: "Bob Marley and the Wailers"
  album: "Kaya"
  year: 1978
  genres: "Reggae"
  link: "https://www.youtube.com/watch?v=By0JgNIE76M"

-
  file: "turn-your-lights-down-low.mp3"
  title: "Turn Your Lights Down Low"
  artist: "Bob Marley and the Wailers"
  album: "Exodus"
  year: 1977
  genres: "Reggae"
  link: "https://www.youtube.com/watch?v=fRid8Tjw_bU"

-
  file: "buffalo-soldier.mp3"
  title: "Buffalo Soldier"
  artist: "Bob Marley and the Wailers"
  album: "Confrontation"
  year: 1983
  genres: "Reggae"
  link: "https://www.youtube.com/watch?v=QiESgCu9Ehw"

-
  file: "jah-live.mp3"
  title: "Jah Live"
  artist: "Bob Marley and the Wailers"
  album: "Jah Live"
  year: 1975
  genres: "Reggae"
  link: "https://www.youtube.com/watch?v=K0Ux_w4XV_g"

-
  file: "i-know-a-place.mp3"
  title: "I Know a Place"
  artist: "Bob Marley and the Wailers"
  album: "I Know a Place EP"
  year: 2001
  genres: "Reggae"
  link: "https://www.youtube.com/watch?v=NHWoPxClne4"

-
  file: "high-tide-or-low-tide.mp3"
  title: "High Tide Or Low Tide"
  artist: "Bob Marley and the Wailers"
  album: "Catch a Fire"
  year: 1973
  genres: "Reggae"
  link: "https://www.youtube.com/watch?v=KWeDXyxT3Qg"

-
  file: "exodus.mp3"
  title: "Exodus"
  artist: "Bob Marley and the Wailers"
  album: "Exodus"
  year: 1977
  genres: "Reggae"
  link: "https://www.youtube.com/watch?v=QBeNlUG0Vyc"

-
  file: "could-you-be-loved.mp3"
  title: "Could You Be Loved"
  artist: "Bob Marley and the Wailers"
  album: "Uprising"
  year: 1980
  genres: "Reggae"
  link: "https://www.youtube.com/watch?v=1ti2YCFgCoI"
