-
  file: "las-islas-del-sabor.mp3"
  title: "Las Islas Del Sabor"
  artist: "Edwin Bonilla"
  album: "Edwin Y Su Son"
  year: 1999
  url: "https://www.youtube.com/watch?v=c7lsJ7vIbbI"

-
  file: "si-te-busco-en-el-baile.mp3"
  title: "Si Te Busco En El Baile"
  artist: "Edwin Bonilla"
  album: "Edwin Y Su Son"
  year: 1999
  url: "https://www.youtube.com/watch?v=emXTukugl8o"

-
  file: "si-tu-no-vienes-no-bailas.mp3"
  title: "Si Tu No Vienes No Bailas"
  artist: null
  album: null
  year: null
  url: "https://www.youtube.com/watch?v=0EZCObbaSKA"

-
  file: "yo-me-la-llevo.mp3"
  title: "Yo Me La Llevo"
  artist: "Edwin Bonilla"
  album: "Pa' La Calle"
  year: 2004
  url: "https://www.youtube.com/watch?v=WwFbWejVCTU"

-
  file: "se-le-ve.mp3"
  title: "Se Le Ve"
  artist: null
  album: null
  year: null
  url: "https://www.youtube.com/watch?v=45Ui7u0KAns"

