# List: https://www.youtube.com/playlist?list=OLAK5uy_kR4dsQRxLvBj6rrS7dfDX2Asmdns0PEWg

-
  file: "la-brasilera.mp3"
  title: "La Brasilera"
  artist: "Rafael Escalona"
  album: "Homenaje a Los Grandes Compositores de la Musica Tropical Colombiana Volume 3"
  year: 2011
  genre: "Vallenato"
  url: "https://www.youtube.com/watch?v=H_AOtasBxqY"

-
  file: "el-testamento.mp3"
  title: "El Testamento"
  artist: "Rafael Escalona"
  album: "Homenaje a Los Grandes Compositores de la Musica Tropical Colombiana Volume 3"
  year: 2011
  genre: "Vallenato"
  url: "https://www.youtube.com/watch?v=Cd7Jg4Q4nhs"

-
  file: "el-viejo-migue.mp3"
  title: "El Viejo Migue"
  artist: "Rafael Escalona"
  album: "Homenaje a Los Grandes Compositores de la Musica Tropical Colombiana Volume 3"
  year: 2011
  genre: "Vallenato"
  url: "https://www.youtube.com/watch?v=R77XgBNcV-0"

-
  file: "el-almirante-padilla.mp3"
  title: "El Almirante Padilla"
  artist: "Rafael Escalona"
  album: "Homenaje a Los Grandes Compositores de la Musica Tropical Colombiana Volume 3"
  year: 2011
  genre: "Vallenato"
  url: "https://www.youtube.com/watch?v=DzvAcgI9h6w"

-
  file: "la-casa-en-el-aire.mp3"
  title: "La Casa En El Aire"
  artist: "Rafael Escalona"
  album: "Homenaje a Los Grandes Compositores de la Musica Tropical Colombiana Volume 3"
  year: 2011
  genre: "Vallenato"
  url: "https://www.youtube.com/watch?v=Xpqu2HuReuM"

-
  file: "la-molinera.mp3"
  title: "La Molinera"
  artist: "Rafael Escalona"
  album: "Homenaje a Los Grandes Compositores de la Musica Tropical Colombiana Volume 3"
  year: 2011
  genre: "Vallenato"
  url: "https://www.youtube.com/watch?v=zV-EzikFrHs"

-
  file: "la-resentida.mp3"
  title: "La Resentida"
  artist: "Rafael Escalona"
  album: "Homenaje a Los Grandes Compositores de la Musica Tropical Colombiana Volume 3"
  year: 2011
  genre: "Vallenato"
  url: "https://www.youtube.com/watch?v=Lf-IhJCR3zs"

-
  file: "el-villanuevero.mp3"
  title: "El Villanuevero"
  artist: "Rafael Escalona"
  album: "Homenaje a Los Grandes Compositores de la Musica Tropical Colombiana Volume 3"
  year: 2011
  genre: "Vallenato"
  url: "https://www.youtube.com/watch?v=s0QaLAxmWtc"

-
  file: "jaime-molina.mp3"
  title: "Jaime Molina"
  artist: "Rafael Escalona"
  album: "Homenaje a Los Grandes Compositores de la Musica Tropical Colombiana Volume 3"
  year: 2011
  genre: "Vallenato"
  url: "https://www.youtube.com/watch?v=WsoPZVvCcts"

-
  file: "la-custodia-de-badillo.mp3"
  title: "La Custodia De Badillo"
  artist: "Rafael Escalona"
  album: "Homenaje a Los Grandes Compositores de la Musica Tropical Colombiana Volume 3"
  year: 2011
  genre: "Vallenato"
  url: "https://www.youtube.com/watch?v=pF4ttFD8lsU"

-
  file: "el-hambre-del-liceo.mp3"
  title: "El Hambre Del Liceo"
  artist: "Rafael Escalona"
  album: "Homenaje a Los Grandes Compositores de la Musica Tropical Colombiana Volume 3"
  year: 2011
  genre: "Vallenato"
  url: "https://www.youtube.com/watch?v=Z44oAPeOvuk"

-
  file: "la-vieja-sara.mp3"
  title: "La Vieja Sara"
  artist: "Rafael Escalona"
  album: "Homenaje a Los Grandes Compositores de la Musica Tropical Colombiana Volume 3"
  year: 2011
  genre: "Vallenato"
  url: "https://www.youtube.com/watch?v=nvMGo072NP0"

-
  file: "honda-herida.mp3"
  title: "Honda Herida"
  artist: "Rafael Escalona"
  album: "Homenaje a Los Grandes Compositores de la Musica Tropical Colombiana Volume 3"
  year: 2011
  genre: "Vallenato"
  url: "https://www.youtube.com/watch?v=MTlY4Q6Fr_0"

-
  file: "el-chevrolito.mp3"
  title: "El Chevrolito"
  artist: "Rafael Escalona"
  album: "Homenaje a Los Grandes Compositores de la Musica Tropical Colombiana Volume 3"
  year: 2011
  genre: "Vallenato"
  url: "https://www.youtube.com/watch?v=fSWRKnTw1DI"

-
  file: "el-general-dangond.mp3"
  title: "El General Dangond"
  artist: "Rafael Escalona"
  album: "Homenaje a Los Grandes Compositores de la Musica Tropical Colombiana Volume 3"
  year: 2011
  genre: "Vallenato"
  url: "https://www.youtube.com/watch?v=OlGRDASMJ0c"

-
  file: "maría-tere.mp3"
  title: "María Tere"
  artist: "Rafael Escalona"
  album: "Homenaje a Los Grandes Compositores de la Musica Tropical Colombiana Volume 3"
  year: 2011
  genre: "Vallenato"
  url: "https://www.youtube.com/watch?v=HHs4hmei5dc"

-
  file: "rosa-maría.mp3"
  title: "Rosa María"
  artist: "Rafael Escalona"
  album: "Homenaje a Los Grandes Compositores de la Musica Tropical Colombiana Volume 3"
  year: 2011
  genre: "Vallenato"
  url: "https://www.youtube.com/watch?v=oSjxaVAVENw"

-
  file: "la-maye.mp3"
  title: "La Maye"
  artist: "Rafael Escalona"
  album: "Homenaje a Los Grandes Compositores de la Musica Tropical Colombiana Volume 3"
  year: 2011
  genre: "Vallenato"
  url: "https://www.youtube.com/watch?v=MFYJNAZWjsU"

-
  file: "el-playonero.mp3"
  title: "El Playonero"
  artist: "Rafael Escalona"
  album: "Homenaje a Los Grandes Compositores de la Musica Tropical Colombiana Volume 3"
  year: 2011
  genre: "Vallenato"
  url: "https://www.youtube.com/watch?v=WxJRM-wFNX8"

-
  file: "el-mejoral.mp3"
  title: "El Mejoral"
  artist: "Rafael Escalona"
  album: "Homenaje a Los Grandes Compositores de la Musica Tropical Colombiana Volume 3"
  year: 2011
  genre: "Vallenato"
  url: "https://www.youtube.com/watch?v=K4EgIEscTFg"

-
  file: "el-creciente-del-cesar.mp3"
  title: "El Creciente Del Cesar"
  artist: "Rafael Escalona"
  album: "Homenaje a Los Grandes Compositores de la Musica Tropical Colombiana Volume 3"
  year: 2011
  genre: "Vallenato"
  url: "https://www.youtube.com/watch?v=Ti3twanFMX0"

