# Topic: https://www.youtube.com/channel/UCZPZSWwcXv7nNEUTx9v8Xnw

-
  file: "cienfuegos.mp3"
  title: "Cienfuegos"
  artist: "Roberto Torres"
  album: "El Rey Del Montuno"
  year: 1991
  genre: "Son montuno"
  url: "https://www.youtube.com/watch?v=1DF7Kwxmqj0"

-
  file: "desde-oriente-al-occidente.mp3"
  title: "Desde Oriente Al Occidente"
  artist: "Roberto Torres"
  album: "Siempre Sonando"
  year: 2000
  genre: "Son montuno"
  url: "https://www.youtube.com/watch?v=tQLMAoljsac"

-
  file: "el-guateque-de-ciprian.mp3"
  title: "El Guateque de Ciprian"
  artist: "Roberto Torres"
  album: "Elegantemente Criollo"
  year: 1986
  genre: "Son montuno"
  url: "https://www.youtube.com/watch?v=_PXhwYkVNIk"

