# List: https://www.youtube.com/playlist?list=OLAK5uy_kMs2A-aqd28I4Wre-YZ9SBs7aDC79u0sI

-
  file: "aqui-hay-un-hombre-gonzando.mp3"
  title: "Aqui Hay Un Hombre Gozando"
  artist: "Charanga De La 4"
  album: "Charanga De La 4"
  year: 2009
  url: "https://www.youtube.com/watch?v=12Z0Qpk5mBY"

-
  file: "tumba-la-caña.mp3"
  title: "Tumba La Caña"
  artist: "Charanga De La 4"
  album: "Charanga De La 4"
  year: 2009
  url: "https://www.youtube.com/watch?v=gXozjH4axlo"

-
  file: "me-gusta-el-son.mp3"
  title: "Me Gusta El Son"
  artist: "Charanga De La 4"
  album: "Charanga De La 4"
  year: 2009
  url: "https://www.youtube.com/watch?v=xmtXcCo55v4"

-
  file: "bilongo.mp3"
  title: "Bilongo"
  artist: "Charanga De La 4"
  album: "Charanga De La 4"
  year: 2009
  url: "https://www.youtube.com/watch?v=RStUnWFhQYs"

-
  file: "consuelate-como-yo.mp3"
  title: "Consuelate Como Yo"
  artist: "Charanga De La 4"
  album: "Charanga De La 4"
  year: 2009
  url: "https://www.youtube.com/watch?v=qlobcP4DP6Q"

-
  file: "seboruco.mp3"
  title: "Seboruco"
  artist: "Charanga De La 4"
  album: "Charanga De La 4"
  year: 2009
  url: "https://www.youtube.com/watch?v=iOXG3x8o8j4"

-
  file: "sabrosona.mp3"
  title: "Sabrosona"
  artist: "Charanga De La 4"
  album: "Charanga De La 4"
  year: 2009
  url: "https://www.youtube.com/watch?v=G1-hU84ekb4"

-
  file: "que-me-digan-feo.mp3"
  title: "Que Me Digan Feo"
  artist: "Charanga De La 4"
  album: "Charanga De La 4"
  year: 2009
  url: "https://www.youtube.com/watch?v=B753irAqG04"
