-
  file: "mi-bendicion.mp3"
  title: "Mi Bendicisn"
  artist: "Juan Luis Guerra"
  album: "A Son de Guerra"
  year: 2010
  
-
  file: "bachata-en-fukuoka.mp3"
  title: "Bachata en Fukuoka"
  artist: "Juan Luis Guerra"
  album: "A Son de Guerra"
  year: 2010
  
-
  file: "muchachita-linda.mp3"
  title: "Muchachita Linda"
  artist: "Juan Luis Guerra"
  album: "Todo Tiene Su Hora"
  year: 2014
  
-
  file: "tus-besos.mp3"
  title: "Tus Besos"
  artist: "Juan Luis Guerra"
  album: "Todo Tiene Su Hora"
  year: 2014
  
-
  file: "la-hormiguita.mp3"
  title: "La Hormiguita"
  artist: "Juan Luis Guerra"
  album: "Ni Es Lo Mismo Ni Es Igual"
  year: 1998
  
-
  file: "si-tu-no-bailas-conmigo.mp3"
  title: "Si Tu No Bailas Conmigo"
  artist: "Juan Luis Guerra"
  album: "La Llave De Mi Corazsn"
  year: 2007

-
  file: "que-me-des-tu-carino.mp3"
  title: "Que Me Des Tu Cariqo"
  artist: "Juan Luis Guerra"
  album: "La Llave De Mi Corazsn"
  year: 2007
  
-
  file: "coronita-de-flores.mp3"
  title: "Coronita De Flores"
  artist: "Juan Luis Guerra"
  album: "Aremto"
  year: 1992
  
-
  file: "estrellitas-y-duendes.mp3"
  title: "Estrellitas y Duendes"
  artist: "Juan Luis Guerra"
  album: "Bachata Rosa"
  year: 1990
  
-
  file: "palomita-blanca.mp3"
  title: "Palomita Blanca"
  artist: "Juan Luis Guerra"
  album: "Ni Es lo Mismo Ni Es Igual"
  year: 1998
  
-
  file: "bachata-rosa.mp3"
  title: "Bachata Rosa"
  artist: "Juan Luis Guerra"
  album: "Bachata Rosa"
  year: 1990
  
-
  file: "ojala-que-llueva-cafe.mp3"
  title: "Ojala Que Llueva Cafe"
  artist: "Juan Luis Guerra"
  album: "Ojala Que Llueva Cafe"
  year: 1989
  
