# Topic: https://www.youtube.com/channel/UCa9TVFrpF_fyLofhw527qOw

-
  file: "rumbatimba.mp3"
  title: "Rumbatimba"
  artist: "Mario Crespo Martinez"
  album: "Siguiendo el Flow"
  year: 2015
  genre: "Timba"
  url: "https://www.youtube.com/watch?v=E22_-Fr7ZOQ"

-
  file: "kamasutra.mp3"
  title: "Kamasutra"
  artist: "Mario Crespo Martinez"
  album: "Siguiendo el Flow"
  year: 2015
  genre: "Timba"
  url: "https://www.youtube.com/watch?v=lOEr7A1YImY"

-
  file: "nena.mp3"
  title: "Nena"
  artist: "Mario Crespo Martinez"
  album: "Siguiendo el Flow"
  year: 2015
  genre: "Timba"
  url: "https://www.youtube.com/watch?v=VxAalfOSZQA"

-
  file: "pa-los-rumberos.mp3"
  title: "Pa Los Rumberos"
  artist: "Mario Crespo Martinez"
  album: "Siguiendo el Flow"
  year: 2015
  genre: "Timba"
  url: "https://www.youtube.com/watch?v=AaGilpzs_U0"

-
  file: "sonero.mp3"
  title: "Sonero"
  artist: "Mario Crespo Martinez"
  album: "Siguiendo el Flow"
  year: 2015
  genre: "Timba"
  url: "https://www.youtube.com/watch?v=Z9zYoWb5OWc"

-
  file: "amor-y-belleza.mp3"
  title: "Amor y Belleza"
  artist: "Mario Crespo Martinez"
  album: "Siguiendo el Flow"
  year: 2015
  genre: "Timba"
  url: "https://www.youtube.com/watch?v=2yxajYe-nCM"

-
  file: "dale-ven.mp3"
  title: "Dale Ven"
  artist: "Mario Crespo Martinez"
  album: "En Resumidas Cuentas"
  year: 2011
  genre: "Timba"
  url: "https://www.youtube.com/watch?v=BdQMtOHamy4"

