# Topic: https://www.youtube.com/channel/UCuZfXCptrKdJEtTdiKdQpgA

-
  file: "gózalo.mp3"
  title: "Gózalo"
  artist: "Niño Torrente and Son de Hoy"
  album: "Niño Torrente and Son de Hoy"
  year: 2003
  genre: "Son montuno"
  url: "https://www.youtube.com/watch?v=ySKBDsQxG2s"

-
  file: "bongocero.mp3"
  title: "Bongocero"
  artist: "Niño Torrente and Son de Hoy"
  album: "Niño Torrente and Son de Hoy"
  year: 2003
  genre: "Son montuno"
  url: "https://www.youtube.com/watch?v=occWFLtqDJM"

-
  file: "lo-tengo-pa-tí.mp3"
  title: "Lo Tengo Pa' Tí"
  artist: "Niño Torrente and Son de Hoy"
  album: "Niño Torrente and Son de Hoy"
  year: 2003
  genre: "Son montuno"
  url: "https://www.youtube.com/watch?v=ZhOiz9x-hDw"

-
  file: "te-sentí.mp3"
  title: "Te Sentí"
  artist: "Niño Torrente and Son de Hoy"
  album: "Niño Torrente and Son de Hoy"
  year: 2003
  genre: "Son montuno"
  url: "https://www.youtube.com/watch?v=R5Dv7ybWZZw"

-
  file: "el-son-te-llama.mp3"
  title: "El Son Te Llama"
  artist: "Niño Torrente and Son de Hoy"
  album: "Niño Torrente and Son de Hoy"
  year: 2003
  genre: "Son montuno"
  url: "https://www.youtube.com/watch?v=Q9ahwxgjzPs"

-
  file: "murió-valera.mp3"
  title: "Murió Valera"
  artist: "Niño Torrente and Son de Hoy"
  album: "Niño Torrente and Son de Hoy"
  year: 2003
  genre: "Son montuno"
  url: "https://www.youtube.com/watch?v=5oVmYFNCWQU"

-
  file: "compasión.mp3"
  title: "Compasión"
  artist: "Niño Torrente and Son de Hoy"
  album: "Niño Torrente and Son de Hoy"
  year: 2003
  genre: "Son montuno"
  url: "https://www.youtube.com/watch?v=pIVxxGh3lWA"

-
  file: "en-mi-jardín.mp3"
  title: "En Mi Jardín"
  artist: "Niño Torrente and Son de Hoy"
  album: "Niño Torrente and Son de Hoy"
  year: 2003
  genre: "Son montuno"
  url: "https://www.youtube.com/watch?v=U1m4GCwyL5U"

-
  file: "bem-bele.mp3"
  title: "Bem Bele"
  artist: "Niño Torrente and Son de Hoy"
  album: "Bem Bele"
  year: 2023
  genre: "Son montuno"
  url: "https://www.youtube.com/watch?v=-14mpMg-apY"

-
  file: "ana-la-tumba.mp3"
  title: "Ana La Tumba"
  artist: "Niño Torrente and Son de Hoy"
  album: "Ana La Tumba"
  year: 2023
  genre: "Son montuno"
  url: "https://www.youtube.com/watch?v=J0UnMbje5WQ"

-
  file: "te-haré-feliz.mp3"
  title: "Te Haré Feliz"
  artist: "Niño Torrente and Son de Hoy"
  album: "Niño Torrente and Son de Hoy, Ahora!"
  year: 2016
  genre: "Son montuno"
  url: "https://www.youtube.com/watch?v=IESHtH_Kzno"

-
  file: "consagración.mp3"
  title: "Consagración"
  artist: "Niño Torrente and Son de Hoy"
  album: "Niño Torrente and Son de Hoy, Ahora!"
  year: 2016
  genre: "Son montuno"
  url: "https://www.youtube.com/watch?v=ZjuO7CDVXyI"

