# Topic: https://www.youtube.com/channel/UC07816eqR-Qwf5AJJqfqibg

-
  file: "mi-havana.mp3"
  title: "Mi Havana"
  artist: "Pablo Timba"
  album: "Llegó Timbacalle"
  year: 2016
  genre: "Timba"
  url: "https://www.youtube.com/watch?v=OzAzW6y_XAQ"

-
  file: "mi-timba.mp3"
  title: "Mi Timba"
  artist: "Pablo Timba"
  album: "Llegó Timbacalle"
  year: 2016
  genre: "Timba"
  url: "https://www.youtube.com/watch?v=X3YZGcC_sJk"

