# List: https://www.youtube.com/playlist?list=OLAK5uy_n2nFJP95k5thFZVSVJ1uUlnguHHVu_XbQ

-
  file: "la-pragua.mp3"
  title: "La Pragua"
  artist: "José Barros"
  album: "Homenaje a Los Grandes Compositores de la Musica Tropical Colombiana Volume 2"
  year: 2011
  url: "https://www.youtube.com/watch?v=bLzdNxqR8HQ"

-
  file: "la-pava.mp3"
  title: "La Pava"
  artist: "José Barros"
  album: "Homenaje a Los Grandes Compositores de la Musica Tropical Colombiana Volume 2"
  year: 2011
  url: "https://www.youtube.com/watch?v=ODxKqC951uo"

-
  file: "las-pilanderas.mp3"
  title: "Las Pilanderas"
  artist: "José Barros"
  album: "Homenaje a Los Grandes Compositores de la Musica Tropical Colombiana Volume 2"
  year: 2011
  url: "https://www.youtube.com/watch?v=HnNvNYBQG70"

-
  file: "el-vaquero.mp3"
  title: "El Vaquero"
  artist: "José Barros"
  album: "Homenaje a Los Grandes Compositores de la Musica Tropical Colombiana Volume 2"
  year: 2011
  url: "https://www.youtube.com/watch?v=UY1bRKtz7S8"

-
  file: "navidad-negra.mp3"
  title: "Navidad Negra"
  artist: "José Barros"
  album: "Homenaje a Los Grandes Compositores de la Musica Tropical Colombiana Volume 2"
  year: 2011
  url: "https://www.youtube.com/watch?v=9eJwCLcHlOI"

-
  file: "momposina.mp3"
  title: "Momposina"
  artist: "José Barros"
  album: "Homenaje a Los Grandes Compositores de la Musica Tropical Colombiana Volume 2"
  year: 2011
  url: "https://www.youtube.com/watch?v=7cS1Fhf3Jho"

-
  file: "la-llorona-loca.mp3"
  title: "La Llorona Loca"
  artist: "José Barros"
  album: "Homenaje a Los Grandes Compositores de la Musica Tropical Colombiana Volume 2"
  year: 2011
  url: "https://www.youtube.com/watch?v=FdN1H_4pVnw"

-
  file: "plamira-señorial.mp3"
  title: "Plamira Señorial"
  artist: "José Barros"
  album: "Homenaje a Los Grandes Compositores de la Musica Tropical Colombiana Volume 2"
  year: 2011
  url: "https://www.youtube.com/watch?v=V_IHL8YJ8dQ"

-
  file: "arbolito-de-navidad.mp3"
  title: "Arbolito De Navidad"
  artist: "José Barros"
  album: "Homenaje a Los Grandes Compositores de la Musica Tropical Colombiana Volume 2"
  year: 2011
  url: "https://www.youtube.com/watch?v=E_N7Esr4L-o"

-
  file: "el-muñeco-de-la-ciudad.mp3"
  title: "El Muñeco De La Ciudad"
  artist: "José Barros"
  album: "Homenaje a Los Grandes Compositores de la Musica Tropical Colombiana Volume 2"
  year: 2011
  url: "https://www.youtube.com/watch?v=3NIjjZ_-ADQ"

-
  file: "el-gallo-tuerto.mp3"
  title: "El Gallo Tuerto"
  artist: "José Barros"
  album: "Homenaje a Los Grandes Compositores de la Musica Tropical Colombiana Volume 2"
  year: 2011
  url: "https://www.youtube.com/watch?v=Q5T1eJxjbE0"

-
  file: "el-guere-guere.mp3"
  title: "El Guere Guere"
  artist: "José Barros"
  album: "Homenaje a Los Grandes Compositores de la Musica Tropical Colombiana Volume 2"
  year: 2011
  url: "https://www.youtube.com/watch?v=EeHgWBrtfBk"

-
  file: "nube-negra.mp3"
  title: "Nube Negra"
  artist: "José Barros"
  album: "Homenaje a Los Grandes Compositores de la Musica Tropical Colombiana Volume 2"
  year: 2011
  url: "https://www.youtube.com/watch?v=Z4d-AZ1RfuQ"

