# Topic: https://www.youtube.com/channel/UCRkQi8U5YaNFIrIHV8fUEOA
# Topic: https://www.youtube.com/channel/UCM3RMNkOsTzWwxmS6ScK-nA

-
  file: "no-estoy-pa-eso.mp3"
  title: "No Estoy Pa' Eso"
  artist: "René Alvarez y Su Cuban Combination"
  album: "Abriendo los Caminos"
  year: 2017
  genre: "Timba"
  url: "https://www.youtube.com/watch?v=Jz69NfF9eWo"

-
  file: "camina-como-yo.mp3"
  title: "Camina Como Yo"
  artist: "René Alvarez y Su Cuban Combination"
  album: "Abriendo los Caminos"
  year: 2017
  genre: "Son montuno"
  url: "https://www.youtube.com/watch?v=GXuKBBzm_PU"

-
  file: "dicen-por-ahí.mp3"
  title: "Dicen Por Ahí"
  artist: "René Alvarez y Su Cuban Combination"
  album: "Abriendo los Caminos"
  year: 2017
  genre: "Timba"
  url: "https://www.youtube.com/watch?v=nAY_-2dy5h0"

-
  file: "ese-soy-yo.mp3"
  title: "Ese Soy Yo"
  artist: "René Alvarez y Su Cuban Combination"
  album: "Abriendo los Caminos"
  year: 2017
  genre: "Timba"
  url: "https://www.youtube.com/watch?v=fmoDv-N2RtM"

-
  file: "timberos-y-salseros.mp3"
  title: "Timberos Y Salseros"
  artist: "René Alvarez y Su Cuban Combination"
  album: "Abriendo los Caminos"
  year: 2017
  genre: "Timba"
  url: "https://www.youtube.com/watch?v=t-QJLHD8oV0"

-
  file: "buscando-un-tambo.mp3"
  title: "Buscando Un Tambo"
  artist: "René Alvarez y Su Cuban Combination"
  album: "Buscando Un Tambo"
  year: 2020
  genre: "Timba"
  featured_artist: "Fredy Clan"
  url: "https://www.youtube.com/watch?v=z2FsBLIApRc"

-
  file: "son-pa-caridad.mp3"
  title: "Son Pa' Caridad"
  artist: "René Alvarez y Su Cuban Combination"
  album: "Son Pa' Caridad"
  year: 2021
  genre: "Timba"
  url: "https://www.youtube.com/watch?v=m8-zxEIlrGs"

-
  file: "pa-la-cubana.mp3"
  title: "Pa' La Cubana"
  artist: "Rene Alvarez y Su Cuban Combination"
  album: "Ya Eres Grande"
  year: 2012
  genre: "Timba"
  url: "https://www.youtube.com/watch?v=mkpfsHTbl7A"

