-
  file: "se-le-ve.mp3"
  title: "Se Le Ve"
  artist: "Batacumbele"
  album: "Con Un Poco De Songo"
  year: 1981
  genre: "Salsa"
  
-
  file: "a-la-i-ole.mp3"
  title: "A La I Ole"
  artist: "Batacumbele"
  album: "Con Un Poco De Songo"
  year: 1981
  genre: "Salsa"
  
-
  file: "batacumbele.mp3"
  title: "Batacumbele"
  artist: "Batacumbele"
  album: "Con Un Poco De Songo"
  year: 1981
  genre: "Salsa"
  
-
  file: "en-aquellos-tiempos.mp3"
  title: "En Aquellos Tiempos"
  artist: "Batacumbele"
  album: "En Aquellos Tiempos"
  year: 1983
  genre: "Salsa"
  
-
  file: "dame-un-traguito.mp3"
  title: "Dame Un Traguito"
  artist: "Batacumbele"
  album: "En Aquellos Tiempos"
  year: 1983
  genre: "Salsa"
  
-
  file: "el-mas-chevere.mp3"
  title: "El Mas Chevere"
  artist: "Batacumbele"
  album: "En Aquellos Tiempos"
  year: 1983
  genre: "Salsa"
  
-
  file: "la-piye.mp3"
  title: "La Piye"
  artist: "Batacumbele"
  album: "Con Un Poco De Songo"
  year: 1981
  genre: "Salsa"
  
-
  file: "batarengue.mp3"
  title: "Batarengue"
  artist: "Batacumbele"
  album: "En Aquellos Tiempos"
  year: 1983
  genre: "Salsa"
  
-
  file: "bailala.mp3"
  title: "Bailala"
  artist: "Batacumbele"
  album: "En Aquellos Tiempos"
  year: 1983
  genre: "Salsa"
