-
  file: "se-le-ve.mp3"
  title: "Se Le Ve"
  artist: "Batacumbele"
  album: "Con Un Poco De Songo"
  year: 1981
  genre: "Salsa"
  url: "https://www.youtube.com/watch?v=2Qdfx9K1jq8"
  
-
  file: "a-la-i-ole.mp3"
  title: "A La I Ole"
  artist: "Batacumbele"
  album: "Con Un Poco De Songo"
  year: 1981
  genre: "Salsa"
  url: "https://www.youtube.com/watch?v=lvIxyO6pqwg"
  
-
  file: "batacumbele.mp3"
  title: "Batacumbele"
  artist: "Batacumbele"
  album: "Con Un Poco De Songo"
  year: 1981
  genre: "Salsa"
  url: "https://www.youtube.com/watch?v=7rzhGIfC0fw"
  
-
  file: "en-aquellos-tiempos.mp3"
  title: "En Aquellos Tiempos"
  artist: "Batacumbele"
  album: "En Aquellos Tiempos"
  year: 1983
  genre: "Salsa"
  url: "https://www.youtube.com/watch?v=EYvGlVtCc0k"
  
-
  file: "dame-un-traguito.mp3"
  title: "Dame Un Traguito"
  artist: "Batacumbele"
  album: "En Aquellos Tiempos"
  year: 1983
  genre: "Salsa"
  url: "https://www.youtube.com/watch?v=NqqNjAEMsaM"
  
-
  file: "el-mas-chévere.mp3"
  title: "El Ma' Chévere"
  artist: "Batacumbele"
  album: "En Aquellos Tiempos"
  year: 1983
  genre: "Salsa"
  url: "https://www.youtube.com/watch?v=ik3ZRliTLLo"
  
-
  file: "la-piyé.mp3"
  title: "La Piyé"
  artist: "Batacumbele"
  album: "Con Un Poco De Songo"
  year: 1981
  genre: "Salsa"
  url: "https://www.youtube.com/watch?v=ZLwp1FEiIPI"
  
-
  file: "batarengue.mp3"
  title: "Batarengue"
  artist: "Batacumbele"
  album: "En Aquellos Tiempos"
  year: 1983
  genre: "Salsa"
  url: "https://www.youtube.com/watch?v=SscnMGbA-Yk"
  
-
  file: "bailala.mp3"
  title: "Bailala"
  artist: "Batacumbele"
  album: "En Aquellos Tiempos"
  year: 1983
  genre: "Salsa"
  url: "https://www.youtube.com/watch?v=EnIR78lvTdU"
