# Topic: https://www.youtube.com/channel/UCjUpTJ06apcNOjQDaDAVVfw (El Mola)
# Topic: https://www.youtube.com/channel/UCPhmkScCZtTEMXObWUg9CkA (M.O.L.A)
-
  file: "preguntando-por-ti.mp3"
  title: "Preguntando Por Ti"
  artist: El Mola
  album: The Arrival
  year: 2015
  genre: "Timbaton"
  url: "https://www.youtube.com/watch?v=3QsKqXk8wa8"

-
  file: "como-tú-te-pones.mp3"
  title: "Como Tú Te Pones"
  artist: El Mola
  album: The Arrival
  year: 2015
  genre: "Timbaton"
  url: "https://www.youtube.com/watch?v=DZ-2kUPgI68"

-
  file: "lo-que-me-pidas.mp3"
  title: "Lo Que Me Pidas"
  artist: El Mola
  album: The Arrival
  year: 2015
  genre: "Timbaton"
  url: "https://www.youtube.com/watch?v=of85KFc4C2E"

-
  file: "lloran2.mp3"
  title: "Lloran2"
  artist: El Mola
  album: The Arrival
  year: 2015
  genre: "Timbaton"
  url: "https://www.youtube.com/watch?v=HnxlFCeXfvA"

-
  file: "te-lo-voy-a-dar.mp3"
  title: "Te Lo Voy a Dar"
  artist: El Mola
  album: The Arrival
  year: 2015
  genre: "Timbaton"
  url: "https://www.youtube.com/watch?v=qR-TTDeaeiY"

-
  file: "pa-llá.mp3"
  title: "Pa' Llá"
  artist: El Mola
  album: The Arrival
  year: 2015
  genre: "Timbaton"
  url: "https://www.youtube.com/watch?v=ZpzATo6CL08"

-
  file: "la-letra-conflictiva.mp3"
  title: "La Letra Conflictiva"
  artist: El Mola
  album: The Arrival
  year: 2015
  genre: "Timbaton"
  url: "https://www.youtube.com/watch?v=g45fIEDmHuQ"

-
  file: "el-tipo-llegó.mp3"
  title: "El Tipo Llegó"
  artist: El Mola
  album: The Arrival
  year: 2015
  genre: "Timbaton"
  url: "https://www.youtube.com/watch?v=MaTc0P1eChE"

-
  file: "peligrosa.mp3"
  title: "Peligrosa"
  artist: El Mola
  album: The Arrival
  year: 2015
  genre: "Timbaton"
  url: "https://www.youtube.com/watch?v=hqxgm4Hp6ug"

-
  file: "véndeme-eso.mp3"
  title: "Véndeme Eso"
  artist: El Mola
  album: The Arrival
  year: 2015
  genre: "Timbaton"
  url: "https://www.youtube.com/watch?v=aspE3Tu-yXc"

