# Topic: https://www.youtube.com/@CHOCQUIBTOWNLIVE/releases

-
  file: "de-donde-vengo-yo.mp3"
  title: "De Donde Vengo Yo"
  artist: "ChocQuibTown"
  album: "Oro"
  year: 2010
  url: "https://www.youtube.com/watch?v=QPcOACgd-ak"

-
  file: "el-mismo.mp3"
  title: "El Mismo"
  artist: "ChocQuibTown"
  album: "El Mismo"
  year: 2015
  url: "https://www.youtube.com/watch?v=Gv0SruQxvn4"

-
  file: "san-antonio.mp3"
  title: "San Antonio"
  artist: "ChocQuibTown"
  album: "Oro"
  year: 2010
  url: "https://www.youtube.com/watch?v=5Ybb03zJHAY"

-
  file: "son-bereju.mp3"
  title: "Son Bereju"
  artist: "ChocQuibTown"
  album: "Oro"
  year: 2010
  url: "https://www.youtube.com/watch?v=rEw_ppp7f84"

-
  file: "somos-pacifico.mp3"
  title: "Somos Pacifico"
  artist: "ChocQuibTown"
  album: "Oro"
  year: 2010
  url: "https://www.youtube.com/watch?v=e7peNBUxT8s"

-
  file: "mi-musica.mp3"
  title: "Mi Musica"
  artist: "ChocQuibTown"
  album: "Oro"
  year: 2010
  url: "https://www.youtube.com/watch?v=t5rYoyuiXZo"

-
  file: "macru.mp3"
  title: "Macru"
  artist: "ChocQuibTown"
  album: "Oro"
  year: 2010
  url: "https://www.youtube.com/watch?v=FEEgPZOYspE"

-
  file: "prietos.mp3"
  title: "Prietos"
  artist: "ChocQuibTown"
  album: "Oro"
  year: 2010
  url: "https://www.youtube.com/watch?v=BbN58qOCxq0"

-
  file: "el-arriendo.mp3"
  title: "El Arriendo"
  artist: "ChocQuibTown"
  album: "El Mismo"
  year: 2015
  url: "https://www.youtube.com/watch?v=Qqn4Z3_eWbA"

-
  file: "pescao-envenenao.mp3"
  title: "Pescao Envenenao"
  artist: "ChocQuibTown"
  album: "Oro"
  year: 2010
  url: "https://www.youtube.com/watch?v=WI_bn6lv9Jg"

-
  file: "nuqui.mp3"
  title: "Nuqui"
  artist: "ChocQuibTown"
  album: "El Mismo"
  year: 2015
  url: "https://www.youtube.com/watch?v=L_XFQUG_vQQ"

