-
  file: "dprimera.mp3"
  title: "#Dprimera"
  artist: "Havana D'Primera"
  album: "Cantor Del Pueblo"
  year: 2018
  genre: "Timba"
  url: "https://www.youtube.com/watch?v=_Y2hhGOR3uY"

-
  file: "tres-días.mp3"
  title: "Tres Días"
  artist: "Havana D'Primera"
  album: "Cantor Del Pueblo"
  year: 2018
  genre: "Timba"
  url: "https://www.youtube.com/watch?v=eYaUwMwkHkg"

-
  file: "la-mujer-piropo.mp3"
  title: "La Mujer Piropo"
  artist: "Havana D'Primera"
  album: "Cantor Del Pueblo"
  year: 2018
  genre: "Timba"
  url: "https://www.youtube.com/watch?v=lhj66Wql1Sc"

-
  file: "cantor-del-pueblo.mp3"
  title: "Cantor Del Pueblo"
  artist: "Havana D'Primera"
  album: "Cantor Del Pueblo"
  year: 2018
  genre: "Timba"
  url: "https://www.youtube.com/watch?v=rdDCzE3vBX4"

-
  file: "manantiales.mp3"
  title: "Manantiales"
  artist: "Havana D'Primera"
  album: "Cantor Del Pueblo"
  year: 2018
  genre: "Timba"
  url: "https://www.youtube.com/watch?v=9SgCZ0NAP9o"

-
  file: "mujeriego.mp3"
  title: "Mujeriego"
  artist: "Havana D'Primera"
  album: "Cantor Del Pueblo"
  year: 2018
  genre: "Timba"
  url: "https://www.youtube.com/watch?v=usvS8-fWZDo"

-
  file: "habana-mia.mp3"
  title: "Habana Mia"
  artist: "Havana D'Primera"
  album: "Cantor Del Pueblo"
  year: 2018
  genre: "Timba"
  url: "https://www.youtube.com/watch?v=DvHjBZ7aLbE"

-
  file: "pastilla-de-menta.mp3"
  title: "Pastilla De Menta"
  artist: "Havana D'Primera"
  album: "Cantor Del Pueblo"
  year: 2018
  genre: "Timba"
  url: "https://www.youtube.com/watch?v=qIKFAGHRQhc"

-
  file: "lamento-yoruba.mp3"
  title: "Lamento Yoruba"
  artist: "Havana D'Primera"
  album: "Cantor Del Pueblo"
  year: 2018
  genre: "Timba"
  url: "https://www.youtube.com/watch?v=3HMOOL5kvp0"

