-
  file: "de-donde-vengo-yo.opus"
  title: "De Donde Vengo Yo"
  artist: "ChocQuibTown"
  album: "Oro"
  year: 2010
  link: "https://www.youtube.com/watch?v=yMS4J6Gp6e4"

-
  file: "el-mismo.opus"
  title: "El Mismo"
  artist: "ChocQuibTown"
  album: "El Mismo"
  year: 2015
  link: "https://www.youtube.com/watch?v=Gv0SruQxvn4"

-
  file: "san-antonio.opus"
  title: "San Antonio"
  artist: "ChocQuibTown"
  album: "Oro"
  year: 2010
  link: "https://www.youtube.com/watch?v=5Ybb03zJHAY"

-
  file: "son-bereju.opus"
  title: "Son Bereju"
  artist: "ChocQuibTown"
  album: "Oro"
  year: 2010
  link: "https://www.youtube.com/watch?v=rEw_ppp7f84"

-
  file: "somos-pacificos.opus"
  title: "Somos Pacificos"
  artist: "ChocQuibTown"
  album: "Oro"
  year: 2010
  link: "https://www.youtube.com/watch?v=e7peNBUxT8s"

-
  file: "mi-musica.opus"
  title: "Mi Musica"
  artist: "ChocQuibTown"
  album: "Oro"
  year: 2010
  link: "https://www.youtube.com/watch?v=t5rYoyuiXZo"

-
  file: "macru.opus"
  title: "Macru"
  artist: "ChocQuibTown"
  album: "Oro"
  year: 2010
  link: "https://www.youtube.com/watch?v=FEEgPZOYspE"

-
  file: "prietos.opus"
  title: "Prietos"
  artist: "ChocQuibTown"
  album: "Oro"
  year: 2010
  link: "https://www.youtube.com/watch?v=BbN58qOCxq0"

-
  file: "el-arriendo.opus"
  title: "El Arriendo"
  artist: "ChocQuibTown"
  album: "El Mismo"
  year: 2015
  link: "https://www.youtube.com/watch?v=Qqn4Z3_eWbA"

-
  file: "pescao-envenenao.opus"
  title: "Pescao Envenenao"
  artist: "ChocQuibTown"
  album: "Oro"
  year: 2010
  link: "https://www.youtube.com/watch?v=WI_bn6lv9Jg"

-
  file: "nuqui.opus"
  title: "Nuqui"
  artist: "ChocQuibTown"
  album: "El Mismo"
  year: 2015
  link: "https://www.youtube.com/watch?v=L_XFQUG_vQQ"
