# Topic: https://www.youtube.com/channel/UCgmGtGBDfR_3OqBE9NAk-ag

-
  file: "changani.mp3"
  title: "Changani"
  artist: "Barbaro Fines y su Mayimbe"
  album: "Mensajeros de Dios"
  year: 2013
  genre: "Timba"
  url: "https://www.youtube.com/watch?v=ZR7SuR-GGTM"

-
  file: "el-animal.mp3"
  title: "El Animal"
  artist: "Barbaro Fines y su Mayimbe"
  album: "Mensajeros de Dios"
  year: 2013
  genre: "Timba"
  url: "https://www.youtube.com/watch?v=l8VQQycv-XE"

-
  file: "el-diablo.mp3"
  title: "El Diablo"
  artist: "Barbaro Fines y su Mayimbe"
  album: "De La Habana a Perú"
  year: 2011
  genre: "Timba"
  url: "https://www.youtube.com/watch?v=GIxI9kzatCM"

-
  file: "el-paquete.mp3"
  title: "El Paquete"
  artist: "Barbaro Fines y su Mayimbe"
  album: "Mensajeros de Dios"
  year: 2013
  genre: "Timba"
  url: "https://www.youtube.com/watch?v=HEATAi7XGHE"

-
  file: "el-tren-bala.mp3"
  title: "El Tren Bala"
  artist: "Barbaro Fines y su Mayimbe"
  album: "De La Habana a Perú"
  year: 2011
  genre: "Timba"
  url: "https://www.youtube.com/watch?v=tp2zjDndUiA"

-
  file: "el-uno-ahora.mp3"
  title: "El Uno Ahora"
  artist: "Barbaro Fines y su Mayimbe"
  album: "Mensajeros de Dios"
  year: 2013
  genre: "Timba"
  url: "https://www.youtube.com/watch?v=CLcuct3q1CA"

-
  file: "la-bendicion.mp3"
  title: "La Bendicion"
  artist: "Barbaro Fines y su Mayimbe"
  album: "Mensajeros de Dios"
  year: 2013
  genre: "Timba"
  url: "https://www.youtube.com/watch?v=8lVihIcqdfM"

-
  file: "intro-del-mayimbe.mp3"
  title: "Intro Del Mayimbe"
  artist: "Barbaro Fines y su Mayimbe"
  album: "De La Habana a Perú"
  year: 2011
  genre: "Timba"
  url: "https://www.youtube.com/watch?v=VWjWPbOXqws"

-
  file: "la-chica-chocolate.mp3"
  title: "La Chica Chocolate"
  artist: "Barbaro Fines y su Mayimbe"
  album: "Mensajeros de Dios"
  year: 2013
  genre: "Timba"
  url: "https://www.youtube.com/watch?v=9LtW_9E1Pe0"

-
  file: "miel-y-canela.mp3"
  title: "Miel Y Canela"
  artist: "Barbaro Fines y su Mayimbe"
  album: "Te Vi Nacer"
  year: 2016
  genre: "Timba"
  url: "https://www.youtube.com/watch?v=IVj58dCcojs"

