# Topic: https://www.youtube.com/@carlosvives/releases

-
  file: "pa-mayte.mp3"
  title: "Pa' Mayte"
  artist: "Carlos Vives"
  album: "La Tierra Del Olvido"
  year: 1995
  url: "https://www.youtube.com/watch?v=ANzuVrjx3Nc"

-
  file: "la-hamaca-grande.mp3"
  title: "La Hamaca Grande"
  artist: "Carlos Vives"
  album: "Clasicos De La Provincia"
  year: 1993
  url: "https://www.youtube.com/watch?v=fR9RYHqCH5c"

-
  file: "el-cante.mp3"
  title: "El Cante"
  artist: "Carlos Vives"
  album: "El Amor De Mi Tierra"
  year: 1999
  url: "https://www.youtube.com/watch?v=h2zV_2gBEGM"

-
  file: "la-gota-fria.mp3"
  title: "La Gota Fria"
  artist: "Carlos Vives"
  album: "Clasicos De La Provincia"
  year: 1993
  url: "https://www.youtube.com/watch?v=cMn3ortVBeE"

-
  file: "la-celosa.mp3"
  title: "La Celosa"
  artist: "Carlos Vives"
  album: "Clasicos De La Provincia"
  year: 1993
  url: "https://www.youtube.com/watch?v=p8rw1Bq0rXs"

-
  file: "la-tijera.mp3"
  title: "La Tijera"
  artist: "Carlos Vives"
  album: "Clasicos De La Provincia"
  year: 1993
  url: "https://www.youtube.com/watch?v=8VKmuZDF2vY"

-
  file: "la-puya-puya.mp3"
  title: "La Puya Puya"
  artist: "Carlos Vives"
  album: "La Tierra Del Olvido"
  year: 1995
  url: "https://www.youtube.com/watch?v=6k_M-uxenB4"

-
  file: "la-parrandita.mp3"
  title: "La Parrandita"
  artist: "Carlos Vives"
  album: "Clasicos De La Provincia II"
  year: 2009
  url: "https://www.youtube.com/watch?v=TMv2myi0NJM"

-
  file: "el-cantor-de-fonseca.mp3"
  title: "El Cantor De Fonseca"
  artist: "Carlos Vives"
  album: "Clasicos De La Provincia"
  year: 1993
  url: "https://www.youtube.com/watch?v=bjP8CQFG5uM"

-
  file: "compae-chipuco.mp3"
  title: "Compa'e Chipuco"
  artist: "Carlos Vives"
  album: "Clasicos De La Provincia"
  year: 1993
  url: "https://www.youtube.com/watch?v=8vC8uVnpxLM"

-
  file: "volver-al-valle.mp3"
  title: "Volver Al Valle"
  artist: "Carlos Vives"
  album: "El Amor De Mi Tierra"
  year: 1999
  url: "https://www.youtube.com/watch?v=cNTYTkr6nTE"

-
  file: "la-mona.mp3"
  title: "La Mona"
  artist: "Carlos Vives"
  album: "El Amor De Mi Tierra"
  year: 1999
  url: "https://www.youtube.com/watch?v=fWcgRJvGfDg"

-
  file: "el-amor-de-mi-tierra.mp3"
  title: "El Amor De Mi Tierra"
  artist: "Carlos Vives"
  album: "El Amor De Mi Tierra"
  year: 1999
  url: "https://www.youtube.com/watch?v=u66oTr-3HvI"

-
  file: "fidelina.mp3"
  title: "Fidelina"
  album: "La Tierra Del Olvido"
  artist: "Carlos Vives"
  year: 1995
  url: "https://www.youtube.com/watch?v=A1R0dRSS73s"

-
  file: "amor-sensible.mp3"
  title: "Amor Sensible"
  artist: "Carlos Vives"
  album: "Clasicos De La Provincia"
  year: 1993
  url: "https://www.youtube.com/watch?v=SgdByk9A0j0"

-
  file: "la-casa-en-el-aire.mp3"
  title: "La Casa En El Aire"
  artist: "Carlos Vives"
  album: "Escalona: Vol. 2"
  year: 1992
  url: "https://www.youtube.com/watch?v=Z-LmIDAEm9Q"

