# Topic: https://www.youtube.com/channel/UCSYKP8YH0vLx9l9Fw4m2W7w

-
  file: "las-melodias.mp3"
  title: "Las Melodias"
  artist: "Gnonnas Pedro"
  album: "La belle époque: 1965 - 1975, Vol.1"
  year: 2011
  url: "https://www.youtube.com/watch?v=E2EU9F75eTo"

-
  file: "yo-prefiero-el-son.mp3"
  title: "Yo Prefiero El Son"
  artist: "Gnonnas Pedro"
  album: "La belle époque: 1965 - 1975, Vol.1"
  year: 2011
  url: "https://www.youtube.com/watch?v=Q5OZukZudLE"

-
  file: "gan-gbabliba.mp3"
  title: "Gan Gbabliba"
  artist: "Gnonnas Pedro"
  album: "La belle époque: 1965 - 1975, Vol.1"
  year: 2011
  url: "https://www.youtube.com/watch?v=phiFQbLHAEQ"

-
  file: "oumako.mp3"
  title: "Oumako"
  artist: "Gnonnas Pedro"
  album: "La belle époque: 1965 - 1975, Vol.1"
  year: 2011
  url: "https://www.youtube.com/watch?v=zZTW6MV8LfM"

-
  file: "feso-yaye.mp3"
  title: "Feso Yaye"
  artist: "Gnonnas Pedro"
  album: "La belle époque: 1965 - 1975, Vol.1"
  year: 2011
  url: "https://www.youtube.com/watch?v=RgXqjIlZtkE"

-
  file: "las-melodias.mp3"
  title: "Las Melodias"
  artist: "Gnonnas Pedro"
  album: "La belle époque: 1965 - 1975, Vol.1"
  year: 2011
  url: "https://www.youtube.com/watch?v=E2EU9F75eTo"

-
  file: "yo-prefiero-el-son.mp3"
  title: "Yo Prefiero El Son"
  artist: "Gnonnas Pedro"
  album: "La belle époque: 1965 - 1975, Vol.1"
  year: 2011
  url: "https://www.youtube.com/watch?v=Q5OZukZudLE"

-
  file: "gan-gbabliba.mp3"
  title: "Gan Gbabliba"
  artist: "Gnonnas Pedro"
  album: "La belle époque: 1965 - 1975, Vol.1"
  year: 2011
  url: "https://www.youtube.com/watch?v=phiFQbLHAEQ"

-
  file: "oumako.mp3"
  title: "Oumako"
  artist: "Gnonnas Pedro"
  album: "La belle époque: 1965 - 1975, Vol.1"
  year: 2011
  url: "https://www.youtube.com/watch?v=zZTW6MV8LfM"

-
  file: "feso-yaye.mp3"
  title: "Feso Yaye"
  artist: "Gnonnas Pedro"
  album: "La belle époque: 1965 - 1975, Vol.1"
  year: 2011
  url: "https://www.youtube.com/watch?v=RgXqjIlZtkE"

-
  file: "la-combinacion-de-gnonnas.mp3"
  title: "La Combinacion De Gnonnas"
  artist: "Gnonnas Pedro"
  album: "La belle époque: 1965 - 1975, Vol.1"
  year: 2011
  url: "https://www.youtube.com/watch?v=rcGUXLBcYGE"

-
  file: "kandevie.mp3"
  title: "Kandevie"
  artist: "Gnonnas Pedro"
  album: "La belle époque: 1965 - 1975, Vol.1"
  year: 2011
  url: "https://www.youtube.com/watch?v=4ksAKOBctZw"

-
  file: "filinwe.mp3"
  title: "Filinwe"
  artist: "Gnonnas Pedro"
  album: "La belle époque: 1965 - 1975, Vol.1"
  year: 2011
  url: "https://www.youtube.com/watch?v=LT-QIExElUk"

-
  file: "yiri-yiri-boum.mp3"
  title: "Yiri Yiri Boum"
  artist: "Gnonnas Pedro"
  album: "La belle époque: 1965 - 1975, Vol.1"
  year: 2011
  url: "https://www.youtube.com/watch?v=IBB1UjZ0J4c"

-
  file: "atimawuin-dagamasi.mp3"
  title: "Atimawuin Dagamasi"
  artist: "Gnonnas Pedro"
  album: "La belle époque: 1965 - 1975, Vol.1"
  year: 2011
  url: "https://www.youtube.com/watch?v=Yyw1QUxxzv8"

-
  file: "azo-nkplon.mp3"
  title: "Azo N'kplon"
  artist: "Gnonnas Pedro"
  album: "La belle époque: 1965 - 1975, Vol.1"
  year: 2011
  url: "https://www.youtube.com/watch?v=F2EZpp625DY"

-
  file: "cicibilici.mp3"
  title: "Cicibilici"
  artist: "Gnonnas Pedro"
  album: "La belle époque: 1965 - 1975, Vol.1"
  year: 2011
  url: "https://www.youtube.com/watch?v=aUlaU_EulGk"

-
  file: "manzanillo.mp3"
  title: "Manzanillo"
  artist: "Gnonnas Pedro"
  album: "La belle époque: 1965 - 1975, Vol.1"
  year: 2011
  url: "https://www.youtube.com/watch?v=UkzhxdXHBa4"

-
  file: "mido-miton.mp3"
  title: "Mido Miton"
  artist: "Gnonnas Pedro"
  album: "La belle époque: 1965 - 1975, Vol.1"
  year: 2011
  url: "https://www.youtube.com/watch?v=8Px94luvItE"

-
  file: "agbefêso.mp3"
  title: "Agbefêso"
  artist: "Gnonnas Pedro"
  album: "La belle époque: 1965 - 1975, Vol.1"
  year: 2011
  url: "https://www.youtube.com/watch?v=HxPhCZ3oMkM"

-
  file: "lo-mejor-de-mi-treinta-años.mp3"
  title: "Lo Mejor de Mi Treinta Años"
  artist: "Gnonnas Pedro"
  album: "La belle époque: 1965 - 1975, Vol.1"
  year: 2011
  url: "https://www.youtube.com/watch?v=T8B3khFnFpg"

