-
  file: "pa-mi-gente.mp3"
  title: "Pa' Mi Gente"
  artist: "Havana D'Primera"
  album: "Pasaporte"
  year: 2012
  genre: "Timba"
  url: "https://www.youtube.com/watch?v=t_ChaU2a9oI"

-
  file: "plato-de-segunda-mesa.mp3"
  title: "Plato De Segunda Mesa"
  artist: "Havana D'Primera"
  album: "Pasaporte"
  year: 2012
  genre: "Timba"
  url: "https://www.youtube.com/watch?v=EdzKdMq394U"

-
  file: "al-final-de-la-vida.mp3"
  title: "Al Final De La Vida"
  artist: "Havana D'Primera"
  album: "Pasaporte"
  year: 2012
  genre: "Timba"
  url: "https://www.youtube.com/watch?v=OJLwVlHEnPE"

-
  file: "pasaporte.mp3"
  title: "Pasaporte"
  artist: "Havana D'Primera"
  album: "Pasaporte"
  year: 2012
  genre: "Timba"
  url: "https://www.youtube.com/watch?v=wtWV9P9x4NM"

-
  file: "se-te-olvidó-quién-soy-yo.mp3"
  title: "Se Te Olvidó Quién Soy Yo"
  artist: "Havana D'Primera"
  album: "Pasaporte"
  year: 2012
  genre: "Timba"
  url: "https://www.youtube.com/watch?v=jxklKvso-MI"

-
  file: "el-paso-de-la-bailarina.mp3"
  title: "El Paso De La Bailarina"
  artist: "Havana D'Primera"
  album: "Pasaporte"
  year: 2012
  genre: "Timba"
  url: "https://www.youtube.com/watch?v=9Rr1zgn9NRE"

-
  file: "la-celosa.mp3"
  title: "La Celosa"
  artist: "Havana D'Primera"
  album: "Pasaporte"
  year: 2012
  genre: "Timba"
  url: "https://www.youtube.com/watch?v=0gaOB-vNG70"

-
  file: "donde-estemos-tú-y-yo.mp3"
  title: "Donde Estemos Tú Y Yo"
  artist: "Havana D'Primera"
  album: "Pasaporte"
  year: 2012
  featured_artist: "Isaac Delgado"
  genre: "Timba"
  url: "https://www.youtube.com/watch?v=AGaReMIGNI0"

-
  file: "el-que-sabe-está-callao.mp3"
  title: "El Que Sabe Está Callao"
  artist: "Havana D'Primera"
  album: "Pasaporte"
  year: 2012
  genre: "Timba"
  url: "https://www.youtube.com/watch?v=dQCjwuPSIG0"

