# Topic: https://www.youtube.com/channel/UCQRodWnOwfz8zuM6KzAMYng

-
  file: "el-familión.mp3"
  title: "El Familión"
  artist: "Maykel Blanco y su Salsa Mayor"
  album: "Enfocado"
  year: 2021
  genre: "Timba"
  url: "https://www.youtube.com/watch?v=3WTmRE4L1eY"

-
  file: "pa-los-mayores-y-los-van-van.mp3"
  title: "Pa' Los Mayores y Los Van Van"
  artist: "Maykel Blanco y su Salsa Mayor"
  album: "Enfocado"
  year: 2021
  genre: "Timba"
  url: "https://www.youtube.com/watch?v=QrfPC7XaDSs"

-
  file: "ya-tú-no-coronas.mp3"
  title: "Ya Tú No Coronas"
  artist: "Maykel Blanco y su Salsa Mayor"
  album: "Que Tiene Que Te Mueve"
  year: 2019
  genre: "Timba"
  url: "https://www.youtube.com/watch?v=0rJGcaA5Rb0"

-
  file: "que-tiene-que-te-mueve.mp3"
  title: "Que Tiene Que Te Mueve"
  artist: "Maykel Blanco y su Salsa Mayor"
  album: "Que Tiene Que Te Mueve"
  year: 2019
  genre: "Timba"
  url: "https://www.youtube.com/watch?v=w73FF03A-Fk"

-
  file: "el-chaca-chaca.mp3"
  title: "El Chaca Chaca"
  artist: "Maykel Blanco y su Salsa Mayor"
  album: "Que Tiene Que Te Mueve"
  year: 2019
  genre: "Timba"
  url: "https://www.youtube.com/watch?v=G10Ad_eV0V0"

-
  file: "en-la-selva.mp3"
  title: "En La Selva"
  artist: "Maykel Blanco y su Salsa Mayor"
  album: "Que Tiene Que Te Mueve"
  year: 2019
  genre: "Timba"
  url: "https://www.youtube.com/watch?v=6Cd62qc6ycw"

-
  file: "la-cafetera.mp3"
  title: "La Cafetera"
  artist: "Maykel Blanco y su Salsa Mayor"
  album: "Que Tiene Que Te Mueve"
  year: 2019
  genre: "Timba"
  url: "https://www.youtube.com/watch?v=j7kz_4Po_xA"

-
  file: "que-no-me-quiten-la-fe.mp3"
  title: "Que No Me Quiten La Fe"
  artist: "Maykel Blanco y su Salsa Mayor"
  album: "Que No Me Quiten La Fe"
  year: 2015
  genre: "Timba"
  url: "https://www.youtube.com/watch?v=UFGFly6sjIY"

-
  file: "cuando-tenia-dinero.mp3"
  title: "Cuando Tenia Dinero"
  artist: "Maykel Blanco y su Salsa Mayor"
  album: "Que No Me Quiten La Fe"
  year: 2015
  genre: "Timba"
  url: "https://www.youtube.com/watch?v=Q1KE9bDUyIU"

-
  file: "pa-que-todo-vaya-alante.mp3"
  title: "Pa' Que Todo Vaya Alante"
  artist: "Maykel Blanco y su Salsa Mayor"
  album: "Que No Me Quiten La Fe"
  year: 2015
  genre: "Timba"
  url: "https://www.youtube.com/watch?v=EGif4sxLeX0"

-
  file: "que-es-lo-que-es.mp3"
  title: "Que Es Lo Que Es"
  artist: "Maykel Blanco y su Salsa Mayor"
  album: "Que No Me Quiten La Fe"
  year: 2015
  genre: "Timba"
  url: "https://www.youtube.com/watch?v=inunSxqlmfA"

-
  file: "mi-mulata-en-la-habana.mp3"
  title: "Mi Mulata En La Habana"
  artist: "Maykel Blanco y su Salsa Mayor"
  album: "Que No Me Quiten La Fe"
  year: 2015
  genre: "Timba"
  url: "https://www.youtube.com/watch?v=3jQW5WExKec"

-
  file: "afloja-la-guayaba.mp3"
  title: "Afloja La Guayaba"
  artist: "Maykel Blanco y su Salsa Mayor"
  album: "Que No Me Quiten La Fe"
  year: 2015
  genre: "Timba"
  url: "https://www.youtube.com/watch?v=InIgLVVxBfk"

-
  file: "son-esos.mp3"
  title: "Son Esos"
  artist: "Maykel Blanco y su Salsa Mayor"
  album: "A Toda Máquina"
  year: 2013
  genre: "Timba"
  url: "https://www.youtube.com/watch?v=AF9KLJD-loc"

-
  file: "el-artista.mp3"
  title: "El Artista"
  artist: "Maykel Blanco y su Salsa Mayor"
  album: "A Toda Máquina"
  year: 2013
  genre: "Timba"
  url: "https://www.youtube.com/watch?v=iyVjN5mgpAQ"

-
  file: "la-calle.mp3"
  title: "La Calle"
  artist: "Maykel Blanco y su Salsa Mayor"
  album: "A Toda Máquina"
  year: 2013
  genre: "Timba"
  url: "https://www.youtube.com/watch?v=IdxIENFecAY"

-
  file: "por-eso-no-vas.mp3"
  title: "Por Eso No Vas"
  artist: "Maykel Blanco y su Salsa Mayor"
  album: "Por Eso No Vas"
  year: 2023
  genre: "Timba"
  url: "https://www.youtube.com/watch?v=FnzM4L9p35o"

-
  file: "el-songo-de-todos.mp3"
  title: "El Songo De Todos"
  artist: "Maykel Blanco y su Salsa Mayor"
  album: "A Toda Máquina"
  year: 2013
  genre: "Timba"
  url: "https://www.youtube.com/watch?v=zHEauu7QlYc"

-
  file: "tremenda-pinta.mp3"
  title: "Tremenda Pinta"
  artist: "Maykel Blanco y su Salsa Mayor"
  album: "A Toda Máquina"
  year: 2013
  genre: "Timba"
  url: "https://www.youtube.com/watch?v=SKIFVJFlGOk"

-
  file: "dale-lo-que-lleva.mp3"
  title: "Dale Lo Que Lleva"
  artist: "Maykel Blanco y su Salsa Mayor"
  album: "Dale Lo Que Lleva"
  year: 2013
  featured_artist: "Maykel Fonts"
  genre: "Timba"
  url: "https://www.youtube.com/watch?v=llIZRZXmZ8A"

