# Topic: https://www.youtube.com/channel/UC34RENjmRA_BUe8A1ruIGtA

-
  file: "un-loco-con-una-moto.mp3"
  title: "Un Loco Con Una Moto"
  artist: "Pupy Y Los Que Son Son"
  album: "Siempre Pupy"
  year: 2011
  genre: "Timba"
  url: "https://www.youtube.com/watch?v=3bym9cNfORc"

-
  file: "ni-bombones-ni-caramelos.mp3"
  title: "Ni Bombones Ni Caramelos"
  artist: "Pupy Y Los Que Son Son"
  album: "Siempre Pupy"
  year: 2011
  genre: "Timba"
  url: "https://www.youtube.com/watch?v=uCAcJw_NJBE"

-
  file: "vino-a-comerse-la-habana.mp3"
  title: "Vino A Comerse La Habana"
  artist: "Pupy Y Los Que Son Son"
  album: "Siempre Pupy"
  year: 2011
  genre: "Timba"
  url: "https://www.youtube.com/watch?v=Ni2KSDvKaws"

-
  file: "si-me-quieres-conocer.mp3"
  title: "Si Me Quieres Conocer"
  artist: "Pupy Y Los Que Son Son"
  album: "Tranquilo Que Yo Controlo"
  year: 2008
  genre: "Timba"
  url: "https://www.youtube.com/watch?v=pOHPLMiMPAE"

-
  file: "se-parece-a-aquel.mp3"
  title: "Se Parece A Aquel"
  artist: "Pupy Y Los Que Son Son"
  album: "Tranquilo Que Yo Controlo"
  year: 2008
  genre: "Timba"
  url: "https://www.youtube.com/watch?v=Ou_jdr1NXZk"

-
  file: "un-poquito-al-revés.mp3"
  title: "Un Poquito al Revés"
  artist: "Pupy Y Los Que Son Son"
  album: "Tranquilo Que Yo Controlo"
  year: 2008
  genre: "Timba"
  url: "https://www.youtube.com/watch?v=sh2XN1aeMSk"

-
  file: "báilalo-hasta-afuera.mp3"
  title: "Báilalo Hasta Afuera"
  artist: "Pupy Y Los Que Son Son"
  album: "Tranquilo Que Yo Controlo"
  year: 2008
  genre: "Timba"
  url: "https://www.youtube.com/watch?v=ymGWWQLl1Tc"

-
  file: "ve-bajando.mp3"
  title: "Ve Bajando"
  artist: "Pupy Y Los Que Son Son"
  album: "Tranquilo Que Yo Controlo"
  year: 2008
  genre: "Timba"
  url: "https://www.youtube.com/watch?v=G8dzMC1nlyg"

-
  file: "nadie-puede-contra-esto.mp3"
  title: "Nadie Puede Contra Esto"
  artist: "Pupy Y Los Que Son Son"
  album: "Tranquilo Que Yo Controlo"
  year: 2008
  genre: "Timba"
  url: "https://www.youtube.com/watch?v=QT5ZhwLnwL8"

-
  file: "camina-pa-un-solo-lao.mp3"
  title: "Camina Pa' Un Solo La'o"
  artist: "Pupy Y Los Que Son Son"
  album: "Pasándola Bien"
  year: 2018
  genre: "Timba"
  url: "https://www.youtube.com/watch?v=Tx6BsBFX9Zk"

-
  file: "me-estan-llamando.mp3"
  title: "Me Estan Llamando"
  artist: "Pupy Y Los Que Son Son"
  album: "Sin Límite"
  year: 2014
  genre: "Timba"
  url: "https://www.youtube.com/watch?v=BkXBSs5I3Dk"

