# List: https://www.youtube.com/playlist?list=OLAK5uy_n2nFJP95k5thFZVSVJ1uUlnguHHVu_XbQ

-
  file: "tolú.mp3"
  title: "Tolú"
  artist: "Lucho Bermudez"
  album: "Homenaje a Los Grandes Compositores de la Musica Tropical Colombiana Volume 1"
  year: 2011
  url: "https://www.youtube.com/watch?v=bv-leLNi3Yw"

-
  file: "carmen-de-bolívar.mp3"
  title: "Carmen De Bolívar"
  artist: "Lucho Bermudez"
  album: "Homenaje a Los Grandes Compositores de la Musica Tropical Colombiana Volume 1"
  year: 2011
  url: "https://www.youtube.com/watch?v=iXdgSl96oTE"

-
  file: "la-gaita.mp3"
  title: "La Gaita"
  artist: "Lucho Bermudez"
  album: "Homenaje a Los Grandes Compositores de la Musica Tropical Colombiana Volume 1"
  year: 2011
  url: "https://www.youtube.com/watch?v=tSgbLlXEY8U"

-
  file: "colombia-tierra-querida.mp3"
  title: "Colombia Tierra Querida"
  artist: "Lucho Bermudez"
  album: "Homenaje a Los Grandes Compositores de la Musica Tropical Colombiana Volume 1"
  year: 2011
  url: "https://www.youtube.com/watch?v=gX7P2cEw87Y"

-
  file: "fiesta-de-negritos.mp3"
  title: "Fiesta De Negritos"
  artist: "Lucho Bermudez"
  album: "Homenaje a Los Grandes Compositores de la Musica Tropical Colombiana Volume 1"
  year: 2011
  url: "https://www.youtube.com/watch?v=AHleRUQjgQo"

-
  file: "salsipuedes.mp3"
  title: "Salsipuedes"
  artist: "Lucho Bermudez"
  album: "Homenaje a Los Grandes Compositores de la Musica Tropical Colombiana Volume 1"
  year: 2011
  url: "https://www.youtube.com/watch?v=13fGJhoMp-c"

-
  file: "san-fernando.mp3"
  title: "San Fernando"
  artist: "Lucho Bermudez"
  album: "Homenaje a Los Grandes Compositores de la Musica Tropical Colombiana Volume 1"
  year: 2011
  url: "https://www.youtube.com/watch?v=7nxQoTn6N4U"

-
  file: "la-danza-negra.mp3"
  title: "La Danza Negra"
  artist: "Lucho Bermudez"
  album: "Homenaje a Los Grandes Compositores de la Musica Tropical Colombiana Volume 1"
  year: 2011
  url: "https://www.youtube.com/watch?v=WtvdK8WBLjI"

-
  file: "gaiteando.mp3"
  title: "Gaiteando"
  artist: "Lucho Bermudez"
  album: "Homenaje a Los Grandes Compositores de la Musica Tropical Colombiana Volume 1"
  year: 2011
  url: "https://www.youtube.com/watch?v=FXtC6bn7GEY"

-
  file: "prende-la-vela.mp3"
  title: "Prende La Vela"
  artist: "Lucho Bermudez"
  album: "Homenaje a Los Grandes Compositores de la Musica Tropical Colombiana Volume 1"
  year: 2011
  url: "https://www.youtube.com/watch?v=OmqfJ-My9DE"

-
  file: "tina.mp3"
  title: "Tina"
  artist: "Lucho Bermudez"
  album: "Homenaje a Los Grandes Compositores de la Musica Tropical Colombiana Volume 1"
  year: 2011
  url: "https://www.youtube.com/watch?v=-tSzHCROvS0"

-
  file: "minarete.mp3"
  title: "Minarete"
  artist: "Lucho Bermudez"
  album: "Homenaje a Los Grandes Compositores de la Musica Tropical Colombiana Volume 1"
  year: 2011
  url: "https://www.youtube.com/watch?v=cmzGiCUyDWM"

-
  file: "gaita-de-las-flores.mp3"
  title: "Gaita De Las Flores"
  artist: "Lucho Bermudez"
  album: "Homenaje a Los Grandes Compositores de la Musica Tropical Colombiana Volume 1"
  year: 2011
  url: "https://www.youtube.com/watch?v=elrL7sp_gyM"

-
  file: "borrachera.mp3"
  title: "Borrachera"
  artist: "Lucho Bermudez"
  album: "Homenaje a Los Grandes Compositores de la Musica Tropical Colombiana Volume 1"
  year: 2011
  url: "https://www.youtube.com/watch?v=W-040SXjv9U"

-
  file: "arturo-garcía.mp3"
  title: "Arturo García"
  artist: "Lucho Bermudez"
  album: "Homenaje a Los Grandes Compositores de la Musica Tropical Colombiana Volume 1"
  year: 2011
  url: "https://www.youtube.com/watch?v=3wdlNiJxbc8"

