-
  file: "el-almirante-padilla.mp3"
  title: "El Almirante Padilla"
  artist: "Carlos Vives"
  album: "Escalona - Un Canto A La Vida"
  year: 1991
  genre: "Vallenato"

-
  file: "el-arco-iris.mp3"
  title: "El Arco Iris"
  artist: "Carlos Vives"
  album: "Escalona - Un Canto A La Vida"
  year: 1991
  genre: "Vallenato"

-
  file: "el-jerre-jerre.mp3"
  title: "El Jerre, Jerre"
  artist: "Carlos Vives"
  album: "Escalona - Un Canto A La Vida"
  year: 1991
  genre: "Vallenato"

-
  file: "el-mejoral.mp3"
  title: "El Mejoral"
  artist: "Carlos Vives"
  album: "Escalona - Un Canto A La Vida"
  year: 1991
  genre: "Vallenato"

-
  file: "el-testamento.mp3"
  title: "El Testamento"
  artist: "Carlos Vives"
  album: "Escalona - Un Canto A La Vida"
  year: 1991
  genre: "Vallenato"

-
  file: "el-villanuevero.mp3"
  title: "El Villanuevero"
  artist: "Carlos Vives"
  album: "Escalona - Un Canto A La Vida"
  year: 1991
  genre: "Vallenato"

-
  file: "jaime-molina.mp3"
  title: "Jaime Molina"
  artist: "Carlos Vives"
  album: "Escalona - Un Canto A La Vida"
  year: 1991
  genre: "Vallenato"

-
  file: "la-custodia-de-badillo.mp3"
  title: "La Custodia De Badillo"
  artist: "Carlos Vives"
  album: "Escalona - Un Canto A La Vida"
  year: 1991
  genre: "Vallenato"

-
  file: "la-golondrina.mp3"
  title: "La Golondrina"
  artist: "Carlos Vives"
  album: "Escalona - Un Canto A La Vida"
  year: 1991
  genre: "Vallenato"

-
  file: "la-molinera.mp3"
  title: "La Molinera"
  artist: "Carlos Vives"
  album: "Escalona - Un Canto A La Vida"
  year: 1991
  genre: "Vallenato"

-
  file: "la-patillalera.mp3"
  title: "La Patillalera"
  artist: "Carlos Vives"
  album: "Escalona - Un Canto A La Vida"
  year: 1991
  genre: "Vallenato"

-
  file: "la-resentida.mp3"
  title: "La Resentida"
  artist: "Carlos Vives"
  album: "Escalona - Un Canto A La Vida"
  year: 1991
  genre: "Vallenato"

-
  file: "miguel-canales.mp3"
  title: "Miguel Canales"
  artist: "Carlos Vives"
  album: "Escalona - Un Canto A La Vida"
  year: 1991
  genre: "Vallenato"
