-
  file: "la-murga-de-panama.mp3"
  title: La Murga
  album: Asalto Navideqo
  artist: Hictor Lavoe and Willie Colsn
  year: 1971
  
-
  file: "che-che-cole.mp3"
  title: Che Che Cole
  artist: Willie Colsn
  album: Cosa Nuestra
  year: 1970
  
-
  file: "tema-del-papelon.mp3"
  title: Tema del Papelon
  artist: Nelson y Sus Estrellas
  album: Mucho Nelson
  year: 1968
  
-
  file: "la-rebelion.mp3"
  title: Rebelion (No Le Pegue a la Negra)
  artist: Joe Arroyo Y La Verdad
  album: Musa Original
  year: 1986
  
-
  file: "acuyuye.mp3"
  title: Acuyuye
  artist: Pacheco y Su Charanga
  album: Que Suene La Flauta
  year: 1962
  
-
  file: "en-barranquilla-me-quedo.mp3"
  title: En Barranquilla Me Quedo
  artist: Joe Arroyo Y La Verdad
  album: Fuego En Mi Mente
  year: 1988
  
-
  file: "micaela.mp3"
  title: Micaela
  artist: Sonora Carruseles
  album: Heavy Salsa
  year: 1998
  
-
  file: "el-rincon.mp3"
  title: El Rincon
  artist: Conjunto Sensacisn
  album: Swing
  year: 1965
  
-
  file: "pita-camion.mp3"
  title: Pita Camisn
  artist: Charanga 76
  album: Pita Camion
  year: 1977
  
-
  file: "ganas-de-bailar-el-son.mp3"
  title: Ganas de Bailar el Son
  artist: La Charanga Casino
  album:  oberto Torres Presenta... La Charanga Casino
  year: 1979
  
-
  file: "me-voy-pa-moron.mp3"
  title: Me Voy Pa Moron
  artist: Nelson y Sus Estrellas
  album: La Salsa Y El Swing
  year: 1967
  
-
  file: "azucar.mp3"
  title: Azucar
  artist: Eddie Palmieri
  album: Azucar Pa Ti
  year: 1965
  
-
  file: "cachondea.mp3"
  title: Cachondea
  artist: Fruko y Sus Tesos
  album: Power Salsa
  year: 2000
  
-
  file: "la-salsa-se-impone.mp3"
  title: La Salsa Se Impone
  artist: Joe Quijano
  album: Joe Quijano Presenta A Ray Cruz Con El Conjunto Cachana
  year: 1977
  
-
  file: "guajiro.mp3"
  title: Guajiro
  artist: La Charanga Casino
  album: Roberto Torres Presenta... La Charanga Casino
  year: 1979
  
