-
  file: "vamonos-pa'l-monte.mp3"
  title: "Vamonos Pa'l Monte"
  artist: "Charanga La Tapa"
  album: "La Tapa"
  year: 1994
  genre: "Salsa vieja"
  url: "https://www.youtube.com/watch?v=KquEpUMy2oA"

-
  file: "el-platanal-de-bartolo.mp3"
  title: "El Platanal de Bartolo"
  artist: "Charanga La Tapa"
  album: "La Tapa"
  year: 1994
  genre: "Salsa vieja"
  url: "https://www.youtube.com/watch?v=oZojQU5LfBY"

-
  file: "papa-montero.mp3"
  title: "Papa Montero"
  artist: "Charanga La Tapa"
  album: "La Tapa"
  year: 1994
  genre: "Salsa vieja"
  url: "https://www.youtube.com/watch?v=ASH70j7wFWY"

-
  file: "oriente.mp3"
  title: "Oriente"
  artist: "Charanga La Tapa"
  album: "La Tapa"
  year: 1994
  genre: "Salsa vieja"
  url: "https://www.youtube.com/watch?v=vi3KxussFO0"

-
  file: "macorina.mp3"
  title: "Macorina"
  artist: "Charanga La Tapa"
  album: "La Tapa"
  year: 1994
  genre: "Salsa vieja"
  url: "https://www.youtube.com/watch?v=_6tnINlwHdQ"

-
  file: "presente-y-pasado.mp3"
  title: "Presente Y Pasado"
  artist: "Charanga La Tapa"
  album: "La Tapa"
  year: 1994
  genre: "Salsa vieja"
  url: "https://www.youtube.com/watch?v=Sj0y-iiafSw"

