-
  file: "ahi-na-ma.opus"
  title: "Ahí Na' Ma'"
  artist: "Descarga Boricua"
  album: "Salseando"
  genre: "Salsa"
  year: 2008
  
-
  file: "fuerza-gigante.opus"
  title: "Fuerza Gigante"
  artist: "Descarga Boricua"
  album: "Salseando"
  genre: "Salsa"
  year: 2008
  
-
  file: "arinanara.opus"
  title: "Arinanara"
  artist: "Descarga Boricua"
  album: "Salseando"
  genre: "Salsa"
  year: 2008
  
-
  file: "el-swing.opus"
  title: "El Swing"
  artist: "Descarga Boricua"
  album: "Salseando"
  genre: "Salsa"
  year: 2008
  
-
  file: "pa-bravo-yo.opus"
  title: "Pa' Bravo Yo"
  artist: "Descarga Boricua"
  album: "Salseando"
  genre: "Salsa"
  year: 2008
  
-
  file: "caridad.opus"
  title: "Caridad"
  artist: "Descarga Boricua"
  album: "Salseando"
  genre: "Salsa"
  year: 2008
  
-
  file: "la-cartera.opus"
  title: "La Cartera"
  artist: "Descarga Boricua"
  album: "Salseando"
  genre: "Salsa"
  year: 2008
  
-
  file: "lluvia.opus"
  title: "Lluvia"
  artist: "Descarga Boricua"
  album: "Salseando"
  genre: "Salsa"
  year: 2008
  
-
  file: "trucutu.opus"
  title: "Trucutu"
  artist: "Descarga Boricua"
  album: "Salseando"
  genre: "Salsa"
  year: 2008
  
-
  file: "llanto-de-cocodrilo.opus"
  title: "Llanto de Cocodrillo"
  artist: "Descarga Boricua"
  album: "Salseando"
  genre: "Salsa"
  year: 2008
  
-
  file: "senor-sereno.opus"
  title: "Señor Sereno"
  artist: "Descarga Boricua"
  album: "Salseando"
  genre: "Salsa"
  year: 2008
  
-
  file: "guancona.opus"
  title: "Guancona"
  artist: "Descarga Boricua"
  album: "Salseando"
  genre: "Salsa"
  year: 2008
  
-
  file: "que-humanidad.opus"
  title: "Que Humanidad"
  artist: "Descarga Boricua"
  album: "Salseando"
  genre: "Salsa"
  year: 2008
  
