-
  file: "ahí-na-má.mp3"
  title: "Ahí Na' Ma'"
  artist: "Descarga Boricua"
  album: "Salseando"
  genre: "Salsa"
  year: 2008
  url: "https://www.youtube.com/watch?v=OpRuwu7lqLI"
  
-
  file: "fuerza-gigante.mp3"
  title: "Fuerza Gigante"
  artist: "Descarga Boricua"
  album: "Salseando"
  genre: "Salsa"
  year: 2008
  url: "https://www.youtube.com/watch?v=Uhs_dfkD6qc"
  
-
  file: "ariñáñara.mp3"
  title: "Ariñáñara"
  artist: "Descarga Boricua"
  album: "Salseando"
  genre: "Salsa"
  year: 2008
  url: "https://www.youtube.com/watch?v=5uShIRwf8NQ"
  
-
  file: "el-swing.mp3"
  title: "El Swing"
  artist: "Descarga Boricua"
  album: "Salseando"
  genre: "Salsa"
  year: 2008
  url: "https://www.youtube.com/watch?v=QllBBRa7dp8"
  
-
  file: "pa-bravo-yo.mp3"
  title: "Pa' Bravo Yo"
  artist: "Descarga Boricua"
  album: "Salseando"
  genre: "Salsa"
  year: 2008
  url: "https://www.youtube.com/watch?v=PxTY3vqeYy4"
  
-
  file: "caridad.mp3"
  title: "Caridad"
  artist: "Descarga Boricua"
  album: "Salseando"
  genre: "Salsa"
  year: 2008
  url: "https://www.youtube.com/watch?v=WgDN6PcbPp8"
  
-
  file: "la-cartera.mp3"
  title: "La Cartera"
  artist: "Descarga Boricua"
  album: "Salseando"
  genre: "Salsa"
  year: 2008
  url: "https://www.youtube.com/watch?v=BdZPNbKCrb8"
  
-
  file: "lluvia.mp3"
  title: "Lluvia"
  artist: "Descarga Boricua"
  album: "Salseando"
  genre: "Salsa"
  year: 2008
  url: "https://www.youtube.com/watch?v=jKJTmT1-MBM"
  
-
  file: "trucutú.mp3"
  title: "Trucutú"
  artist: "Descarga Boricua"
  album: "Salseando"
  genre: "Salsa"
  year: 2008
  url: "https://www.youtube.com/watch?v=y_btdskTa-Y"
  
-
  file: "llanto-de-cocodrillo.mp3"
  title: "Llanto de Cocodrillo"
  artist: "Descarga Boricua"
  album: "Salseando"
  genre: "Salsa"
  year: 2008
  url: "https://www.youtube.com/watch?v=QtcnVICC6s4"
  
-
  file: "señor-sereno.mp3"
  title: "Señor Sereno"
  artist: "Descarga Boricua"
  album: "Salseando"
  genre: "Salsa"
  year: 2008
  url: "https://www.youtube.com/watch?v=7HALYr5VJAs"
  
-
  file: "guancona.mp3"
  title: "Guancona"
  artist: "Descarga Boricua"
  album: "Salseando"
  genre: "Salsa"
  year: 2008
  url: "https://www.youtube.com/watch?v=sQoMt7kMDYc"
  
-
  file: "qué-humanidad.mp3"
  title: "¡Qué Humanidad!"
  artist: "Descarga Boricua"
  album: "Salseando"
  genre: "Salsa"
  year: 2008
  url: "https://www.youtube.com/watch?v=jxcVzENMkQA"


-
  file: "guancona.mp3"
  title: "Guancona"
  artist: "Descarga Boricua"
  album: "Salseando"
  genre: "Salsa"
  year: 2008
  url: "https://www.youtube.com/watch?v=sQoMt7kMDYc"
