# Topic: https://www.youtube.com/@TIMBALIVE/releases
-
  file: "ave-maria-que-calor.mp3"
  title: "Ave Maria Que Calor"
  artist: "Timbalive"
  album: "From Miami a La Habana"
  year: 2010
  genre: "Rumba;Timba"
  url: "https://www.youtube.com/watch?v=lJhAK_IHLIY"

-
  file: "zorra.mp3"
  title: "Zorra"
  artist: "Timbalive"
  album: "From Miami a La Habana"
  year: 2010
  genre: "Timba"
  url: "https://www.youtube.com/watch?v=-muI5RgYNz0"

-
  file: "timba-pa-la-humanidad.mp3"
  title: "Timba Pa' La Humanidad"
  artist: "Timbalive"
  album: "From Miami a La Habana"
  year: 2010
  genre: "Timba"
  url: "https://www.youtube.com/watch?v=hSgOsOG9zsg"

-
  file: "el-dinero.mp3"
  title: "El Dinero"
  artist: "Timbalive"
  album: "From Miami a La Habana"
  year: 2010
  genre: "Timba"
  url: "https://www.youtube.com/watch?v=BTabZXxw0NQ"

-
  file: "dame-un-tin.mp3"
  title: "Dame Un Tin"
  artist: "Timbalive"
  album: "From Miami a La Habana"
  year: 2010
  genre: "Timba"
  url: "https://www.youtube.com/watch?v=lZd6oa3jFGg"

-
  file: "salsa-vitamina.mp3"
  title: "Salsa Vitamina"
  artist: "Timbalive"
  album: "La Timba Pa' To' El Mundo"
  year: 2011
  genre: "Timba"
  url: "https://www.youtube.com/watch?v=Jp62grD7OXY"

-
  file: "quimbombo.mp3"
  title: "Quimbombo"
  artist: "Timbalive"
  album: "Con La Musica Cubana No!"
  year: 2013
  genre: "Timba"
  url: "https://www.youtube.com/watch?v=IyyKEo_umV0"

-
  file: "ese-atrevimiento.mp3"
  title: "Ese Atrevimiento"
  artist: "Timbalive"
  album: "Con La Musica Cubana No!"
  year: 2013
  genre: "Rumba;Timba"
  url: "https://www.youtube.com/watch?v=YQhZ5yl8dcA"

-
  file: "lo-que-se-da-no-se-quita.mp3"
  title: "Lo Que Se Da No Se Quita"
  artist: "Timbalive"
  album: "Con La Musica Cubana No!"
  year: 2013
  genre: "Timba"
  url: "https://www.youtube.com/watch?v=5PStPhKBcdQ"

-
  file: "welcome-felicidad.mp3"
  title: "Welcome Felicidad"
  artist: "Timbalive"
  album: "Con La Musica Cubana No!"
  year: 2013
  genre: "Timba"
  url: "https://www.youtube.com/watch?v=haD3TgflEwU"

-
  file: "la-farandula-de-miami.mp3"
  title: "La Farandula De Miami"
  artist: "Timbalive"
  album: "Gasolina De Avion"
  year: 2016
  featured_artist: "Los 4"
  genre: "Timba"
  url: "https://www.youtube.com/watch?v=ca9M3hVeZNo"

-
  file: "duplicandote-la-dosis.mp3"
  title: "Duplicandote la Dosis"
  artist: "Timbalive"
  album: "Gasolina De Avion"
  year: 2016
  featured_artist: "Roberton Van Van"
  genre: "Timba"
  url: "https://www.youtube.com/watch?v=3JpfWsWx9tg"

-
  file: "en-mi-solar.mp3"
  title: "En Mi Solar"
  artist: "Timbalive"
  album: "Consumelo"
  year: 2018
  featured_artist: "Mayito Rivera;Osaín Del Monte"
  genre: "Timba"
  url: "https://www.youtube.com/watch?v=ekK8FbLGaLo"

-
  file: "calentando.mp3"
  title: "Calentando"
  artist: "Timbalive"
  album: "Consumelo"
  year: 2018
  genre: "Timba"
  url: "https://www.youtube.com/watch?v=wzaTvnKPEYU"

-
  file: "tremendo-palo.mp3"
  title: "Tremendo Palo"
  artist: "Timbalive"
  album: "Tremendo Palo"
  year: 2023
  genre: "Timba"
  url: "https://www.youtube.com/watch?v=eo3hvuMOuLE"

-
  file: "se-botó-pa-la-calle.mp3"
  title: "Se Botó Pa' La Calle"
  artist: "Timbalive"
  album: "Se Botó Pa' La Calle"
  year: 2021
  genre: "Timba"
  url: "https://www.youtube.com/watch?v=twazv81bIfY"

-
  file: "conmigo-no.mp3"
  title: "Conmigo No"
  artist: "Timbalive"
  album: "Con La Musica Cubana No!"
  year: 2013
  genre: "Timba"
  url: "https://www.youtube.com/watch?v=-X28WIssVHU"

-
  file: "tu-eres-la-candela.mp3"
  title: "Tu Eres La Candela"
  artist: "Timbalive"
  album: "Con La Musica Cubana No!"
  year: 2013
  genre: "Timba"
  url: "https://www.youtube.com/watch?v=vfHsTH63fvY"

-
  file: "díme-con-que.mp3"
  title: "Díme Con Que?"
  artist: "Timbalive"
  album: "Con La Musica Cubana No!"
  year: 2013
  genre: "Timba"
  url: "https://www.youtube.com/watch?v=YI9eoBsobJw"

-
  file: "ra-ra-ra.mp3"
  title: "Ra Ra Ra"
  artist: "Timbalive"
  album: "La Timba Pa' To' El Mundo"
  year: 2011
  genre: "Timba"
  url: "https://www.youtube.com/watch?v=kecph0xta8w"

-
  file: "arriba-tu-gozas-mas.mp3"
  title: "Arriba Tu Gozas Mas"
  artist: "Timbalive"
  album: "La Timba Pa' To' El Mundo"
  year: 2011
  genre: "Timba"
  url: "https://www.youtube.com/watch?v=IU5A-o-Wsbg"

-
  file: "consumelo.mp3"
  title: "Consumelo"
  artist: "Timbalive"
  album: "Consumelo"
  year: 2018
  genre: "Timba"
  url: "https://www.youtube.com/watch?v=cu9Y0IM4jd8"

-
  file: "la-cocina.mp3"
  title: "La Cocina"
  artist: "Timbalive"
  album: "Consumelo"
  year: 2018
  genre: "Timba"
  url: "https://www.youtube.com/watch?v=Mfot0aHlmcg"

-
  file: "esta-es-mi-musica.mp3"
  title: "Esta Es Mi Musica"
  artist: "Timbalive"
  album: "Consumelo"
  year: 2018
  genre: "Timba"
  url: "https://www.youtube.com/watch?v=W1EZAmF6DA8"

