# Topic: https://www.youtube.com/channel/UCksJICx3Z6qGYZf9aTjd5pg

-
  file: "mi-son-te-hace-sentir.mp3"
  title: "Mi Son Te Hace Sentir"
  artist: "Papaito"
  album: "Para Mis Amigos"
  year: 1984
  genre: "Son montuno"
  url: "https://www.youtube.com/watch?v=e1bOs6rvW80"

-
  file: "hay-comentarios.mp3"
  title: "Hay Comentarios"
  artist: "Papaito"
  album: "Para Mis Amigos"
  year: 1984
  genre: "Son montuno"
  url: "https://www.youtube.com/watch?v=TUuYPkWhYAs"

-
  file: "ni-hits-ni-carreras.mp3"
  title: "Ni Hits Ni Carreras"
  artist: "Papaito"
  album: "Para Mis Amigos"
  year: 1984
  genre: "Son montuno"
  url: "https://www.youtube.com/watch?v=6lBNF0Rtu5M"

-
  file: "yo-bailo-con-la-mas-fea.mp3"
  title: "Yo Bailo Con La Mas Fea"
  artist: "Papaito"
  album: "Papaito"
  year: 1982
  genre: "Son montuno"
  url: "https://www.youtube.com/watch?v=ZRjCHz5jH8c"

-
  file: "que-no-muera-el-son.mp3"
  title: "Que No Muera El Son"
  artist: "Papaito"
  album: "Papaito"
  year: 1982
  genre: "Son montuno"
  url: "https://www.youtube.com/watch?v=_ARnLsvPmd4"

-
  file: "sin-caña-y-sin-platanal.mp3"
  title: "Sin Caña Y Sin Platanal"
  artist: "Papaito"
  album: "Papaito"
  year: 1982
  genre: "Son montuno"
  url: "https://www.youtube.com/watch?v=hPPvlKZ2TEk"

-
  file: "el-guajiro-de-cunagua.mp3"
  title: "El Guajiro De Cunagua"
  artist: "Papaito"
  album: "Papaito Rinde Homenaje a Abelardo Barroso"
  year: 1980
  genre: "Son montuno"
  url: "https://www.youtube.com/watch?v=z5pUve-29bs"

-
  file: "el-panquelero.mp3"
  title: "El Panquelero"
  artist: "Papaito"
  album: "Papaito Rinde Homenaje a Abelardo Barroso"
  year: 1980
  genre: "Son montuno"
  url: "https://www.youtube.com/watch?v=VoIeUZqhlQc"

-
  file: "en-guantanamo.mp3"
  title: "En Guantanamo"
  artist: "Papaito"
  album: "Papaito Rinde Homenaje a Abelardo Barroso"
  year: 1980
  genre: "Son montuno"
  url: "https://www.youtube.com/watch?v=Tz1PViDBkx8"

-
  file: "bruca-manigua.mp3"
  title: "Bruca Manigua"
  artist: "Papaito"
  album: "Papaito Rinde Homenaje a Abelardo Barroso"
  year: 1980
  genre: "Son montuno"
  url: "https://www.youtube.com/watch?v=WmIji60dZoY"

-
  file: "mi-chiquita-quiere.mp3"
  title: "Mi Chiquita Quiere"
  artist: "Papaito"
  album: "Lo Mejor De Papaito Vol. 1"
  year: 1991
  genre: "Son montuno"
  url: "https://www.youtube.com/watch?v=VyyYf7cpNqk"

-
  file: "aprietala-en-el-rincon.mp3"
  title: "Aprietala En El Rincon"
  artist: "Papaito"
  album: "Lo Mejor De Papaito Vol. 1"
  year: 1991
  genre: "Son montuno"
  url: "https://www.youtube.com/watch?v=IyDQRtNxqJg"

-
  file: "fuego-en-los-bomberos.mp3"
  title: "Fuego En Los Bomberos"
  artist: "Papaito"
  album: "Lo Mejor De Papaito Vol. 1"
  year: 1991
  genre: "Son montuno"
  url: "https://www.youtube.com/watch?v=QBctyMFpJqo"

-
  file: "caramelo-a-kilo.mp3"
  title: "Caramelo A Kilo"
  artist: "Papaito"
  album: "Lo Mejor De Papaito Vol. 1"
  year: 1991
  genre: "Son montuno"
  url: "https://www.youtube.com/watch?v=NLZYHe1ae1s"

