-
  file: "boliviana.mp3"
  title: "Boliviana"
  artist: "Havana D'Primera"
  album: "Sera Qué Se Acabó"
  year: 2021
  genre: "Timba"
  url: "https://www.youtube.com/watch?v=5cqz-d-aNYQ"

-
  file: "siempre-si.mp3"
  title: "Siempre Si"
  artist: "Havana D'Primera"
  album: "Siempre Si"
  year: 2017
  genre: "Timba"
  url: "https://www.youtube.com/watch?v=CrCjiOGUhOs"

-
  file: "hoy-quiero-fiesta.mp3"
  title: "Hoy Quiero Fiesta"
  artist: "Havana D'Primera"
  album: "Hoy Quiero Fiesta"
  year: 2021
  genre: "Timba"
  url: "https://www.youtube.com/watch?v=sKzeP4yPVAc"

-
  file: "nena.mp3"
  title: "Nena"
  artist: "Grupo Danson"
  album: "Mi Música"
  year: 2006
  genre: "Timba"
  url: "https://www.youtube.com/watch?v=7YvW4ZJoVoM"

-
  file: "pura-imagen.mp3"
  title: "Pura Imagen"
  artist: "Havana D'Primera"
  album: "Sera Qué Se Acabó"
  year: 2021
  genre: "Timba"
  url: "https://www.youtube.com/watch?v=u-DUquuWGeg"

-
  file: "qué-sorpresa.mp3"
  title: "Qué Sorpresa"
  artist: "Havana D'Primera"
  album: "Qué Sorpresa"
  year: 2017
  genre: "Timba"
  url: "https://www.youtube.com/watch?v=DLGU-c19wR4"

