-
  file: "be.mp3"
  title: "Be"
  artist: "Common"
  album: "Be"
  year: 2005
  genre: "Hip-hop"
  track: 1
  url: "https://www.youtube.com/watch?v=uNKbjXrX9Uw"

-
  file: "the-corner.mp3"
  title: "The Corner"
  artist: "Common"
  album: "Be"
  year: 2005
  genre: "Hip-hop"
  track: 2
  url: "https://www.youtube.com/watch?v=NtYaTeZCOH0"

-
  file: "go.mp3"
  title: "GO!"
  artist: "Common"
  album: "Be"
  year: 2005
  genre: "Hip-hop"
  track: 3
  url: "https://www.youtube.com/watch?v=zAuCbjLviJY"

-
  file: "faithful.mp3"
  title: "Faithful"
  artist: "Common"
  album: "Be"
  year: 2005
  genre: "Hip-hop"
  track: 4
  url: "https://www.youtube.com/watch?v=luRNQCgxhjI"

-
  file: "testify.mp3"
  title: "Testify"
  artist: "Common"
  album: "Be"
  year: 2005
  genre: "Hip-hop"
  track: 5
  url: "https://www.youtube.com/watch?v=qVt76WViqs0"

-
  file: "love-is.mp3"
  title: "Love Is"
  artist: "Common"
  album: "Be"
  year: 2005
  genre: "Hip-hop"
  track: 6
  url: "https://www.youtube.com/watch?v=qpGT_h5SKDI"

-
  file: "chi-city.mp3"
  title: "Chi City"
  artist: "Common"
  album: "Be"
  year: 2005
  genre: "Hip-hop"
  track: 7
  url: "https://www.youtube.com/watch?v=4fpHqQWlDiA"

-
  file: "the-food.mp3"
  title: "The Food"
  artist: "Common"
  album: "Be"
  year: 2005
  genre: "Hip-hop"
  track: 8
  url: "https://www.youtube.com/watch?v=ZtH6OW4hsnE"

-
  file: "real-people.mp3"
  title: "Real People"
  artist: "Common"
  album: "Be"
  year: 2005
  genre: "Hip-hop"
  track: 9
  url: "https://www.youtube.com/watch?v=sMnebkAL6Xw"

-
  file: "they-say.mp3"
  title: "They Say"
  artist: "Common"
  album: "Be"
  year: 2005
  genre: "Hip-hop"
  track: 10
  url: "https://www.youtube.com/watch?v=dAW95PZwPUg"

-
  file: "its-your-world-1.mp3"
  title: "It's Your World 1"
  artist: "Common"
  album: "Be"
  year: 2005
  genre: "Hip-hop"
  track: 11
  url: "https://www.youtube.com/watch?v=qVR9KsYH4Sc"

-
  file: "its-your-world-2.mp3"
  title: "It's Your World 2"
  artist: "Common"
  album: "Be"
  year: 2005
  genre: "Hip-hop"
  track: 12
  url: "https://www.youtube.com/watch?v=qVR9KsYH4Sc"
