- 
  file: "those-sweet-words.mp3"
  title: "Those Sweet Words"
  artist: "Norah Jones"
  album: "Feels Like Home"
  year: 2004
  link: "https://www.youtube.com/watch?v=PMQtB3qjoh8"

- 
  file: "nightingale.mp3"
  title: "Nightingale"
  artist: "Norah Jones"
  album: "Come Away With Me"
  year: 2002
  link: "https://www.youtube.com/watch?v=69O30YpAsLc"

- 
  file: "lonestar.mp3"
  title: "Lonestar"
  artist: "Norah Jones"
  album: "Come Away With Me"
  year: 2002
  link: "https://www.youtube.com/watch?v=ok9aThYymuQ"

- 
  file: "painter-song.mp3"
  title: "Painter Song"
  artist: "Norah Jones"
  album: "Come Away With Me"
  year: 2002
  link: "https://www.youtube.com/watch?v=ibAaSxmvczw"

- 
  file: "the-nearness-of-you.mp3"
  title: "The Nearness of You"
  artist: "Norah Jones"
  album: "Come Away With Me"
  year: 2002
  link: "https://www.youtube.com/watch?v=ZVuF3rAYLyw"

- 
  file: "dont-know-why.mp3"
  title: "Don't Know Why"
  artist: "Norah Jones"
  album: "Come Away with Me"
  year: 2002
  link: "https://www.youtube.com/watch?v=Q8KsCEqJrKU"

- 
  file: "sunrise.mp3"
  title: "Sunrise"
  artist: "Norah Jones"
  album: "Feels Like Home"
  year: 2004
  link: "https://www.youtube.com/watch?v=Sl_4CVB6EVQ"

- 
  file: "feeling-the-same-way.mp3"
  title: "Feeling the Same Way"
  artist: "Norah Jones"
  album: "Come Away With Me"
  year: 2002
  link: "https://www.youtube.com/watch?v=jT1KmAZLBp4"

- 
  file: "the-long-way-home.mp3"
  title: "The Long Way Home"
  artist: "Norah Jones"
  album: "Feels Like Home"
  year: 2004
  link: "https://www.youtube.com/watch?v=2kjMciBgpk4"

- 
  file: "toes.mp3"
  title: "Toes"
  artist: "Norah Jones"
  album: "Feels Like Home"
  year: 2004
  link: "https://www.youtube.com/watch?v=LXltSG1xlvk"

- 
  file: "carry-on.mp3"
  title: "Carry On"
  artist: "Norah Jones"
  album: "Day Breaks"
  year: 2016
  link: "https://www.youtube.com/watch?v=DqA25Ug71Mc"

- 
  file: "come-away-with-me.mp3"
  title: "Come Away With Me"
  artist: "Norah Jones"
  album: "Come Away With Me"
  year: 2002
  link: "https://www.youtube.com/watch?v=rZbhDOC7oyI"

- 
  file: "the-long-day-is-over.mp3"
  title: "The Long Day Is Over"
  artist: "Norah Jones"
  album: "Come Away With Me"
  year: 2002
  link: "https://www.youtube.com/watch?v=3jM_kyPuGDc"
