# Topic: https://www.youtube.com/channel/UCcn3l_u5bgb7XmWnEiWXBrA

-
  file: "este-es-el-expresso.mp3"
  title: "Este Es el Expresso"
  artist: "Aisar y el Expresso de Cuba"
  album: "A Toda Marcha"
  year: 2022
  genre: "Timba"
  url: "https://www.youtube.com/watch?v=7DjKeXq3xn8"

-
  file: "la-cabeza-se-respeta.mp3"
  title: "La Cabeza Se Respeta"
  artist: "Aisar y el Expresso de Cuba"
  album: "La Cabeza Se Respeta"
  year: 2023
  genre: "Timba"
  url: "https://www.youtube.com/watch?v=7ZBX08pm_7w"

-
  file: "llegó-el-expresso.mp3"
  title: "Llegó el Expresso"
  artist: "Aisar y el Expresso de Cuba"
  album: "Música Cubana, Llegó el Expresso"
  year: 2017
  genre: "Timba"
  url: "https://www.youtube.com/watch?v=LvPyDxd9k3Q"

-
  file: "los-portales.mp3"
  title: "Los Portales"
  artist: "Aisar y el Expresso de Cuba"
  album: "A Toda Marcha"
  year: 2022
  genre: "Timba"
  url: "https://www.youtube.com/watch?v=uwS7SBERr7A"

-
  file: "se-soltaron.mp3"
  title: "Se Soltaron"
  artist: "Aisar y el Expresso de Cuba"
  album: "A Toda Marcha"
  year: 2022
  genre: "Timba"
  url: "https://www.youtube.com/watch?v=EHaWnORg1us"

-
  file: "un-pastel.mp3"
  title: "Un Pastel"
  artist: "Aisar y el Expresso de Cuba"
  album: "A Toda Marcha"
  year: 2022
  genre: "Timba"
  url: "https://www.youtube.com/watch?v=zRmQDf9lq5c"

