pa-mayte.mp3:
  title: "Pa Mayte"
  artist: "Carlos Vives"
  album: "La Tierra Del Olvido"
  year: 1995
  link: "https://www.youtube.com/watch?v=feaB_q4s2GM"

la-hamaca-grande.mp3:
  title: "La Hamaca Grande"
  artist: "Carlos Vives"
  album: "Clasicos De La Provincia"
  year: 1993
  link: "https://www.youtube.com/watch?v=fR9RYHqCH5c"

el-cante.mp3:
  title: "El Cante"
  artist: "Carlos Vives"
  album: "El Amor De Mi Tierra"
  year: 1999
  link: "https://www.youtube.com/watch?v=h2zV_2gBEGM"

la-gota-fria.mp3:
  title: "La Gota Fria"
  artist: "Carlos Vives"
  album: "Clasicos De La Provincia"
  year: 1993
  link: "https://www.youtube.com/watch?v=Nmb80HXWsFQ"

la-celosa.mp3:
  title: "La Celosa"
  artist: "Carlos Vives"
  album: "Clasicos De La Provincia"
  year: 1993
  link: "https://www.youtube.com/watch?v=p8rw1Bq0rXs"

la-tijera.mp3:
  title: "La Tijera"
  artist: "Carlos Vives"
  album: "Clasicos De La Provincia"
  year: 1993
  link: "https://www.youtube.com/watch?v=8VKmuZDF2vY"

la-puya-puya.mp3:
  title: "La Puya Puya"
  artist: "Carlos Vives"
  album: "La Tierra Del Olvido"
  year: 1995
  link: "https://www.youtube.com/watch?v=6k_M-uxenB4"

la-parrandita.mp3:
  title: "La Parrandita"
  artist: "Carlos Vives"
  album: "Clasicos De La Provincia II"
  year: 2009
  link: "https://www.youtube.com/watch?v=TMv2myi0NJM"

el-cantor-de-fonseca.mp3:
  title: "El Cantor de Fonseca"
  artist: "Carlos Vives"
  album: "Clasicos De La Provincia"
  year: 1993
  link: "https://www.youtube.com/watch?v=bjP8CQFG5uM"

compay-chipuco.mp3:
  title: "Compay Chipuco"
  artist: "Carlos Vives"
  album: "Clasicos De La Provincia"
  year: 1993
  link: "https://www.youtube.com/watch?v=8vC8uVnpxLM"

volver-al-valle.mp3:
  title: "Volver Al Valle"
  artist: "Carlos Vives"
  album: "El Amor De Mi Tierra"
  year: 1999
  link: "https://www.youtube.com/watch?v=cNTYTkr6nTE"

la-mona.mp3:
  title: "La Mona"
  artist: "Carlos Vives"
  album: "El Amor De Mi Tierra"
  year: 1999
  link: "https://www.youtube.com/watch?v=fWcgRJvGfDg"

el-amor-de-mi-tierra.mp3:
  title: "El Amor De Mi Tierra"
  artist: "Carlos Vives"
  album: "El Amor De Mi Tierra"
  year: 1999
  link: "https://www.youtube.com/watch?v=u66oTr-3HvI"

fidelina.mp3:
  title: "Fidelina"
  album: "La Tierra Del Olvido"
  artist: "Carlos Vives"
  year: 1995
  link: "https://www.youtube.com/watch?v=A1R0dRSS73s"

amor-sensible.mp3:
  title: "Amor Sensible"
  artist: "Carlos Vives"
  album: "Clasicos De La Provincia"
  year: 1993
  link: "https://www.youtube.com/watch?v=SgdByk9A0j0"

la-casa-en-el-aire.mp3:
  title: "La Casa en el Aire"
  artist: "Carlos Vives"
  album: "Escalona: Vol. 2"
  year: 1992
  link: "https://www.youtube.com/watch?v=Z-LmIDAEm9Q"
