# Topic: https://www.youtube.com/channel/UCJornCb7HzLsTf1nBvA1AGw

-
  file: "bailando-en-la-tropical.mp3"
  title: "Bailando en La Tropical"
  artist: "Adalberto Álvarez y Su Son"
  album: "El Son de Altura"
  year: 2014
  genre: "Timba"
  url: "https://www.youtube.com/watch?v=ercD79M1udI"

-
  file: "prepárate-pá-lo-que-traigo.mp3"
  title: "Prepárate Pá Lo Que Traigo"
  artist: "Adalberto Álvarez y su Son"
  album: "Respeto Pá los Mayores"
  year: 2013
  genre: "Timba"
  url: "https://www.youtube.com/watch?v=XMq_bW2tcU8"

-
  file: "nadie-te-va-a-querer-como-yo.mp3"
  title: "Nadie Te Va a Querer Como Yo"
  artist: "Adalberto Álvarez y su Son"
  album: "Respeto Pá los Mayores"
  year: 2013
  genre: "Timba"
  url: "https://www.youtube.com/watch?v=ZEBp3mNQji8"

-
  file: "los-caminos-de-ifá-respeto-pá-los-mayores.mp3"
  title: "Los Caminos de IFÁ / Respeto Pá los Mayores"
  artist: "Adalberto Álvarez y su Son"
  album: "Respeto Pá los Mayores"
  year: 2013
  genre: "Timba"
  url: "https://www.youtube.com/watch?v=r7tyepJf-HQ"

-
  file: "gozando-en-la-habana.mp3"
  title: "Gozando En La Habana"
  artist: "Adalberto Álvarez y su Son"
  album: "Gozando En La Habana"
  year: 2008
  genre: "Timba"
  url: "https://www.youtube.com/watch?v=K_-ZwDzd6-0"

-
  file: "si-no-vas-a-bailar.mp3"
  title: "Si No Vas A Bailar"
  artist: "Adalberto Álvarez y su Son"
  album: "Gozando En La Habana"
  year: 2008
  genre: "Timba"
  url: "https://www.youtube.com/watch?v=N7go6-o8Q7s"

-
  file: "para-bailar-casino.mp3"
  title: "Para Bailar Casino"
  artist: "Adalberto Álvarez y su Son"
  album: "Para Bailar Casino"
  year: 2003
  genre: "Timba"
  url: "https://www.youtube.com/watch?v=pRBXXahJfIg"

-
  file: "tumba-timbal-y-bongó.mp3"
  title: "Tumba, Timbal Y Bongó"
  artist: "Adalberto Álvarez y su Son"
  album: "Para Bailar Casino"
  year: 2003
  genre: "Timba"
  url: "https://www.youtube.com/watch?v=rU5DbGSObLU"

-
  file: "mi-tumbao.mp3"
  title: "Mi Tumbao"
  artist: "Adalberto Álvarez y su Son"
  album: "El Son de Adalberto Suena Cubano"
  year: 2001
  genre: "Timba"
  url: "https://www.youtube.com/watch?v=KZcl_XAaY2s"

-
  file: "amor-a-primera-vista.mp3"
  title: "Amor A Primera Vista"
  artist: "Adalberto Álvarez y su Son"
  album: "El Son de Adalberto Suena Cubano"
  year: 2001
  genre: "Timba"
  url: "https://www.youtube.com/watch?v=rBVkxM0N50E"

-
  file: "de-cuba-pal-mundo-entero.mp3"
  title: "De Cuba Pa'l Mundo Entero"
  artist: "Adalberto Álvarez y su Son"
  album: "De Cuba Pa'l Mundo Entero"
  year: 2018
  genre: "Timba"
  url: "https://www.youtube.com/watch?v=wVnWmOdHrt0"

-
  file: "los-buenos-y-los-malos.mp3"
  title: "Los Buenos y Los Malos"
  artist: "Adalberto Álvarez y su Son"
  album: "De Cuba Pa'l Mundo Entero"
  year: 2018
  genre: "Timba"
  url: "https://www.youtube.com/watch?v=51sTKJ77vQE"

-
  file: "qué-será-lo-que-tiene-la-habana.mp3"
  title: "Qué Será Lo Que Tiene la Habana"
  artist: "Adalberto Álvarez y su Son"
  album: "De Cuba Pa'l Mundo Entero"
  year: 2018
  genre: "Timba"
  url: "https://www.youtube.com/watch?v=3NhMjaz8FMQ"

-
  file: "tu-fiesta-de-cumpleaños.mp3"
  title: "Tu Fiesta de Cumpleaños"
  artist: "Adalberto Álvarez y su Son"
  album: "De Cuba Pa'l Mundo Entero"
  year: 2018
  genre: "Timba"
  url: "https://www.youtube.com/watch?v=lKgYxEBxcnY"

-
  file: "mi-linda-habanera.mp3"
  title: "Mi Linda Habanera"
  artist: "Adalberto Álvarez y su Son"
  album: "Mi Linda Habanera"
  year: 2005
  genre: "Timba"
  url: "https://www.youtube.com/watch?v=Kj0m-vYrEsM"

-
  file: "pregúntame-como-estoy.mp3"
  title: "Pregúntame Como Estoy"
  artist: "Adalberto Álvarez y su Son"
  album: "Mi Linda Habanera"
  year: 2005
  genre: "Timba"
  url: "https://www.youtube.com/watch?v=RdKeRV16-nc"

-
  file: "fin-de-semana-es-la-cita.mp3"
  title: "Fin De Semana Es La Cita"
  artist: "Adalberto Álvarez y su Son"
  album: "Grandes Éxitos De Adalberto Alvarez (Greatest Hits From The 90s)"
  year: 1997
  genre: "Timba"
  url: "https://www.youtube.com/watch?v=g-bx04vme9Y"

-
  file: "llego-la-orquesta.mp3"
  title: "Llego la Orquesta"
  artist: "Adalberto Álvarez y su Son"
  album: "A Bailar el Toca Toca"
  year: 2015
  genre: "Timba"
  url: "https://www.youtube.com/watch?v=dYduk6SWtcM"

-
  file: "lo-que-está-pasando.mp3"
  title: "Lo Que Está Pasando"
  artist: "Adalberto Álvarez y su Son"
  album: "La Salsa Caliente"
  year: 2014
  genre: "Timba"
  url: "https://www.youtube.com/watch?v=1MaYCHtlYaI"

