-
  file: "natural-mystic.mp3"
  title: "Natural Mystic"
  artist: "Bob Marley and the Wailers"
  album: "Exodus"
  year: 1977
  genre: "Reggae"
  url: "https://www.youtube.com/watch?v=2U91ELKMNlE"

-
  file: "so-much-things-to-say.mp3"
  title: "So Much Things To Say"
  artist: "Bob Marley and the Wailers"
  album: "Exodus"
  year: 1977
  genre: "Reggae"
  url: "https://www.youtube.com/watch?v=_Cp9MVaweyA"

-
  file: "guiltiness.mp3"
  title: "Guiltiness"
  artist: "Bob Marley and the Wailers"
  album: "Exodus"
  year: 1977
  genre: "Reggae"
  url: "https://www.youtube.com/watch?v=W5lAQJYLuWI"

-
  file: "the-heathen.mp3"
  title: "The Heathen"
  artist: "Bob Marley and the Wailers"
  album: "Exodus"
  year: 1977
  genre: "Reggae"
  url: "https://www.youtube.com/watch?v=dfwu0iZp7OM"

-
  file: "exodus.mp3"
  title: "Exodus"
  artist: "Bob Marley and the Wailers"
  album: "Exodus"
  year: 1977
  genre: "Reggae"
  url: "https://www.youtube.com/watch?v=JxEgBL0wAkc"

-
  file: "jamming.mp3"
  title: "Jamming"
  artist: "Bob Marley and the Wailers"
  album: "Exodus"
  year: 1977
  genre: "Reggae"
  url: "https://www.youtube.com/watch?v=7kyg6F-E4fg"

-
  file: "waiting-in-vain.mp3"
  title: "Waiting In Vain"
  artist: "Bob Marley and the Wailers"
  album: "Exodus"
  year: 1977
  genre: "Reggae"
  url: "https://www.youtube.com/watch?v=TBq4_pk_W24"

-
  file: "turn-your-lights-down-low.mp3"
  title: "Turn Your Lights Down Low"
  artist: "Bob Marley and the Wailers"
  album: "Exodus"
  year: 1977
  genre: "Reggae"
  url: "https://www.youtube.com/watch?v=fRid8Tjw_bU"

-
  file: "three-little-birds.mp3"
  title: "Three Little Birds"
  artist: "Bob Marley and the Wailers"
  album: "Exodus"
  year: 1977
  genre: "Reggae"
  url: "https://www.youtube.com/watch?v=MUNNRAdizz0"

-
  file: "one-love-people-get-ready.mp3"
  title: "One Love / People Get Ready"
  artist: "Bob Marley and the Wailers"
  album: "Exodus"
  year: 1977
  genre: "Reggae"
  url: "https://www.youtube.com/watch?v=e2ad7O8-5Xg"

