# Topic: https://www.youtube.com/@LazaritoValdesyBamboleo/releases

-
  file: "atrevimiento.mp3"
  title: "Atrevimiento"
  artist: "Lazarito Valdes y Bamboleo"
  album: "Caramelo Con Picante"
  year: 2015
  genre: "Timba"
  url: "https://www.youtube.com/watch?v=aNM1gKtMePo"

-
  file: "amanda.mp3"
  title: "Amanda"
  artist: "Lazarito Valdes y Bamboleo"
  album: "Pa' Que Bailes"
  year: 2018
  genre: "Timba"
  url: "https://www.youtube.com/watch?v=IIc1SBSjGDo"

-
  file: "caramelo-con-picante.mp3"
  title: "Caramelo Con Picante"
  artist: "Lazarito Valdes y Bamboleo"
  album: "Caramelo Con Picante"
  year: 2015
  genre: "Timba"
  url: "https://www.youtube.com/watch?v=Lg2p-JyHBXM"

-
  file: "cosa-de-locos.mp3"
  title: "Cosa De Locos"
  artist: "Lazarito Valdes y Bamboleo"
  album: "Pa' Que Bailes"
  year: 2018
  genre: "Timba"
  url: "https://www.youtube.com/watch?v=2ceaIxaQuP8"

-
  file: "lo-de-nosotros-es-musical.mp3"
  title: "Lo De Nosotros Es Musical"
  artist: "Lazarito Valdes y Bamboleo"
  album: "Pa' Que Bailes"
  year: 2018
  genre: "Timba"
  url: "https://www.youtube.com/watch?v=-dCdfdOVlfY"

-
  file: "pa-que-bailes.mp3"
  title: "Pa' Que Bailes"
  artist: "Lazarito Valdes y Bamboleo"
  album: "Pa' Que Bailes"
  year: 2018
  genre: "Timba"
  url: "https://www.youtube.com/watch?v=Ze4oj6HB7Ho"

