-
  file: "debe.mp3"
  title: "Debe"
  artist: "Ali Farka Toure & Toumani Diabate"
  album: "In the Heart of the Moon"
  year: 2005
  genre: "Kora"

-
  file: "kala.mp3"
  title: "Kala"
  album: "In the Heart of the Moon"
  artist: "Ali Farka Toure & Toumani Diabate"
  year: 2005
  genre: "Kora"

-
  file: "mamadou-boutiquier.mp3"
  title: "Mamadou Boutiquier"
  artist: "Ali Farka Toure & Toumani Diabate"
  album: "In the Heart of the Moon"
  year: 2005
  genre: "Kora"

-
  file: "monsieur-le-maire-de-niafunké.mp3"
  title: "Monsieur le Maire de Niafunke"
  artist: "Ali Farka Toure & Toumani Diabate"
  album: "In the Heart of the Moon"
  year: 2005
  genre: "Kora"

-
  file: "kaira.mp3"
  title: "Kaira"
  artist: "Ali Farka Toure & Toumani Diabate"
  album: "In the Heart of the Moon"
  year: 2005
  genre: "Kora"

-
  file: "simbo.mp3"
  title: "Simbo"
  artist: "Ali Farka Toure & Toumani Diabate"
  album: "In the Heart of the Moon"
  year: 2005
  genre: "Kora"

-
  file: "ai-ga-bani.mp3"
  title: "Ai Ga Bani"
  artist: "Ali Farka Toure & Toumani Diabate"
  album: "In the Heart of the Moon"
  year: 2005
  genre: "Kora"

-
  file: "soumbou-ya-ya.mp3"
  title: "Soumbou Ya Ya"
  artist: "Ali Farka Toure & Toumani Diabate"
  album: "In the Heart of the Moon"
  year: 2005
  genre: "Kora"

-
  file: "naweye-toro.mp3"
  title: "Naweye Toro"
  artist: "Ali Farka Toure & Toumani Diabate"
  album: "In the Heart of the Moon"
  year: 2005
  genre: "Kora"

-
  file: "kadi-kadi.mp3"
  title: "Kadi Kadi"
  artist: "Ali Farka Toure & Toumani Diabate"
  album: "In the Heart of the Moon"
  year: 2005
  genre: "Kora"

-
  file: "gomni.mp3"
  title: "Gomni"
  artist: "Ali Farka Toure & Toumani Diabate"
  album: "In the Heart of the Moon"
  year: 2005
  genre: "Kora"

-
  file: "hawa-dolo.mp3"
  title: "Hawa Dolo"
  artist: "Ali Farka Toure & Toumani Diabate"
  album: "In the Heart of the Moon"
  year: 2005
  genre: "Kora"
