-
  file: "nag-champa.mp3"
  title: "Nag Champa"
  artist: "Common"
  album: "Like Water For Chocolate"
  year: 2000
  genre: "Hip-hop"
  url: "https://www.youtube.com/watch?v=9cncKOGTCJk"

-
  file: "the-light.mp3"
  title: "The Light"
  artist: "Common"
  album: "Like Water For Chocolate"
  year: 2000
  genre: "Hip-hop"
  url: "https://www.youtube.com/watch?v=pK76GKkEc9o"

