# Topic: https://www.youtube.com/channel/UCSVfTMSaZtkRbvvV3xkkcBA

-
  file: "frutas-del-caney.mp3"
  title: "Frutas Del Caney"
  artist: "Charanga De La 4"
  album: "Interpreta A Matamoros"
  year: 1997
  genre: "Son montuno"
  url: "https://www.youtube.com/watch?v=AmfjLtHoHQo"

-
  file: "el-que-siembra-su-maiz.mp3"
  title: "El Que Siembra Su Maiz"
  artist: "Charanga De La 4"
  album: "Interpreta A Matamoros"
  year: 1997
  genre: "Son montuno"
  url: "https://www.youtube.com/watch?v=bRtuUT-I7gY"

-
  file: "buchi-pluma.mp3"
  title: "Buchi Pluma"
  artist: "Charanga De La 4"
  album: "Interpreta A Matamoros"
  year: 1997
  genre: "Son montuno"
  url: "https://www.youtube.com/watch?v=AVL8tU7jz2M"

-
  file: "son-de-la-loma.mp3"
  title: "Son De La Loma"
  artist: "Charanga De La 4"
  album: "Interpreta A Matamoros"
  year: 1997
  genre: "Son montuno"
  url: "https://www.youtube.com/watch?v=VzQZcQohMrE"

-
  file: "lágrimas-negras.mp3"
  title: "Lágrimas Negras"
  artist: "Charanga De La 4"
  album: "Interpreta A Matamoros"
  year: 1997
  genre: "Son montuno"
  url: "https://www.youtube.com/watch?v=o9tV5x65Tk0"

-
  file: "el-paralitico.mp3"
  title: "El Paralitico"
  artist: "Charanga De La 4"
  album: "Interpreta A Matamoros"
  year: 1997
  genre: "Son montuno"
  url: "https://www.youtube.com/watch?v=CAjp3yZKSwQ"

-
  file: "compay-gallo.mp3"
  title: "Compay Gallo"
  artist: "Charanga De La 4"
  album: "Interpreta A Matamoros"
  year: 1997
  genre: "Son montuno"
  url: "https://www.youtube.com/watch?v=Ax3AiXhRcdo"

-
  file: "la-mujer-de-antonio.mp3"
  title: "La Mujer De Antonio"
  artist: "Charanga De La 4"
  album: "Interpreta A Matamoros"
  year: 1997
  genre: "Son montuno"
  url: "https://www.youtube.com/watch?v=r17gnWkXSU4"

