# Topic: https://www.youtube.com/@marianaylamakynaria7313/releases

-
  file: "tu-no-sabes-na.mp3"
  title: "Tu No Sabes Na"
  artist: "Mariana y La Makynaria"
  album: "Hala Pa Tu Mano"
  year: 2020
  genre: "Timba urbana"
  url: "https://www.youtube.com/watch?v=amkrBbIlGsg"

-
  file: "le-cogí-la-vuelta.mp3"
  title: "Le Cogí La Vuelta"
  artist: "Mariana y La Makynaria"
  album: "Hala Pa Tu Mano"
  year: 2020
  genre: "Timba urbana"
  url: "https://www.youtube.com/watch?v=Tetj5EMbVLg"

-
  file: "hala-pa-tu-mano.mp3"
  title: "Hala Pa Tu Mano"
  artist: "Mariana y La Makynaria"
  album: "Hala Pa Tu Mano"
  year: 2020
  genre: "Timba urbana"
  url: "https://www.youtube.com/watch?v=TYBEC6q9ilc"

-
  file: "por-la-madrugada.mp3"
  title: "Por La Madrugada"
  artist: "Mariana y La Makynaria"
  album: "Hala Pa Tu Mano"
  year: 2020
  featured_artist: "Emilio Frias"
  genre: "Timba"
  url: "https://www.youtube.com/watch?v=qLJ1Sxeo314"

-
  file: "intro.mp3"
  title: "Intro"
  artist: "Mariana y La Makynaria"
  album: "Trabajando Fino"
  year: 2018
  genre: "Timba urbana"
  url: "https://www.youtube.com/watch?v=CGcgDVJydco"

-
  file: "trabajando-fino.mp3"
  title: "Trabajando Fino"
  artist: "Mariana y La Makynaria"
  album: "Trabajando Fino"
  year: 2018
  genre: "Timba urbana"
  url: "https://www.youtube.com/watch?v=GsanNz5Wj-c"

-
  file: "la-pasmadera.mp3"
  title: "La Pasmadera"
  artist: "Mariana y La Makynaria"
  album: "Trabajando Fino"
  year: 2018
  genre: "Timba urbana"
  url: "https://www.youtube.com/watch?v=KSuZkGWLq0s"

-
  file: "avísale-a-papá.mp3"
  title: "Avísale a Papá"
  artist: "Mariana y La Makynaria"
  album: "Trabajando Fino"
  year: 2018
  genre: "Timba urbana"
  url: "https://www.youtube.com/watch?v=5RNt1H040q4"

-
  file: "nos-vamos.mp3"
  title: "Nos Vamos"
  artist: "Mariana y La Makynaria"
  album: "Hala Pa Tu Mano"
  year: 2020
  genre: "Timba urbana"
  url: "https://www.youtube.com/watch?v=XVVEOLyLbeI"

-
  file: "el-picante.mp3"
  title: "El Picante"
  artist: "Mariana y La Makynaria"
  album: "Trabajando Fino"
  year: 2018
  genre: "Timba urbana"
  url: "https://www.youtube.com/watch?v=DRxaYNn4kC8"

-
  file: "viento-en-popa.mp3"
  title: "Viento en Popa"
  artist: "Mariana y La Makynaria"
  album: "Trabajando Fino"
  year: 2018
  featured_artist: "Yasser Ramos y su Tumbao Mayombe"
  genre: "Timba urbana"
  url: "https://www.youtube.com/watch?v=eJDEsDC0tlU"

-
  file: "la-calle.mp3"
  title: "La Calle"
  artist: "Mariana y La Makynaria"
  album: "Trabajando Fino"
  year: 2018
  genre: "Timba urbana"
  url: "https://www.youtube.com/watch?v=AV7FV8TQUes"

-
  file: "manolo.mp3"
  title: "Manolo"
  artist: "Mariana y La Makynaria"
  album: "Trabajando Fino"
  year: 2018
  genre: "Timba urbana"
  url: "https://www.youtube.com/watch?v=l9S52PeLhKw"

-
  file: "una-señal.mp3"
  title: "Una Señal"
  artist: "Mariana y La Makynaria"
  album: "Trabajando Fino"
  year: 2018
  genre: "Timba urbana"
  url: "https://www.youtube.com/watch?v=0NNSATUVH2I"

