-
  file: "one-love.mp3"
  title: "One Love / People Get Ready"
  artist: "Bob Marley and the Wailers"
  album: "Exodus"
  year: 1977
  genre: "Reggae"
  link: "https://www.youtube.com/watch?v=0Tgl0Ok2Pjg"

-
  file: "jammin.mp3"
  album: "Exodus"
  title: "Jamming"
  year: 1977
  artist: "Bob Marley and the Wailers"
  genre: "Reggae"
  link: "https://www.youtube.com/watch?v=CMB4I5HbOl4"

-
  file: "waiting-in-vain.mp3"
  album: "Exodus"
  title: "Waiting in Vain"
  year: 1977
  artist: "Bob Marley and the Wailers"
  genre: "Reggae"
  link: "https://www.youtube.com/watch?v=IWxbhC44p2w"

-
  file: "dont-worry-be-happy.mp3"
  album: "Simple Pleasures"
  title: "Don't Worry, Be Happy"
  year: 1988
  artist: "Bobby McFerrin"
  genre: "Reggae"
  link: "https://www.youtube.com/watch?v=AFDOSq6Wxa0"

-
  file: "three-little-birds.mp3"
  album: "Exodus"
  title: "Three Little Birds"
  year: 1977
  artist: "Bob Marley and the Wailers"
  genre: "Reggae"
  link: "https://www.youtube.com/watch?v=NOyRsPDPfMM"

-
  file: "is-this-love.mp3"
  album: "Kaya"
  title: "Is This Love"
  year: 1978
  artist: "Bob Marley and the Wailers"
  genre: "Reggae"
  link: "https://www.youtube.com/watch?v=co2FK0WbXX0"

-
  file: "satisfy-my-soul.mp3"
  title: "Satisfy My Soul"
  album: "Kaya"
  year: 1978
  artist: "Bob Marley and the Wailers"
  genre: "Reggae"
  link: "https://www.youtube.com/watch?v=rf2bCmYIUy0"

-
  file: "stir-it-up.mp3"
  title: "Stir It Up"
  artist: "Bob Marley and the Wailers"
  album: "Catch a Fire"
  year: 1973
  genre: "Reggae"
  link: "https://www.youtube.com/watch?v=1hwL3S3Gtzs"

-
  file: "no-woman-no-cry.mp3"
  album: "Live!"
  title: "No Woman No Cry"
  artist: "Bob Marley"
  year: 1975
  genre: "Reggae"

-
  file: "johnny-b-goode.mp3"
  title: "Johnny B. Goode"
  artist: "Peter Tosh"
  album: "Mama Africa"
  year: 1983
  genre: "Reggae"
  link: "https://www.youtube.com/watch?v=FTvehe6kPjU"
