# Topic: https://www.youtube.com/@tromboranga/releases
-
  file: "un-extraterrestre.mp3"
  title: "Un Extraterrestre"
  artist: "Tromboranga"
  album: "Te Voy A Contar"
  year: 2019
  genre: "Timba dura"
  url: "https://www.youtube.com/watch?v=ufqPjlfJZWU"

-
  file: "golpe-con-melodia.mp3"
  title: "Golpe Con Melodia"
  artist: "Tromboranga"
  album: "Golpe Con Melodia"
  year: 2015
  genre: "Son montuno"
  url: "https://www.youtube.com/watch?v=RJday4vTlFQ"

-
  file: "soy-sonero.mp3"
  title: "Soy Sonero"
  artist: "Tromboranga"
  album: "Al Mal Tiempo Buena Salsa"
  year: 2013
  genre: "Timba dura"
  url: "https://www.youtube.com/watch?v=ZeFJ6nPbMCQ"

-
  file: "palo-pa-la-campana.mp3"
  title: "Palo Pa La Campana"
  artist: "Tromboranga"
  album: "Salsa Pa Rato"
  year: 2014
  genre: "Timba dura"
  url: "https://www.youtube.com/watch?v=gXFIh3m8SS0"

-
  file: "adios-que-te-vaya-bien.mp3"
  title: "Adios Que Te Vaya Bien"
  artist: "Tromboranga"
  album: "Al Mal Tiempo Buena Salsa"
  year: 2013
  genre: "Timba dura"
  url: "https://www.youtube.com/watch?v=rtspz7AvSZo"

-
  file: "agua-que-va-caer.mp3"
  title: "Agua Que Va Caer"
  artist: "Tromboranga"
  album: "Tromboranga"
  year: 2012
  genre: "Timba dura"
  url: "https://www.youtube.com/watch?v=5P8W12mHsCY"

-
  file: "pachuly.mp3"
  title: "Pachuly"
  artist: "Tromboranga"
  album: "Tromboranga"
  year: 2012
  genre: "Timba dura"
  url: "https://www.youtube.com/watch?v=ROB3ylw2S_E"

-
  file: "bombo-laye.mp3"
  title: "Bombo Laye"
  artist: "Tromboranga"
  album: "Tromboranga"
  year: 2012
  genre: "Timba dura"
  url: "https://www.youtube.com/watch?v=U9pcWLBdl6w"

-
  file: "charrupi.mp3"
  title: "Charrupi"
  artist: "Calibre"
  album: "Charrupi"
  year: 2016
  featured_artist: "Tromboranga"
  genre: "Timba dura"
  url: "https://www.youtube.com/watch?v=1LbxV9Ryma0"

