-
  file: "baila-latino.mp3"
  title: "Baila Latino"
  artist: "Spanish Harlem Orchestra"
  album: "Viva La Tradicion"
  year: 2010
  genre: "Salsa Dura"
  url: "https://www.youtube.com/watch?v=aqbEQ67gTY4"

-
  file: "como-lo-canto-yo.mp3"
  title: "Como Lo Canto Yo"
  artist: "Spanish Harlem Orchestra"
  album: "Across 110th St. Featuring Ruben Blades"
  year: 2004
  genre: "Salsa Dura"
  url: "https://www.youtube.com/watch?v=WDX6aVLyABE"

-
  file: "dime-si-llegué-a-tiempo.mp3"
  title: "Dime Si Llegué a Tiempo"
  artist: "Spanish Harlem Orchestra"
  album: "Across 110th St. Featuring Ruben Blades"
  year: 2004
  genre: "Salsa Dura"
  url: "https://www.youtube.com/watch?v=gvMTK3R-0YQ"

-
  file: "esa-nena.mp3"
  title: "Esa Nena"
  artist: "Spanish Harlem Orchestra"
  album: "Anniversery"
  year: 2018
  genre: "Salsa Dura"

-
  file: "escucha-el-ritmo.mp3"
  title: "Escucha El Ritmo"
  artist: "Spanish Harlem Orchestra"
  album: "Across 110th St. Featuring Ruben Blades"
  year: 2004
  genre: "Salsa Dura"
  url: "https://www.youtube.com/watch?v=ZmbtG-ppn48"

-
  file: "goza-el-ritmo.mp3"
  title: "Goza el Ritmo"
  artist: "Spanish Harlem Orchestra"
  album: "Anniversery"
  year: 2018
  genre: "Salsa Dura"

-
  file: "guaracha-y-bembe.mp3"
  title: "Guaracha y Bembe"
  artist: "Spanish Harlem Orchestra"
  album: "Anniversery"
  year: 2018
  genre: "Salsa Dura"

-
  file: "la-banda.mp3"
  title: "La Banda"
  artist: "Spanish Harlem Orchestra"
  album: "Un Gran Día En El Barrio"
  year: 2002
  genre: "Salsa Dura"
  url: "https://www.youtube.com/watch?v=KhF5qGIHmZs"

-
  file: "la-fiesta-empezó.mp3"
  title: "La Fiesta Empezó"
  artist: "Spanish Harlem Orchestra"
  album: "Viva La Tradicion"
  year: 2010
  genre: "Salsa Dura"
  url: "https://www.youtube.com/watch?v=gDT8XxEl6jc"

-
  file: "la-musica-es-mi-vida.mp3"
  title: "La Musica Es Mi Vida"
  artist: "Spanish Harlem Orchestra"
  album: "Un Gran Día En El Barrio"
  year: 2002
  genre: "Salsa Dura"
  url: "https://www.youtube.com/watch?v=re-F7YV-uaA"

-
  file: "la-salsa-dura.mp3"
  title: "La Salsa Dura"
  artist: "Spanish Harlem Orchestra"
  album: "Viva La Tradicion"
  year: 2010
  genre: "Salsa Dura"
  url: "https://www.youtube.com/watch?v=jelISDIlLHY"

-
  file: "maestro-de-rumbero.mp3"
  title: "Maestro De Rumbero"
  artist: "Spanish Harlem Orchestra"
  album: "Across 110th St. Featuring Ruben Blades"
  year: 2004
  genre: "Salsa Dura"
  url: "https://www.youtube.com/watch?v=1P-4JFqmu-c"

-
  file: "mama-guela.mp3"
  title: "Mama Guela"
  artist: "Spanish Harlem Orchestra"
  album: "Un Gran Día En El Barrio"
  year: 2002
  genre: "Salsa Dura"
  url: "https://www.youtube.com/watch?v=KnRbiySWFHU"

-
  file: "pa-gozar.mp3"
  title: "Pa' Gozar"
  artist: "Spanish Harlem Orchestra"
  album: "Un Gran Día En El Barrio"
  year: 2002
  genre: "Salsa Dura"
  url: "https://www.youtube.com/watch?v=AhfIdK9H8fw"

-
  file: "plena-con-sabor.mp3"
  title: "Plena Con Sabor"
  artist: "Spanish Harlem Orchestra"
  album: "United We Swing"
  year: 2007
  genre: "Salsa Dura"
  url: "https://www.youtube.com/watch?v=Q9BP5rab6V4"

-
  file: "pueblo-latino.mp3"
  title: "Pueblo Latino"
  artist: "Spanish Harlem Orchestra"
  album: "Un Gran Día En El Barrio"
  year: 2002
  genre: "Salsa Dura"
  url: "https://www.youtube.com/watch?v=nu5FbqwbpIs"

-
  file: "que-bonito.mp3"
  title: "Que Bonito"
  artist: "Spanish Harlem Orchestra"
  album: "United We Swing"
  year: 2007
  genre: "Salsa Dura"
  url: "https://www.youtube.com/watch?v=2Db49xW8dOU"

-
  file: "salsa-pal-bailador.mp3"
  title: "Salsa Pa'l Bailador"
  artist: "Spanish Harlem Orchestra"
  album: "United We Swing"
  year: 2007
  genre: "Salsa Dura"
  url: "https://www.youtube.com/watch?v=lUE0oge_7vU"

-
  file: "son-de-corazon.mp3"
  title: "Son de Corazon"
  artist: "Spanish Harlem Orchestra"
  album: "Viva La Tradicion"
  year: 2010
  genre: "Salsa Dura"
  url: "https://www.youtube.com/watch?v=cHM3XTKlhiI"

-
  file: "te-cantare.mp3"
  title: "Te Cantaré"
  artist: "Spanish Harlem Orchestra"
  album: "Across 110th St. Featuring Ruben Blades"
  year: 2004
  genre: "Salsa Dura"
  url: "https://www.youtube.com/watch?v=AH_IUP1zVFI"

-
  file: "tun-tun-suena-el-tambor.mp3"
  title: "Tun Tun Suena el Tambor"
  artist: "Spanish Harlem Orchestra"
  album: "Across 110th St. Featuring Ruben Blades"
  year: 2004
  genre: "Salsa Dura"
  url: "https://www.youtube.com/watch?v=KBPjDtjOZdQ"

-
  file: "un-gran-dia-en-el-barrio.mp3"
  title: "Un Gran Dia En El Barrio"
  artist: "Spanish Harlem Orchestra"
  album: "Across 110th St. Featuring Ruben Blades"
  year: 2004
  genre: "Salsa Dura"
  url: "https://www.youtube.com/watch?v=00Kz86LjBO4"
