-
  file: "baila-latino.mp3"
  title: "Baila Latino"
  artist: "Spanish Harlem Orchestra"
  album: "Viva La Tradicion"
  year: 2010
  genre: "Salsa dura"

-
  file: "como-lo-canto-yo.mp3"
  title: "Como lo Canto Yo"
  artist: "Spanish Harlem Orchestra"
  album: "Across 110th St. Featuring Ruben Blades"
  year: 2004
  genre: "Salsa dura"

-
  file: "dime-si-llegue-a-tiempo.mp3"
  title: "Dime Si Llegue a Tiempo"
  artist: "Spanish Harlem Orchestra"
  album: "Across 110th St. Featuring Ruben Blades"
  year: 2004
  genre: "Salsa dura"

-
  file: "esa-nena.mp3"
  title: "Esa Nena"
  artist: "Spanish Harlem Orchestra"
  album: "Anniversery"
  year: 2018
  genre: "Salsa dura"

-
  file: "escucha-el-ritmo.mp3"
  title: "Escucha el Ritmo"
  artist: "Spanish Harlem Orchestra"
  album: "Across 110th St. Featuring Ruben Blades"
  year: 2004
  genre: "Salsa dura"

-
  file: "goza-el-ritmo.mp3"
  title: "Goza el Ritmo"
  artist: "Spanish Harlem Orchestra"
  album: "Anniversery"
  year: 2018
  genre: "Salsa dura"

-
  file: "guaracha-y-bembe.mp3"
  title: "Guaracha y Bembe"
  artist: "Spanish Harlem Orchestra"
  album: "Anniversery"
  year: 2018
  genre: "Salsa dura"

-
  file: "la-banda.mp3"
  title: "La Banda"
  artist: "Spanish Harlem Orchestra"
  album: "Un Gran Día En El Barrio"
  year: 2002
  genre: "Salsa dura"

-
  file: "la-fiesta-empezo.mp3"
  title: "La Fiesta Empezó"
  artist: "Spanish Harlem Orchestra"
  album: "Viva La Tradicion"
  year: 2010
  genre: "Salsa dura"

-
  file: "la-musica-es-mi-vida.mp3"
  title: "La Musica es Mi Vida"
  artist: "Spanish Harlem Orchestra"
  album: "Un Gran Día En El Barrio"
  year: 2002
  genre: "Salsa dura"

-
  file: "la-salsa-dura.mp3"
  title: "La Salsa Dura"
  artist: "Spanish Harlem Orchestra"
  album: "Viva La Tradicion"
  year: 2010
  genre: "Salsa dura"

-
  file: "maestro-de-rumbero.mp3"
  title: "Maestro De Rumbero"
  artist: "Spanish Harlem Orchestra"
  album: "Across 110th St. Featuring Ruben Blades"
  year: 2004
  genre: "Salsa dura"

-
  file: "mama-guela.mp3"
  title: "Mama Guela"
  artist: "Spanish Harlem Orchestra"
  album: "Un Gran Día En El Barrio"
  year: 2002
  genre: "Salsa dura"

-
  file: "pa-gozar.mp3"
  title: "Pa' Gozar"
  artist: "Spanish Harlem Orchestra"
  album: "Un Gran Día En El Barrio"
  year: 2002
  genre: "Salsa dura"

-
  file: "plena-con-sabor.mp3"
  title: "Plena con Sabor"
  artist: "Spanish Harlem Orchestra"
  album: "United We Swing"
  year: 2007
  genre: "Salsa dura"

-
  file: "pueblo-latino.mp3"
  title: "Pueblo Latino"
  artist: "Spanish Harlem Orchestra"
  album: "Un Gran Día En El Barrio"
  year: 2002
  genre: "Salsa dura"

-
  file: "que-bonito.mp3"
  title: "Que Bonito"
  artist: "Spanish Harlem Orchestra"
  album: "United We Swing"
  year: 2007
  genre: "Salsa dura"

-
  file: "salsa-pal-bailador.mp3"
  title: "Salsa Pa'l Bailador"
  artist: "Spanish Harlem Orchestra"
  album: "United We Swing"
  year: 2007
  genre: "Salsa dura"

-
  file: "son-de-corazon.mp3"
  title: "Son de Corazon"
  artist: "Spanish Harlem Orchestra"
  album: "Viva La Tradicion"
  year: 2010
  genre: "Salsa dura"

-
  file: "te-cantare.mp3"
  title: "Te Cantaré"
  artist: "Spanish Harlem Orchestra"
  album: "Across 110th St. Featuring Ruben Blades"
  year: 2004
  genre: "Salsa dura"

-
  file: "tun-tun-suena-el-tambor.mp3"
  title: "Tun Tun Suena el Tambor"
  artist: "Spanish Harlem Orchestra"
  album: "Across 110th St. Featuring Ruben Blades"
  year: 2004
  genre: "Salsa dura"

-
  file: "un-gran-dia-en-el-barrio.mp3"
  title: "Un Gran Dia En El Barrio"
  artist: "Spanish Harlem Orchestra"
  album: "Across 110th St. Featuring Ruben Blades"
  year: 2004
  genre: "Salsa dura"
