-
  file: "reina-mia.mp3"
  title: Reina Mia
  artist: Juan Luis Guerra
  album: Ojala Que Llueva Cafe
  year: 1989
  
-
  file: "a-pedir-su-mano.mp3"
  title: A Pedir Su Mano
  artist: Juan Luis Guerra
  album: Bachata Rosa
  year: 1990
  
-
  file: "la-bilirrubina.mp3"
  title: La Bilirrubina
  artist: Juan Luis Guerra
  album: Bachata Rosa
  year: 1990
  
-
  file: "la-travesia.mp3"
  title: La Travesia
  artist: Juan Luis Guerra
  album: La Llave De Mi Corazon
  year: 2007
  
-
  file: "fogarate.mp3"
  title: Fogarate
  artist: Juan Luis Guerra
  album: Fogarate
  year: 1994
  
-
  file: "la-cosquillita.mp3"
  title: La Cosquillita
  artist: Juan Luis Guerra
  album: Fogarate
  year: 1994
  
-
  file: "vale-la-pena.mp3"
  title: Vale La Pena
  artist: Juan Luis Guerra
  album: Ni Es Lo Mismo Ni Es Igual
  year: 1998
  
-
  file: "el-niagara-en-bicicleta.mp3"
  title: El Niagara en Bicicleta
  artist: Juan Luis Guerra
  album: Ni Es Lo Mismo Ni Es Igual
  year: 1998
  
-
  file: "visa-para-un-sueno.mp3"
  title: Visa Para un Sueno
  artist: Juan Luis Guerra
  album: Ojala Que Llueva Cafe
  year: 1989
  
-
  file: "el-primo.mp3"
  title: El Primo
  artist: Juan Luis Guerra
  album: Ni Es Lo Mismo Ni Es Igual
  year: 1998
  
-
  file: "el-farolito.mp3"
  title: El Farolito
  artist: Juan Luis Guerra
  album: Fogarate
  year: 1994
  
-
  file: "la-llave-de-mi-corazon.mp3"
  title: La Llave De Mi Corazon
  artist: Juan Luis Guerra
  album: La Llave De Mi Corazon
  year: 1987
  
-
  file: "guavaberry.mp3"
  title: Guavaberry
  artist: Juan Luis Guerra
  album: Mientras Mas Lo Pienso Tu
  year: 1987
  
-
  file: "razones.mp3"
  title: Razones
  artist: Juan Luis Guerra
  album: Ojala Que Llueva Cafe
  year: 1989
  
-
  file: "te-contaran.mp3"
  title: Te Contaran
  artist: Juan Luis Guerra
  album: La Llave de Mi Corazon
  year: 2007
  
-
  file: "rompiendo-fuentes.mp3"
  title: Rompiendo Fuentes
  artist: Juan Luis Guerra
  album: Areito
  year: 1992
  
-
  file: "rosalia.mp3"
  title: Rosalia
  artist: Juan Luis Guerra
  album: Bachata Rosa
  year: 1990
  
-
  file: "oficio-de-enamorado.mp3"
  title: Oficio de Enamorado
  artist: Juan Luis Guerra
  album: Fogarate
  year: 1994
  
-
  file: "quisiera.mp3"
  title: Quisiera
  artist: Juan Luis Guerra
  album: Ni Es Lo Mismo Ni Es Igual
  year: 1998
  
-
  file: "me-enamoro-de-ella.mp3"
  title: Me Enamora De Ella
  artist: Juan Luis Guerra
  album: Mientras Mas Lo Pienso...Tz
  year: 1987
