# Topic: https://www.youtube.com/channel/UCfvE0LPvf4Zf_0WnKJcNP5Q
-
  file: "la-preferencia.mp3"
  title: "La Preferencia"
  artist: "El Noro y Primera Clase"
  album: "Sin Escala"
  year: 2015
  genre: "Timba"
  url: "https://www.youtube.com/watch?v=wVM9Ma3nLBc"

-
  file: "tú-no-tienes-cambio-pa-mí.mp3"
  title: "Tú No Tienes Cambio Pa Mí"
  artist: "El Noro y Primera Clase"
  album: "Sin Escala"
  year: 2015
  genre: "Timba"
  url: "https://www.youtube.com/watch?v=h98GrKxmQqs"

