# Album: https://www.youtube.com/playlist?list=OLAK5uy_lM42FVNOdpmr_gr4W4BYUBithDaOk_qLk

-
  file: "monte-escondido.mp3"
  title: "Monte Escondido"
  artist: "Angelo Vaillant"
  album: "Soneros De Cuba Y New York"
  year: 2000
  genre: "Son montuno"
  url: "https://www.youtube.com/watch?v=8nc6Pea5eZY"

-
  file: "el-piñero.mp3"
  title: "El Piñero"
  artist: "Ernest 'Chico' Alvarez"
  album: "Soneros De Cuba Y New York"
  year: 2000
  genre: "Son montuno"
  url: "https://www.youtube.com/watch?v=cUgsp3GJKH0"

-
  file: "el-pajaro-y-el-cazador.mp3"
  title: "El Pajaro Y El Cazador"
  artist: "Angelo Vaillant"
  album: "Soneros De Cuba Y New York"
  year: 2000
  genre: "Son montuno"
  url: "https://www.youtube.com/watch?v=SPNqv7F8_JM"

-
  file: "val-carretero.mp3"
  title: "Val'Carretero"
  artist: "Ernest 'Chico' Alvarez"
  album: "Soneros De Cuba Y New York"
  year: 2000
  genre: "Son montuno"
  url: "https://www.youtube.com/watch?v=kTYWaeRPi2k"

-
  file: "guaguanco-pa-todos.mp3"
  title: "Guaguanco Pa' Todos"
  artist: "Angelo Vaillant"
  album: "Soneros De Cuba Y New York"
  year: 2000
  genre: "Son montuno"
  url: "https://www.youtube.com/watch?v=UpER7gvBdF0"

-
  file: "me-botó-la-negrita.mp3"
  title: "Me Botó La Negrita"
  artist: "Ernest 'Chico' Alvarez"
  album: "Soneros De Cuba Y New York"
  year: 2000
  genre: "Son montuno"
  url: "https://www.youtube.com/watch?v=XEds00jigaU"

-
  file: "monte-ruz.mp3"
  title: "Monte Ruz"
  artist: "Angelo Vaillant"
  album: "Soneros De Cuba Y New York"
  year: 2000
  genre: "Son montuno"
  url: "https://www.youtube.com/watch?v=hbp6v8s84yY"

-
  file: "esa-china.mp3"
  title: "Esa China"
  artist: "Ernest 'Chico' Alvarez"
  album: "Soneros De Cuba Y New York"
  year: 2000
  genre: "Son montuno"
  url: "https://www.youtube.com/watch?v=uYM1j2CPLDo"

-
  file: "cogele-el-gusto.mp3"
  title: "Cogele El Gusto"
  artist: "Ernest 'Chico' Alvarez"
  album: "Soneros De Cuba Y New York"
  year: 2000
  genre: "Son montuno"
  url: "https://www.youtube.com/watch?v=v5K-30UAP3U"

-
  file: "y-qué-pasó.mp3"
  title: "Y Qué Pasó"
  artist: "Angelo Vaillant"
  album: "Soneros De Cuba Y New York"
  year: 2000
  genre: "Son montuno"
  url: "https://www.youtube.com/watch?v=vZvn52XAvEY"

-
  file: "yo-bailo-la-chambelona.mp3"
  title: "Yo Bailo La Chambelona"
  artist: "Ernest 'Chico' Alvarez"
  album: "Soneros De Cuba Y New York"
  year: 2000
  genre: "Son montuno"
  url: "https://www.youtube.com/watch?v=zxtHhyMWibw"

-
  file: "mentiras-criollas.mp3"
  title: "Mentiras Criollas"
  artist: Angelo Vaillant
  album: Angelo Y Su Conjunto Modelo
  year: 1981
  genre: "Son montuno"
  url: "https://www.youtube.com/watch?v=xPhm9_WpEdU"

