# Topic: https://www.youtube.com/channel/UCSVfTMSaZtkRbvvV3xkkcBA

-
  file: "manzanillo.mp3"
  title: "Manzanillo"
  artist: "Charanga De La 4"
  album: "Charanga de la 4 Recuerda a Beny More, Vol. 1"
  year: 1981
  genre: "Son montuno"
  url: "https://www.youtube.com/watch?v=jswVjZSR180"

-
  file: "soy-campesino.mp3"
  title: "Soy Campesino"
  artist: "Charanga De La 4"
  album: "Charanga de la 4 Recuerda a Beny More, Vol. 1"
  year: 1981
  genre: "Son montuno"
  url: "https://www.youtube.com/watch?v=Hh6-oLU986Y"

-
  file: "guantanamo.mp3"
  title: "Guantanamo"
  artist: "Charanga De La 4"
  album: "Charanga de la 4 Recuerda a Beny More, Vol. 1"
  year: 1981
  genre: "Son montuno"
  url: "https://www.youtube.com/watch?v=1PgZeb-WCI0"

-
  file: "adios-a-palma-soriano.mp3"
  title: "Adios A Palma Soriano"
  artist: "Charanga De La 4"
  album: "Charanga de la 4 Recuerda a Beny More, Vol. 1"
  year: 1981
  genre: "Son montuno"
  url: "https://www.youtube.com/watch?v=dLyykCcr82o"

-
  file: "santa-isabel-de-las-lajas.mp3"
  title: "Santa Isabel De Las Lajas"
  artist: "Charanga De La 4"
  album: "Charanga de la 4 Recuerda a Beny More, Vol. 2"
  year: 1983
  genre: "Son montuno"
  url: "https://www.youtube.com/watch?v=cWEAPUvZCi4"

-
  file: "bonito-y-sabroso.mp3"
  title: "Bonito Y Sabroso"
  artist: "Charanga De La 4"
  album: "Charanga de la 4 Recuerda a Beny More, Vol. 2"
  year: 1983
  genre: "Son montuno"
  url: "https://www.youtube.com/watch?v=84PNECZhBmE"

-
  file: "tú-verás-margot.mp3"
  title: "Tú Verás Margot"
  artist: "Charanga De La 4"
  album: "Charanga de la 4 Recuerda a Beny More, Vol. 2"
  year: 1983
  genre: "Son montuno"
  url: "https://www.youtube.com/watch?v=Hkrj_hrcyJo"

-
  file: "mulata-con-cola.mp3"
  title: "Mulata Con Cola"
  artist: "Charanga De La 4"
  album: "Charanga de la 4 Recuerda a Beny More, Vol. 2"
  year: 1983
  genre: "Son montuno"
  url: "https://www.youtube.com/watch?v=wM1fTgtd-HI"

-
  file: "tumba-tumbadora.mp3"
  title: "Tumba Tumbadora"
  artist: "Charanga De La 4"
  album: "Charanga de la 4 Recuerda a Beny More, Vol. 3"
  year: 1983
  genre: "Son montuno"
  url: "https://www.youtube.com/watch?v=FD6yS_p1bM4"

-
  file: "mata-siguaraya.mp3"
  title: "Mata Siguaraya"
  artist: "Charanga De La 4"
  album: "Charanga de la 4 Recuerda a Beny More, Vol. 3"
  year: 1983
  genre: "Son montuno"
  url: "https://www.youtube.com/watch?v=HH3DOLH7O7Y"

-
  file: "guajiro-de-verdad.mp3"
  title: "Guajiro De Verdad"
  artist: "Charanga De La 4"
  album: "Charanga de la 4 Recuerda a Beny More, Vol. 3"
  year: 1983
  genre: "Son montuno"
  url: "https://www.youtube.com/watch?v=7GxJ0VX9w44"

-
  file: "baila-mi-son.mp3"
  title: "Baila Mi Son"
  artist: "Charanga De La 4"
  album: "Charanga de la 4 Recuerda a Beny More, Vol. 3"
  year: 1983
  genre: "Son montuno"
  url: "https://www.youtube.com/watch?v=XhI9xbAIkHk"

