# Topic: https://www.youtube.com/channel/UCO5pCBAHq9gHVge_piAJMMA

-
  file: "andamos-a-500.mp3"
  title: "Andamos A 500"
  artist: "Azúcar Negra"
  album: "Somos Azúcar"
  year: 2019
  genre: "Timba"
  url: "https://www.youtube.com/watch?v=ouQIMAPFw8A"

-
  file: "de-fiesta-en-fiesta.mp3"
  title: "De Fiesta En Fiesta"
  artist: "Azúcar Negra"
  album: "Tonada Pa'l Bailador"
  year: 2017
  genre: "Timba"
  url: "https://www.youtube.com/watch?v=8WAahynfjYY"

-
  file: "la-farándula-me-llama.mp3"
  title: "La Farándula Me Llama"
  artist: "Azúcar Negra"
  album: "Bailando Sin Parar"
  year: 2022
  genre: "Timba"
  url: "https://www.youtube.com/watch?v=hmfVvW2St28"

-
  file: "la-pasamos-bien.mp3"
  title: "La Pasamos Bien"
  artist: "Azúcar Negra"
  album: "Se Acabó el Pescao"
  year: 2011
  genre: "Timba"
  url: "https://www.youtube.com/watch?v=QWDkoJ2y71s"

-
  file: "mi-chica-se-rebela.mp3"
  title: "Mi Chica Se Rebela"
  artist: "Azúcar Negra"
  album: "Tonada Pa'l Bailador"
  year: 2017
  genre: "Timba"
  url: "https://www.youtube.com/watch?v=OwaQZKMX1bU"

-
  file: "retomando-el-son.mp3"
  title: "Retomando El Son"
  artist: "Azúcar Negra"
  album: "Tonada Pa'l Bailador"
  year: 2017
  genre: "Timba"
  url: "https://www.youtube.com/watch?v=BTai6Kr-Uro"

-
  file: "somos-azúcar.mp3"
  title: "Somos Azúcar"
  artist: "Azúcar Negra"
  album: "Somos Azúcar"
  year: 2019
  genre: "Timba"
  url: "https://www.youtube.com/watch?v=53JzpX8TwDI"

-
  file: "tonada-pal-bailador.mp3"
  title: "Tonada Pa'l Bailador"
  artist: "Azúcar Negra"
  album: "Tonada Pa'l Bailador"
  year: 2017
  genre: "Timba"
  featured_artist: "Alexander Abreu"
  url: "https://www.youtube.com/watch?v=H-Kd1t3YfzA"

