-
  file: "tolu.opus"
  title: "Tolu"
  artist: "Lucho Bermudez"
  album: "Homenaje a Los Grandes Compositores de la Musica Tropical Colombiana Volume 1"
  year: 2011
  link: "https://www.youtube.com/watch?v=bv-leLNi3Yw"
  track: 1

-
  file: "carmen-de-bolivar.opus"
  title: "Carmen de Bolivar"
  artist: "Lucho Bermudez"
  album: "Homenaje a Los Grandes Compositores de la Musica Tropical Colombiana Volume 1"
  year: 2011
  link: "https://www.youtube.com/watch?v=iXdgSl96oTE"
  track: 2

-
  file: "la-gaita.opus"
  title: "La Gaita"
  artist: "Lucho Bermudez"
  album: "Homenaje a Los Grandes Compositores de la Musica Tropical Colombiana Volume 1"
  year: 2011
  link: "https://www.youtube.com/watch?v=tSgbLlXEY8U"
  track: 3

-
  file: "colombia-tierra-querida.opus"
  title: "Colombia Tierra Querida"
  artist: "Lucho Bermudez"
  album: "Homenaje a Los Grandes Compositores de la Musica Tropical Colombiana Volume 1"
  year: 2011
  link: "https://www.youtube.com/watch?v=gX7P2cEw87Y"
  track: 4

-
  file: "fiesta-de-negritos.opus"
  title: "Fiesta de Negritos"
  artist: "Lucho Bermudez"
  album: "Homenaje a Los Grandes Compositores de la Musica Tropical Colombiana Volume 1"
  year: 2011
  link: "https://www.youtube.com/watch?v=AHleRUQjgQo"
  track: 5

-
  file: "salsipuedes.opus"
  title: "Salsipuedes"
  artist: "Lucho Bermudez"
  album: "Homenaje a Los Grandes Compositores de la Musica Tropical Colombiana Volume 1"
  year: 2011
  link: "https://www.youtube.com/watch?v=13fGJhoMp-c"
  track: 6

-
  file: "san-fernando.opus"
  title: "San Fernando"
  artist: "Lucho Bermudez"
  album: "Homenaje a Los Grandes Compositores de la Musica Tropical Colombiana Volume 1"
  year: 2011
  link: "https://www.youtube.com/watch?v=7nxQoTn6N4U"
  track: 7

-
  file: "la-danza-negra.opus"
  title: "La Danza Negra"
  artist: "Lucho Bermudez"
  album: "Homenaje a Los Grandes Compositores de la Musica Tropical Colombiana Volume 1"
  year: 2011
  link: "https://www.youtube.com/watch?v=WtvdK8WBLjI"
  track: 8

-
  file: "gaiteando.opus"
  title: "Gaiteando"
  artist: "Lucho Bermudez"
  album: "Homenaje a Los Grandes Compositores de la Musica Tropical Colombiana Volume 1"
  year: 2011
  link: "https://www.youtube.com/watch?v=FXtC6bn7GEY"
  track: 9

-
  file: "prende-la-vela.opus"
  title: "Prende la Vela"
  artist: "Lucho Bermudez"
  album: "Homenaje a Los Grandes Compositores de la Musica Tropical Colombiana Volume 1"
  year: 2011
  link: "https://www.youtube.com/watch?v=OmqfJ-My9DE"
  track: 10

-
  file: "tina.opus"
  title: "Tina"
  artist: "Lucho Bermudez"
  album: "Homenaje a Los Grandes Compositores de la Musica Tropical Colombiana Volume 1"
  year: 2011
  link: "https://www.youtube.com/watch?v=-tSzHCROvS0"
  track: 11

-
  file: "minarete.opus"
  title: "Minarete"
  artist: "Lucho Bermudez"
  album: "Homenaje a Los Grandes Compositores de la Musica Tropical Colombiana Volume 1"
  year: 2011
  link: "https://www.youtube.com/watch?v=cmzGiCUyDWM"
  track: 12

-
  file: "gaita-de-las-flores.opus"
  title: "Gaita de las Flores"
  artist: "Lucho Bermudez"
  album: "Homenaje a Los Grandes Compositores de la Musica Tropical Colombiana Volume 1"
  year: 2011
  link: "https://www.youtube.com/watch?v=elrL7sp_gyM"
  track: 13

-
  file: "arturo-garcia.opus"
  title: "Arturo Garcia"
  artist: "Lucho Bermudez"
  album: "Homenaje a Los Grandes Compositores de la Musica Tropical Colombiana Volume 1"
  year: 2011
  link: "https://www.youtube.com/watch?v=3wdlNiJxbc8"
  track: 15
