# Topic: https://www.youtube.com/channel/UCkAreMWvP4xCLfWGz37ruqA

-
  file: "a-moverse.mp3"
  title: "A Moverse"
  artist: "Berna Jam"
  album: "Welcome to Salsopoli"
  year: 2009
  genre: "Timbapop"
  url: "https://www.youtube.com/watch?v=fTzmvEto5rY"

-
  file: "caliente.mp3"
  title: "Caliente"
  artist: "Berna Jam"
  album: "Timba Pa' La Disco"
  year: 2023
  genre: "Timbapop"
  url: "https://www.youtube.com/watch?v=5tFLG6i6zAU"

-
  file: "camina.mp3"
  title: "Camina"
  artist: "Berna Jam"
  album: "Timba Pa' La Disco"
  year: 2023
  genre: "Timbapop"
  url: "https://www.youtube.com/watch?v=WI3rDwLbpps"

-
  file: "candela.mp3"
  title: "Candela"
  artist: "Berna Jam"
  album: "Welcome to Salsopoli"
  year: 2009
  genre: "Timbapop"
  url: "https://www.youtube.com/watch?v=1VmWO-qIdjM"

-
  file: "con-el-berna-jam.mp3"
  title: "Con El Berna Jam"
  artist: "Berna Jam"
  album: "Welcome to Salsopoli"
  year: 2009
  genre: "Timbapop"
  url: "https://www.youtube.com/watch?v=lWLmsMakRvQ"

-
  file: "dale-bailador.mp3"
  title: "Dale Bailador"
  artist: "Berna Jam"
  album: "Timba Pa' La Disco"
  year: 2023
  genre: "Timbapop"
  url: "https://www.youtube.com/watch?v=ftTRIyua66c"

-
  file: "el-berna-jam-ya-llego.mp3"
  title: "El Berna Jam Ya Llego"
  artist: "Berna Jam"
  album: "Welcome to Salsopoli"
  year: 2009
  genre: "Timbapop"
  url: "https://www.youtube.com/watch?v=9CdaVNB9zmE"

-
  file: "fiesta.mp3"
  title: "Fiesta"
  artist: "Berna Jam"
  album: "Welcome to Salsopoli"
  year: 2009
  genre: "Timbapop"
  url: "https://www.youtube.com/watch?v=425MXEKAvQE"

-
  file: "mi-rumba.mp3"
  title: "Mi Rumba"
  artist: "Berna Jam"
  album: "Welcome to Salsopoli"
  year: 2009
  genre: "Timbapop"
  url: "https://www.youtube.com/watch?v=FkGkOUm88i8"

-
  file: "mi-timbaton.mp3"
  title: "Mi Timbaton"
  artist: "Berna Jam"
  album: "Timba Pa' La Disco"
  year: 2023
  genre: "Timbapop"
  url: "https://www.youtube.com/watch?v=_7rrYq1TVqg"

-
  file: "rumbeando.mp3"
  title: "Rumbeando"
  artist: "Berna Jam"
  album: "No Te Dio la Cuenta"
  year: 2012
  genre: "Timbapop"
  url: "https://www.youtube.com/watch?v=vG7STvOHQwM"

-
  file: "pa-la-escuela.mp3"
  title: "Pa' La Escuela"
  artist: "Berna Jam"
  album: "No Te Dio la Cuenta"
  year: 2012
  genre: "Timbapop"
  url: "https://www.youtube.com/watch?v=_XP3KsZ-JIg"

-
  file: "se-va-conmigo.mp3"
  title: "Se Va Conmigo"
  artist: "Berna Jam"
  album: "Timba Pa' La Disco"
  year: 2023
  genre: "Timbapop"
  url: "https://www.youtube.com/watch?v=zq3gwGyICJY"

-
  file: "rumberito.mp3"
  title: "Rumberito"
  artist: "Berna Jam"
  album: "Timba Pa' La Disco"
  year: 2023
  genre: "Timbapop"
  url: "https://www.youtube.com/watch?v=s97zZkFqlqQ"

-
  file: "y-ahora-baila.mp3"
  title: "Y Ahora Baila"
  artist: "Berna Jam"
  album: "Welcome to Salsopoli"
  year: 2009
  genre: "Timbapop"
  url: "https://www.youtube.com/watch?v=PIUz5jK8uqo"

-
  file: "yo-soy-la-timba.mp3"
  title: "Yo Soy La Timba"
  artist: "Berna Jam"
  album: "Timba Pa' La Disco"
  year: 2023
  genre: "Timbapop"
  url: "https://www.youtube.com/watch?v=Ju3SUAcAXOk"

