# List: https://www.youtube.com/playlist?list=OLAK5uy_n2nFJP95k5thFZVSVJ1uUlnguHHVu_XbQ
-
  file: "porro-bonito.mp3"
  title: "Porro Bonito"
  artist: "Luis Pérez"
  album: "Homenaje a Los Grandes Compositores de la Musica Tropical Colombiana Volume 6"
  year: 2011
  url: "https://www.youtube.com/watch?v=ClSDuyWGxCU"

-
  file: "ramita-de-matimbá.mp3"
  title: "Ramita De Matimbá"
  artist: "Rosendo Martínez"
  album: "Homenaje a Los Grandes Compositores de la Musica Tropical Colombiana Volume 6"
  year: 2011
  url: "https://www.youtube.com/watch?v=G6kmE7pEdVc"

-
  file: "el-turco-perro.mp3"
  title: "El Turco Perro"
  artist: "Hilario Angarita"
  album: "Homenaje a Los Grandes Compositores de la Musica Tropical Colombiana Volume 6"
  year: 2011
  url: "https://www.youtube.com/watch?v=sw6VlwpA9ZA"

-
  file: "la-gorra.mp3"
  title: "La Gorra"
  artist: "D en D"
  album: "Homenaje a Los Grandes Compositores de la Musica Tropical Colombiana Volume 6"
  year: 2011
  url: "https://www.youtube.com/watch?v=tXVcf53pQY4"

-
  file: "guayabo-a-la-ye.mp3"
  title: "Guayabo A La Ye"
  artist: "Luis Herrán"
  album: "Homenaje a Los Grandes Compositores de la Musica Tropical Colombiana Volume 6"
  year: 2011
  url: "https://www.youtube.com/watch?v=Mb1d1OU_0zQ"

-
  file: "las-flores-rojas.mp3"
  title: "Las Flores Rojas"
  artist: "Elíseo Herrera Junco"
  album: "Homenaje a Los Grandes Compositores de la Musica Tropical Colombiana Volume 6"
  year: 2011
  url: "https://www.youtube.com/watch?v=ITZuymkhg0s"

-
  file: "la-cumbiamberita.mp3"
  title: "La Cumbiamberita"
  artist: "Ignacio Paredes"
  album: "Homenaje a Los Grandes Compositores de la Musica Tropical Colombiana Volume 6"
  year: 2011
  url: "https://www.youtube.com/watch?v=fXFQT0Umcic"

-
  file: "al-sonar-de-la-cumbia.mp3"
  title: "Al Sonar De La Cumbia"
  artist: "Luis Pérez"
  album: "Homenaje a Los Grandes Compositores de la Musica Tropical Colombiana Volume 6"
  year: 2011
  url: "https://www.youtube.com/watch?v=PRhQhWIT1QM"

-
  file: "ron-pa-todo-el-mundo.mp3"
  title: "Ron Pa' Todo El Mundo"
  artist: "Freddy Solano"
  album: "Homenaje a Los Grandes Compositores de la Musica Tropical Colombiana Volume 6"
  year: 2011
  url: "https://www.youtube.com/watch?v=hESXNGzlLHo"

-
  file: "acordeón-pitador.mp3"
  title: "Acordeón Pitador"
  artist: "Lisandro Mesa"
  album: "Homenaje a Los Grandes Compositores de la Musica Tropical Colombiana Volume 6"
  year: 2011
  url: "https://www.youtube.com/watch?v=F3OxLpiv1cM"

-
  file: "cumbia-cienaguera.mp3"
  title: "Cumbia Cienaguera"
  artist: "Luis Enrique Martínez"
  album: "Homenaje a Los Grandes Compositores de la Musica Tropical Colombiana Volume 6"
  year: 2011
  url: "https://www.youtube.com/watch?v=CDWEzmAHVCs"

-
  file: "un-poquito-de-cariño.mp3"
  title: "Un Poquito De Cariño"
  artist: "Rogelio Paredes"
  album: "Homenaje a Los Grandes Compositores de la Musica Tropical Colombiana Volume 6"
  year: 2011
  url: "https://www.youtube.com/watch?v=d2F7sCkCZrw"

-
  file: "alicia-la-flaca.mp3"
  title: "Alicia La Flaca"
  artist: "José Velásquez"
  album: "Homenaje a Los Grandes Compositores de la Musica Tropical Colombiana Volume 6"
  year: 2011
  url: "https://www.youtube.com/watch?v=_FEvEo4k6x8"

-
  file: "aji-picante.mp3"
  title: "Aji Picante"
  artist: "Aníbal Velásquez"
  album: "Homenaje a Los Grandes Compositores de la Musica Tropical Colombiana Volume 6"
  year: 2011
  url: "https://www.youtube.com/watch?v=nPpTvEc4X6o"

-
  file: "la-cachaquita.mp3"
  title: "La Cachaquita"
  artist: "Luis Pérez"
  album: "Homenaje a Los Grandes Compositores de la Musica Tropical Colombiana Volume 6"
  year: 2011
  url: "https://www.youtube.com/watch?v=qM383-L1k7E"

