-
  file: "pintame.mp3"
  title: "Pintame"
  artist: "Elvis Crespo"
  album: "Pintame"
  year: 1999
  genre: "Merengue"
  url: "https://www.youtube.com/watch?v=ZemZjPCXe0A"
  
-
  file: "por-el-caminito.mp3"
  title: "Por el Caminito"
  artist: "Elvis Crespo"
  album: "Pintame"
  year: 1999
  genre: "Merengue"
  url: "https://www.youtube.com/watch?v=uXHvXmZqr7c"
  
-
  file: "besos-de-coral.mp3"
  title: "Besos de Coral"
  artist: "Elvis Crespo"
  album: "Pintame"
  year: 1999
  genre: "Merengue"
  url: "https://www.youtube.com/watch?v=VRDYAqYZXoU"
  
-
  file: "solo-me-miro.mp3"
  title: "Solo Me Miro"
  artist: "Elvis Crespo"
  album: "Pintame"
  year: 1999
  genre: "Merengue"
  url: "https://www.youtube.com/watch?v=TfF4lQsQgFA"
  
-
  file: "tiemblo.mp3"
  title: "Tiemblo"
  artist: "Elvis Crespo"
  album: "Pintame"
  year: 1999
  genre: "Merengue"
  url: "https://www.youtube.com/watch?v=DNud6DRj420"
  
-
  file: "linda-eh.mp3"
  title: "Linda Eh"
  artist: "Grupo Mania"
  album: "Esta de Moda"
  year: 1996
  genre: "Merengue"
  url: "https://www.youtube.com/watch?v=dElUL4hvbJE"
  
-
  file: "tu-sonrisa.mp3"
  title: "Tu Sonrisa"
  artist: "Elvis Crespo"
  album: "Suavemente"
  year: 1998
  genre: "Merengue"
  url: "https://www.youtube.com/watch?v=q1QjBsMNQnM"
  
-
  file: "luna-llena.mp3"
  title: "Luna Llena"
  artist: "Elvis Crespo"
  album: "Suavemente"
  year: 1998
  genre: "Merengue"
  url: "https://www.youtube.com/watch?v=9EtC8zBHEIc"
  
-
  file: "suavemente.mp3"
  title: "Suavemente"
  artist: "Elvis Crespo"
  album: "Suavemente"
  year: 1998
  genre: "Merengue"
  url: "https://www.youtube.com/watch?v=QH0zo6AcP6g"
  
-
  file: "me-miras-y-te-miro.mp3"
  title: "Me Miras y te Miro"
  artist: "Grupo Mania"
  album: "Alto Honor"
  year: 1997
  genre: "Merengue"
  url: "https://www.youtube.com/watch?v=M3fdWamxjA0"
  
-
  file: "ojitos-bellos.mp3"
  title: "Ojitos Bellos"
  artist: "Grupo Mania"
  album: "Dance Mania"
  year: 1995
  genre: "Merengue"
  url: "https://www.youtube.com/watch?v=jnkLAMVI0so"
  
-
  file: "princesita.mp3"
  title: "Princesita"
  artist: "Elvis Crespo"
  album: "Suavemente"
  year: 1998
  genre: "Merengue"
  url: "https://www.youtube.com/watch?v=pfEf7i9uMPU"
  
-
  file: "vuelve-conmigo.mp3"
  title: "Vuelve Conmigo"
  artist: "Elvis Crespo"
  album: "Pintame"
  year: 1999
  genre: "Merengue"
  url: "https://www.youtube.com/watch?v=HCUTsauK_q8"
