-
  file: "hoah.mp3"
  title: "Hoah!"
  artist: "Calle Real"
  album: "¿¡Dime Qué?!"
  year: 2015
  genre: "Timba"
  url: "https://www.youtube.com/watch?v=6uSbG9-BZAo"

-
  file: "bienvenido.mp3"
  title: "Bienvenido"
  artist: "Calle Real"
  album: "¿¡Dime Qué?!"
  year: 2015
  genre: "Timba"
  url: "https://www.youtube.com/watch?v=oCMB6I5H0Ow"

