-
  file: "la-vuelta-al-mundo.mp3"
  title: "La Vuelta Al Mundo"
  artist: "Havana D'Primera"
  album: "La Vuelta Al Mundo"
  year: 2015
  genre: "Timba"
  url: "https://www.youtube.com/watch?v=pq6HrgYH_hg"

-
  file: "regalito-de-dios.mp3"
  title: "Regalito De Dios"
  artist: "Havana D'Primera"
  album: "La Vuelta Al Mundo"
  year: 2015
  genre: "Timba"
  url: "https://www.youtube.com/watch?v=Rf-cw3iPr58"

-
  file: "el-juego-de-la-vida.mp3"
  title: "El Juego De La Vida"
  artist: "Havana D'Primera"
  album: "La Vuelta Al Mundo"
  year: 2015
  genre: "Timba"
  url: "https://www.youtube.com/watch?v=OHezdrVKurk"

-
  file: "me-dicen-cuba.mp3"
  title: "Me Dicen Cuba"
  artist: "Havana D'Primera"
  album: "La Vuelta Al Mundo"
  year: 2015
  genre: "Timba"
  url: "https://www.youtube.com/watch?v=hqNl4TIXwV0"

-
  file: "venenosa.mp3"
  title: "Venenosa"
  artist: "Havana D'Primera"
  album: "La Vuelta Al Mundo"
  year: 2015
  genre: "Son"
  url: "https://www.youtube.com/watch?v=ZGg5KSZEdb4"

-
  file: "trece.mp3"
  title: "Trece"
  artist: "Havana D'Primera"
  album: "La Vuelta Al Mundo"
  year: 2015
  genre: "Timba"
  url: "https://www.youtube.com/watch?v=XJjm7Ats-b8"

-
  file: "el-palo-más-duro.mp3"
  title: "El Palo Más Duro"
  artist: "Havana D'Primera"
  album: "La Vuelta Al Mundo"
  year: 2015
  genre: "Timba"
  url: "https://www.youtube.com/watch?v=xH-RKpXtGy8"

-
  file: "la-mitad.mp3"
  title: "La Mitad"
  artist: "Havana D'Primera"
  album: "La Vuelta Al Mundo"
  year: 2015
  genre: "Timba"
  url: "https://www.youtube.com/watch?v=qixxGQdAKis"

-
  file: "la-peligrosa.mp3"
  title: "La Peligrosa"
  artist: "Havana D'Primera"
  album: "La Vuelta Al Mundo"
  year: 2015
  genre: "Timba"
  url: "https://www.youtube.com/watch?v=ZtEd04CoOM4"

-
  file: "después-de-mil-lunas.mp3"
  title: "Después De Mil Lunas"
  artist: "Havana D'Primera"
  album: "La Vuelta Al Mundo"
  year: 2015
  genre: "Timba"
  url: "https://www.youtube.com/watch?v=eZ9kuqbRW-Q"

-
  file: "conga-pa-cerrar.mp3"
  title: "Conga Pa' Cerrar"
  artist: "Havana D'Primera"
  album: "La Vuelta Al Mundo"
  year: 2015
  genre: "Timba"
  url: "https://www.youtube.com/watch?v=kTqYuAp4Rqc"

