# Topic: https://www.youtube.com/channel/UCahG_EKTZipi7LkiEMsEyYA
# Topic: https://www.youtube.com/channel/UC8DIoEFFJwlCumGYvzVAe0A
# Topic: https://www.youtube.com/channel/UCXp9K3VI6jxABFl6MbDTV1Q

-
  file: "pa-cualquiera.mp3"
  title: "Pa' Cualquiera"
  artist: "Papucho Y Manana Club"
  album: "Pa' Cualquiera"
  year: 2020
  genre: "Timba"
  url: "https://www.youtube.com/watch?v=31-uhYHPDys"

-
  file: "tú-no-suenas.mp3"
  title: "Tú No Suenas"
  artist: "Papucho Y Manana Club"
  album: "Pa' Cualquiera"
  year: 2020
  genre: "Timba"
  url: "https://www.youtube.com/watch?v=gr_A4n5Q68w"

-
  file: "manana-se-pega.mp3"
  title: "Manana Se Pega"
  artist: "Papucho Y Manana Club"
  album: "Pa' Cualquiera"
  year: 2020
  genre: "Timba"
  url: "https://www.youtube.com/watch?v=mTnhJRF5BF8"

-
  file: "la-especuladora-de-la-habana.mp3"
  title: "La Especuladora de la Habana"
  artist: "Papucho Y Manana Club"
  album: "Pa' Cualquiera"
  year: 2020
  genre: "Timba"
  url: "https://www.youtube.com/watch?v=0WzP38fsY3U"

-
  file: "te-pillé.mp3"
  title: "Te Pillé"
  artist: "Papucho Y Manana Club"
  album: "Pa' Cualquiera"
  year: 2020
  genre: "Timba"
  url: "https://www.youtube.com/watch?v=_yagH2MXIHQ"

-
  file: "pa-comer-y-pa-llevar.mp3"
  title: "Pa' Comer Y Pa Llevar"
  artist: "Papucho Y Manana Club"
  album: "Pa' Cualquiera"
  year: 2020
  genre: "Timba"
  url: "https://www.youtube.com/watch?v=xL0Wue1bSm0"

-
  file: "respeta.mp3"
  title: "Respeta"
  artist: "Papucho Y Manana Club"
  album: "Respeta"
  year: 2017
  genre: "Timba"
  url: "https://www.youtube.com/watch?v=3SOQLOKzb3w"

-
  file: "la-fiera.mp3"
  title: "La Fiera"
  artist: "Papucho Y Manana Club"
  album: "Mi Manana"
  year: 2015
  genre: "Timba"
  url: "https://www.youtube.com/watch?v=ogUegvbv7zM"

-
  file: "sin-susto.mp3"
  title: "Sin Susto"
  artist: "Papucho Y Manana Club"
  album: "Sin Susto"
  year: 2022
  featured_artist: "El Yera"
  genre: "Timba"
  url: "https://www.youtube.com/watch?v=f7XTTYICHzA"

