-
  file: "no-me-mires-mas.mp3"
  title: "No Me Mires Mas"
  artist: "Charanga De La 4"
  album: "Se Peg贸"
  year: 1995
  genre: "Son Montuno"
  url: "https://www.youtube.com/watch?v=O6-N3h8Ywio"

-
  file: "clavelitos.mp3"
  title: "Clavelitos"
  artist: "Charanga De La 4"
  album: "Se Peg贸"
  year: 1995
  genre: "Son Montuno"
  url: "https://www.youtube.com/watch?v=I5JgXhirtzs"

-
  file: "suavito.mp3"
  title: "Suavito"
  artist: "Charanga De La 4"
  album: "Se Peg贸"
  year: 1995
  genre: "Son Montuno"
  url: "https://www.youtube.com/watch?v=Ti7fcgSRSvA"

-
  file: "oyeme-viejito.mp3"
  title: "Oyeme Viejito"
  artist: "Charanga De La 4"
  album: "Se Peg贸"
  year: 1995
  genre: "Son Montuno"
  url: "https://www.youtube.com/watch?v=QXAJM0d5U_c"

