-
  file: "ya-sé-cantar-ya-sé-bailar.mp3"
  title: "Ya Sé Cantar, Ya Sé Bailar"
  artist: "Elito Revé y su Charangón"
  album: "¿De Qué Estamos Hablando?"
  year: 2010
  genre: "Timba"
  url: "https://www.youtube.com/watch?v=W4h3BWtFNPE"

-
  file: "agua-pa-yemayá.mp3"
  title: "Agua Pa' Yemayá"
  artist: "Elito Revé y su Charangón"
  album: "¿De Qué Estamos Hablando?"
  year: 2010
  genre: "Timba"
  url: "https://www.youtube.com/watch?v=6nafri1tNcc"

-
  file: "de-qué-estamos-hablando.mp3"
  title: "¿De Qué Estamos Hablando?"
  artist: "Elito Revé y su Charangón"
  album: "¿De Qué Estamos Hablando?"
  year: 2010
  genre: "Timba"
  url: "https://www.youtube.com/watch?v=eaN7Vm0OsbA"

-
  file: "el-jala-jala.mp3"
  title: "El Jala Jala"
  artist: "Elito Revé y su Charangón"
  album: "La Aplanadora de Cuba"
  year: 2014
  genre: "Timba"
  featured_artist: "Cristian y Rey"
  url: "https://www.youtube.com/watch?v=U_iFR1YnZmo"

