-
  file: "ron-pa-todo-el-mundo.mp3"
  title: "Ron Pa' Todo El Mundo"
  artist: "Joe Arroyo"
  album: "32 Grandes Exitos"
  year: 2000
  featured_artist: "Diomedes Díaz"
  url: "https://www.youtube.com/watch?v=QDwb6H1PpO4"

