-
  file: "resumen-de-los-90.mp3"
  title: "Resumen De Los 90"
  artist: "Havana D'Primera"
  album: "Haciendo Historia"
  year: 2009
  genre: "Timba"
  url: "https://www.youtube.com/watch?v=zwL8OJqDpr8"

-
  file: "qué-buscas.mp3"
  title: "Qué Buscas"
  artist: "Havana D'Primera"
  album: "Haciendo Historia"
  year: 2009
  genre: "Timba"
  url: "https://www.youtube.com/watch?v=iJygdGKrAQc"

-
  file: "historia-verdadera.mp3"
  title: "Historia Verdadera"
  artist: "Havana D'Primera"
  album: "Haciendo Historia"
  year: 2009
  genre: "Timba"
  url: "https://www.youtube.com/watch?v=fQSgjD0Myjc"

-
  file: "mi-música.mp3"
  title: "Mi Música"
  artist: "Havana D'Primera"
  album: "Haciendo Historia"
  year: 2009
  genre: "Timba"
  url: "https://www.youtube.com/watch?v=sCBiq_cjvI4"

-
  file: "después-de-un-beso.mp3"
  title: "Después De Un Beso"
  artist: "Havana D'Primera"
  album: "Haciendo Historia"
  year: 2009
  genre: "Timba"
  url: "https://www.youtube.com/watch?v=RioGn8N0-KU"

-
  file: "vivencias.mp3"
  title: "Vivencias"
  artist: "Havana D'Primera"
  album: "Haciendo Historia"
  year: 2009
  genre: "Timba"
  url: "https://www.youtube.com/watch?v=wKCC1u7KAPU"

-
  file: "niña-bonita.mp3"
  title: "Niña Bonita"
  artist: "Havana D'Primera"
  album: "Haciendo Historia"
  year: 2009
  genre: "Timba"
  url: "https://www.youtube.com/watch?v=deFlVOwTA2I"

-
  file: "cuando-el-río-suena.mp3"
  title: "Cuando El Río Suena"
  artist: "Havana D'Primera"
  album: "Haciendo Historia"
  year: 2009
  genre: "Timba"
  url: "https://www.youtube.com/watch?v=ahaGho8-lgo"

-
  file: "oní-oní.mp3"
  title: "Oní, Oní"
  artist: "Havana D'Primera"
  album: "Haciendo Historia"
  year: 2009
  genre: "Timba"
  url: "https://www.youtube.com/watch?v=h0YkmXhRT58"

-
  file: "confiésale.mp3"
  title: "Confiésale"
  artist: "Havana D'Primera"
  album: "Haciendo Historia"
  year: 2009
  genre: "Timba"
  url: "https://www.youtube.com/watch?v=QBBKwuhKesU"

-
  file: "las-cosas-de-un-amigo.mp3"
  title: "Las Cosas De Un Amigo"
  artist: "Havana D'Primera"
  album: "Haciendo Historia"
  year: 2009
  genre: "Timba"
  url: "https://www.youtube.com/watch?v=9ih4-QgQtT4"

