# Topic: https://www.youtube.com/channel/UCKvleX9O6wL55o_66CXAKmA
-
  file: "mirella.mp3"
  title: "Mirella"
  artist: "Conjunto Crema"
  album: "Roberto Torres Presenta al... Conjunto Crema"
  year: 1980
  genre: "Son montuno"
  url: "https://www.youtube.com/watch?v=VQjRxttZ2A8"

-
  file: "rompe-saraguey.mp3"
  title: "Rompe Saraguey"
  artist: "Conjunto Crema"
  album: "Roberto Torres Presenta al... Conjunto Crema"
  year: 1980
  genre: "Son montuno"
  url: "https://www.youtube.com/watch?v=MNeByj-OzQQ"

-
  file: "torcuata.mp3"
  title: "Torcuata"
  artist: "Conjunto Crema"
  album: "Roberto Torres Presenta al... Conjunto Crema"
  year: 1980
  genre: "Son montuno"
  url: "https://www.youtube.com/watch?v=QtRoBPGwHZc"

-
  file: "yo-si-como-candela.mp3"
  title: "Yo Si Como Candela"
  artist: "Conjunto Crema"
  album: "Roberto Torres Presenta al... Conjunto Crema"
  year: 1980
  genre: "Son montuno"
  url: "https://www.youtube.com/watch?v=aZThxHUS1PM"

-
  file: "canallón.mp3"
  title: "Canallón"
  artist: "Conjunto Crema"
  album: "Roberto Torres Presenta al... Conjunto Crema"
  year: 1980
  genre: "Son montuno"
  url: "https://www.youtube.com/watch?v=KICfC2qdEOo"

-
  file: "no-te-preocupes.mp3"
  title: "No Te Preocupes"
  artist: "Conjunto Crema"
  album: "Roberto Torres Presenta al... Conjunto Crema"
  year: 1980
  genre: "Son montuno"
  url: "https://www.youtube.com/watch?v=KICfC2qdEOo"

-
  file: "pescadores-de-camarones.mp3"
  title: "Pescadores de Camarones"
  artist: "Conjunto Crema"
  album: "La Masacre Musical"
  year: 1982
  genre: "Son montuno"
  url: "https://www.youtube.com/watch?v=fWnXDVx8szY"

-
  file: "sibanicu.mp3"
  title: "Sibanicu"
  artist: "Conjunto Crema"
  album: "La Masacre Musical"
  year: 1982
  genre: "Son montuno"
  url: "https://www.youtube.com/watch?v=OJsNDusk878"

-
  file: "el-cantante.mp3"
  title: "El Cantante"
  artist: "Conjunto Crema"
  album: "La Masacre Musical"
  year: 1982
  genre: "Son montuno"
  url: "https://www.youtube.com/watch?v=T9tgcvyohDo"

