-
  file: "yo-como-candela.mp3"
  title: "Yo Como Candela"
  artist: "Adalberto Alvarez y Su Son"
  album: "A Mi Manera"
  year: 2013
  genre: "Timba"
  url: "https://www.youtube.com/watch?v=r11k5zy5iAE"

-
  file: "dale-como-e'.mp3"
  title: "Dale Como E'"
  artist: "Adalberto Alvarez y Su Son"
  album: "A Mi Manera"
  year: 2013
  genre: "Timba"
  url: "https://www.youtube.com/watch?v=XaYifY1Z2JY"

-
  file: "cántalo-pero-báilalo.mp3"
  title: "Cántalo Pero Báilalo"
  artist: "Adalberto Alvarez y Su Son"
  album: "A Mi Manera"
  year: 2013
  genre: "Timba"
  url: "https://www.youtube.com/watch?v=Cor4zxHrEsk"

-
  file: "fin-de-semana-es-la-cita.mp3"
  title: "Fin de Semana Es la Cita"
  artist: "Adalberto Alvarez y Su Son"
  album: "Fin de Semana"
  year: 1988
  genre: "Timba"
  url: "https://www.youtube.com/watch?v=Q_3_mB8z0l8"

-
  file: "si-la-guagua-está-llena.mp3"
  title: "Si la Guagua Está Llena"
  artist: "Adalberto Álvarez y Su Son"
  album: "A Mi Manera"
  year: 2013
  genre: "Timba"
  url: "https://www.youtube.com/watch?v=xlyEawruJuM"

-
  file: "camina-y-prende-el-fogon.mp3"
  title: "Camina Y Prende El Fogon"
  artist: "Adalberto Álvarez y Su Son"
  album: "Gozando En La Habana"
  year: 2008
  genre: "Timba"
  url: "https://www.youtube.com/watch?v=AhZ__7zpIHk"

-
  file: "deja-la-mala-noche.mp3"
  title: "Deja La Mala Noche"
  artist: "Adalberto Álvarez y Su Son"
  album: "Para Bailar Casino"
  year: 2003
  genre: "Timba"
  url: "https://www.youtube.com/watch?v=isPv-SCmC5M"

-
  file: "y-que-tú-quieres-que-te-den.mp3"
  title: "Y Que Tú Quieres Que Te Den?"
  artist: "Adalberto Álvarez y Su Son"
  album: "Mi Linda Habanera"
  year: 2005
  genre: "Timba"
  url: "https://www.youtube.com/watch?v=fDyv4xIYx9g"

-
  file: "haciendo-camino.mp3"
  title: "Haciendo Camino"
  artist: "Adalberto Álvarez y Su Son"
  album: "Fin de Semana"
  year: 1988
  genre: "Timba"
  url: "https://www.youtube.com/watch?v=85jJhbKSal4"

-
  file: "mami-me-gusto.mp3"
  title: "Mami Me Gusto"
  artist: "Adalberto Álvarez y Su Son"
  album: "Fin de Semana"
  year: 1988
  genre: "Timba"
  url: "https://www.youtube.com/watch?v=CfH2F4OWbXg"

-
  file: "son-para-despertar-a-una-negrita.mp3"
  title: "Son para Despertar a una Negrita"
  artist: "Adalberto Álvarez y Su Son"
  album: "Fin de Semana"
  year: 1988
  genre: "Timba"
  url: "https://www.youtube.com/watch?v=EFoYDn5Vpbc"

-
  file: "amor-en-tiempo-de-merengue.mp3"
  title: "Amor en Tiempo de Merengue"
  artist: "Adalberto Álvarez y Su Son"
  album: "Fin de Semana"
  year: 1988
  genre: "Timba"
  url: "https://www.youtube.com/watch?v=75mb5YPx2wI"

-
  file: "a-bailar-el-toca-toca.mp3"
  title: "A Bailar El Toca Toca"
  artist: "Adalberto Álvarez y Su Son"
  album: "Grandes Éxitos De Adalberto Alvarez (Greatest Hits From The 90s)"
  year: 1997
  genre: "Timba"
  url: "https://www.youtube.com/watch?v=gz_E6EYE_Ns"

-
  file: "el-quimbombo.mp3"
  title: "El Quimbombo"
  artist: "Adalberto Álvarez y Su Son"
  album: "El Regreso de Maria"
  year: 1987
  genre: "Timba"
  url: "https://www.youtube.com/watch?v=kEcZZQjwwTY"

-
  file: "soy-la-rumba.mp3"
  title: "Soy la Rumba"
  artist: "Adalberto Álvarez y Su Son"
  album: "El Regreso de Maria"
  year: 1987
  genre: "Timba"
  url: "https://www.youtube.com/watch?v=XvAw12YRg0w"

-
  file: "y-que-tú-quieres-que-te-den-live.mp3"
  title: "Y Que Tú Quieres Que Te Den?"
  artist: "Adalberto Álvarez y Su Son"
  album: "En Vivo"
  year: 1997
  genre: "Timba"
  url: "https://www.youtube.com/watch?v=xW4Wc96UHsE"

-
  file: "menéame-la-cuna.mp3"
  title: "Menéame la Cuna"
  artist: "Adalberto Álvarez y Su Son"
  album: "A Mi Manera"
  year: 2013
  genre: "Timba"
  url: "https://www.youtube.com/watch?v=LH7H-AJGuOY"

-
  file: "linda-santiaguera.mp3"
  title: "Linda Santiaguera"
  artist: "Adalberto Álvarez y Su Son"
  album: "El Son de Altura"
  year: 2014
  genre: "Timba"
  url: "https://www.youtube.com/watch?v=vhB6vMLqySE"

-
  file: "entra-la-rumba-y-el-son.mp3"
  title: "Entra La Rumba y El Son"
  artist: "Adalberto Álvarez y Su Son"
  album: "El Son de Altura"
  year: 2014
  genre: "Rumba"
  url: "https://www.youtube.com/watch?v=LO1fY8faMp4"

-
  file: "mamaita-no-queire.mp3"
  title: "Mamaita No Quiere"
  artist: "Adalberto Álvarez y Su Son"
  album: "Locos Por El Son"
  year: 1997
  genre: "Son Montuno"
  url: "https://www.youtube.com/watch?v=eyyM59TxtkE"

-
  file: "lo-que-me-pasó-en-la-guagua.mp3"
  title: "Lo Que Me Pasó en La Guagua"
  artist: "Adalberto Álvarez y Su Son"
  album: "La Salsa Caliente"
  year: 2014
  genre: "Timba"
  url: "https://www.youtube.com/watch?v=URHYF2EhB0c"
