# Topic: https://www.youtube.com/channel/UCiM_mHhTuzhy0FosP_5TxlA
# Topic: https://www.youtube.com/channel/UCxb8EThfTB3VADeCwAlYXzw

-
  file: "yiriyiribom.mp3"
  title: "Yiri-Yiri-Bom"
  artist: "Silvestre Méndez"
  album: "Perlas Cubanas"
  year: 2014
  genres: "Perlas Cubanas"
  url: "https://www.youtube.com/watch?v=ihpGmQk0kjE"

-
  file: "mi-bomba-sonó.mp3"
  title: "Mi Bomba Sonó"
  artist: "Silvestre Méndez"
  album: "Perlas Cubanas"
  year: 2014
  genres: "Perlas Cubanas"
  url: "https://www.youtube.com/watch?v=KQHRvvl5Dl4"

-
  file: "méxico-lindo.mp3"
  title: "México Lindo"
  artist: "Silvestre Méndez"
  album: "Perlas Cubanas"
  year: 2014
  genres: "Perlas Cubanas"
  url: "https://www.youtube.com/watch?v=RctEm6f2eXw"

-
  file: "matilde-ven.mp3"
  title: "Matilde Ven"
  artist: "Silvestre Méndez"
  album: "Perlas Cubanas"
  year: 2014
  genres: "Perlas Cubanas"
  url: "https://www.youtube.com/watch?v=p5GFLeJP9tI"

-
  file: "doroteo.mp3"
  title: "Doroteo"
  artist: "Silvestre Méndez"
  album: "Perlas Cubanas"
  year: 2014
  genres: "Perlas Cubanas"
  url: "https://www.youtube.com/watch?v=-_YI3kVgU6g"

-
  file: "david-ya-no-quiso-el-arpa.mp3"
  title: "David Ya No Quiso El Arpa"
  artist: "Silvestre Méndez"
  album: "Perlas Cubanas"
  year: 2014
  genres: "Perlas Cubanas"
  url: "https://www.youtube.com/watch?v=YxaV0BQJp9g"

-
  file: "tocineta.mp3"
  title: "Tocineta"
  artist: "Silvestre Méndez"
  album: "Perlas Cubanas"
  year: 2014
  genres: "Perlas Cubanas"
  url: "https://www.youtube.com/watch?v=ro9S7_bHOSY"

-
  file: "no-sé-qué.mp3"
  title: "No Sé Qué"
  artist: "Silvestre Méndez"
  album: "Perlas Cubanas"
  year: 2014
  genres: "Perlas Cubanas"
  url: "https://www.youtube.com/watch?v=AsnLS9Ecvgo"

-
  file: "pero-que-suegro.mp3"
  title: "Pero Que Suegro"
  artist: "Silvestre Méndez"
  album: "Perlas Cubanas"
  year: 2014
  genres: "Perlas Cubanas"
  url: "https://www.youtube.com/watch?v=g9bPrZi_ClY"

-
  file: "cuba-es-así.mp3"
  title: "Cuba Es Así"
  artist: "Silvestre Méndez"
  album: "Perlas Cubanas"
  year: 2014
  genres: "Perlas Cubanas"
  url: "https://www.youtube.com/watch?v=jWxcm_q3aZs"

-
  file: "baila-pollito.mp3"
  title: "Baila Pollito"
  artist: "Silvestre Méndez Y Su Conjunto"
  album: "Baila Pollito"
  year: 2014
  genre: "Perlas Cubanas"
  url: "https://www.youtube.com/watch?v=bURA1hhBdc8"

-
  file: "de-méxico-a-la-habana.mp3"
  title: "De México A La Habana"
  artist: "Silvestre Méndez Y Su Conjunto"
  album: "Baila Pollito"
  year: 2014
  genre: "Perlas Cubanas"
  url: "https://www.youtube.com/watch?v=mgMjFWAee9Q"

-
  file: "oye-mi-son-cha-cha-chá.mp3"
  title: "Oye Mi Son Cha Cha Chá"
  artist: "Silvestre Méndez Y Su Conjunto"
  album: "Baila Pollito"
  year: 2014
  genre: "Perlas Cubanas"
  url: "https://www.youtube.com/watch?v=l9ghGuMwZlo"

-
  file: "baila-cachita.mp3"
  title: "Baila Cachita"
  artist: "Silvestre Méndez Y Su Conjunto"
  album: "Baila Pollito"
  year: 2014
  genre: "Perlas Cubanas"
  url: "https://www.youtube.com/watch?v=sg98asrZsu4"

-
  file: "orgullo-veracruzano.mp3"
  title: "Orgullo Veracruzano"
  artist: "Silvestre Méndez Y Su Conjunto"
  album: "Baila Pollito"
  year: 2014
  genre: "Perlas Cubanas"
  url: "https://www.youtube.com/watch?v=lAHUdfmUSRY"

-
  file: "rompiendo-la-rutina.mp3"
  title: "Rompiendo La Rutina"
  artist: "Silvestre Méndez Y Su Conjunto"
  album: "Soy Rumbero"
  year: 2010
  genre: "Perlas Cubanas"
  url: "https://www.youtube.com/watch?v=Gtmlw0LVVPs"

-
  file: "cantando-en-calo.mp3"
  title: "Cantando En Calo"
  artist: "Silvestre Méndez Y Su Conjunto"
  album: "Soy Rumbero"
  year: 2010
  genre: "Perlas Cubanas"
  url: "https://www.youtube.com/watch?v=x4j7Fsv5QUI"

-
  file: "cha-cha-guere.mp3"
  title: "Cha Cha Guere"
  artist: "Silvestre Méndez Y Su Conjunto"
  album: "Soy Rumbero"
  year: 2010
  genre: "Perlas Cubanas"
  url: "https://www.youtube.com/watch?v=pSxX9gof4Fc"

-
  file: "anda-pollito.mp3"
  title: "Anda Pollito"
  artist: "Silvestre Méndez Y Su Conjunto"
  album: "Soy Rumbero"
  year: 2010
  genre: "Perlas Cubanas"
  url: "https://www.youtube.com/watch?v=rYEU7QHRZm4"

-
  file: "ay-casimira.mp3"
  title: "Ay Casimira"
  artist: "Silvestre Méndez Y Su Conjunto"
  album: "Soy Rumbero"
  year: 2010
  genre: "Perlas Cubanas"
  url: "https://www.youtube.com/watch?v=lmgRSCrejpk"

-
  file: "saludo-a-veracruz.mp3"
  title: "Saludo A Veracruz"
  artist: "Silvestre Méndez Y Su Conjunto"
  album: "Salsa Cubana"
  year: 2014
  genre: "Perlas Cubanas"
  url: "https://www.youtube.com/watch?v=YqjH3D5-tgU"

-
  file: "pa-gozarlo.mp3"
  title: "Pa' Gozarlo"
  artist: "Silvestre Méndez Y Su Conjunto"
  album: "Soy Rumbero"
  year: 2010
  genre: "Perlas Cubanas"
  url: "https://www.youtube.com/watch?v=SS4gcvsTRoo"

-
  file: "me-llama-la-tambo.mp3"
  title: "Me Llama La Tambo"
  artist: "Silvestre Méndez Y Su Conjunto"
  album: "Soy Rumbero"
  year: 2010
  genre: "Perlas Cubanas"
  url: "https://www.youtube.com/watch?v=CQw5hkO667E"

-
  file: "domingo-primoroso.mp3"
  title: "Domingo Primoroso"
  artist: "Silvestre Méndez Y Su Conjunto"
  album: "Soy Rumbero"
  year: 2010
  genre: "Perlas Cubanas"
  url: "https://www.youtube.com/watch?v=p_vtU4PDo9o"

-
  file: "fiesta-de-animales.mp3"
  title: "Fiesta De Animales"
  artist: "Silvestre Méndez Y Su Conjunto"
  album: "Soy Rumbero"
  year: 2010
  genre: "Perlas Cubanas"
  url: "https://www.youtube.com/watch?v=SPhQUtTF-mQ"

