# Topic: https://www.youtube.com/channel/UCvjUa-uXAY5v6mcpDs4Xo3Q

-
  file: "voy-pa-arriba.mp3"
  title: "Voy Pa' Arriba"
  artist: "Yoruba Andabo"
  album: "Soy De La Tierra Brava"
  year: 2016
  genre: "Rumba"
  url: "https://www.youtube.com/watch?v=cvGeyFghDfI"

-
  file: "columbia-de-ara-oko.mp3"
  title: "Columbia De Ara Oko"
  artist: "Yoruba Andabo"
  album: "Rumba, rumbero (Rumba Cubana)"
  year: 2014
  genre: "Rumba"
  url: "https://www.youtube.com/watch?v=A0BY2R40PgY"

-
  file: "ponte-pa-lo-tuyo.mp3"
  title: "Ponte Pa' Lo Tuyo"
  artist: "Yoruba Andabo"
  album: "Dale cuero (Rumba Cubana)"
  year: 2014
  genre: "Rumba"
  url: "https://www.youtube.com/watch?v=jloHU2lLKS0"

-
  file: "la-cafetera.mp3"
  title: "La Cafetera"
  artist: "Yoruba Andabo"
  album: "Seguimos Sonando"
  year: 2020
  genre: "Rumba"
  url: "https://www.youtube.com/watch?v=KZcbFK3lMMg"

-
  file: "la-cafetera.mp3"
  title: "La Cafetera"
  artist: "Yoruba Andabo"
  album: "Seguimos Sonando"
  year: 2020
  genre: "Rumba"
  url: "https://www.youtube.com/watch?v=KZcbFK3lMMg"

